SDL: GLM_GTX_handed_coordinate_space
GLM_GTX_handed_coordinate_space
GTX Extensions (Experimental)
To know if a set of three basis vectors defines a right or left-handed coordinate system.
Functions
template<typename T >
bool glm::rightHanded (detail::tvec3< T > const &tangent, detail::tvec3< T > const &binormal, detail::tvec3< T > const &normal)
template<typename T >
bool glm::leftHanded (detail::tvec3< T > const &tangent, detail::tvec3< T > const &binormal, detail::tvec3< T > const &normal)
Detailed Description
To know if a set of three basis vectors defines a right or left-handed coordinate system.
<glm/gtx/handed_coordinate_system.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > bool glm::leftHanded (detail::tvec3< T > const & tangent, detail::tvec3< T > const & binormal, detail::tvec3< T > const & normal)
Return if a trihedron left handed or not. From GLM_GTX_handed_coordinate_space extension.
Definition at line 25 of file handed_coordinate_space.inl.
References glm::cross(), glm::dot(), and glm::T.
         {
                 return dot(cross(normal, tangent), binormal) < T(0);
         }
template<typename T > bool glm::rightHanded (detail::tvec3< T > const & tangent, detail::tvec3< T > const & binormal, detail::tvec3< T > const & normal)
Return if a trihedron right handed or not. From GLM_GTX_handed_coordinate_space extension.
Definition at line 14 of file handed_coordinate_space.inl.
References glm::cross(), glm::dot(), and glm::T.
         {
                 return dot(cross(normal, tangent), binormal) > T(0);
         }