SDL: GLM_GTC_ulp
GLM_GTC_ulp
GTC Extensions (Stable)
Allow the measurement of the accuracy of a function against a reference implementation. This extension works on floating-point data and provide results in ULP. <glm/gtc/ulp.hpp> need to be included to use these features.
Functions
template<typename genType >
genType glm::next_float (genType const &x)
template<typename genType >
genType glm::prev_float (genType const &x)
template<typename genType >
genType glm::next_float (genType const &x, uint const &Distance)
template<typename genType >
genType glm::prev_float (genType const &x, uint const &Distance)
template<typename T >
uint glm::float_distance (T const &x, T const &y)
template<typename T , template< typename > class vecType>
vecType< uint > glm::float_distance (vecType< T > const &x, vecType< T > const &y)
Detailed Description
Allow the measurement of the accuracy of a function against a reference implementation. This extension works on floating-point data and provide results in ULP. <glm/gtc/ulp.hpp> need to be included to use these features.
Function Documentation
template<typename T > uint glm::float_distance (T const & x, T const & y)
Return the distance in the number of ULP between 2 scalars.
See also
GLM_GTC_ulp
Definition at line 280 of file ulp.inl.
References glm::max(), glm::next_float(), and glm::T.
Referenced by glm::float_distance().
         {
                 uint ulp = 0;
                 if(x < y)
                 {
                         T temp = x;
                         while(temp != y && ulp < std::numeric_limits<std::size_t>::max())
{
                                 ++ulp;
                                 temp = next_float(temp);
                         }
                 }
                 else if(y < x)
                 {
                         T temp = y;
                         while(temp != x && ulp < std::numeric_limits<std::size_t>::max())
{
                                 ++ulp;
                                 temp = next_float(temp);
                         }
                 }
                 else // ==
                 {
                 }
                 return ulp;
         }
template<typename T , template< typename > class vecType> vecType<uint> glm::float_distance (vecType< T > const & x, vecType< T > const & y)
Return the distance in the number of ULP between 2 vectors.
See also
GLM_GTC_ulp
Definition at line 311 of file ulp.inl.
References glm::float_distance().
         {
                 vecType<uint> Result;
                 for(std::size_t i = 0; i < Result.length(); ++i)
                         Result[i] = float_distance(x[i], y[i]);
                 return Result;
         }
template<typename genType > genType glm::next_float (genType const & x)
Return the next ULP value(s) after the input value(s).
See also
GLM_GTC_ulp
Referenced by glm::float_distance(), and glm::next_float().
template<typename genType > genType glm::next_float (genType const & x, uint const & Distance)
Return the value(s) ULP distance after the input value(s).
See also
GLM_GTC_ulp
template<typename genType > genType glm::prev_float (genType const & x)
Return the previous ULP value(s) before the input value(s).
See also
GLM_GTC_ulp
Referenced by glm::prev_float().
template<typename genType > genType glm::prev_float (genType const & x, uint const & Distance)
Return the value(s) ULP distance before the input value(s).
See also
GLM_GTC_ulp