SDL: GLM_GTX_polar_coordinates
GLM_GTX_polar_coordinates
GTX Extensions (Experimental)
Conversion from Euclidean space to polar space and revert.
Functions
template<typename T >
detail::tvec3< T > glm::polar (detail::tvec3< T > const &euclidean)
template<typename T >
detail::tvec3< T > glm::euclidean (detail::tvec2< T > const &polar)
Detailed Description
Conversion from Euclidean space to polar space and revert.
<glm/gtx/polar_coordinates.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > detail::tvec3<T> glm::euclidean (detail::tvec2< T > const & polar)
Convert Polar to Euclidean coordinates.
See also
GLM_GTX_polar_coordinates
Definition at line 37 of file polar_coordinates.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
 #ifdef GLM_FORCE_RADIANS
                 T const latitude(polar.x);
                 T const longitude(polar.y);
 #else
                 T const latitude(radians(polar.x));
                 T const longitude(radians(polar.y));
 #endif
                 return detail::tvec3<T>(
                         cos(latitude) * sin(longitude),
                         sin(latitude),
                         cos(latitude) * cos(longitude));
         }
template<typename T > detail::tvec3<T> glm::polar (detail::tvec3< T > const & euclidean)
Convert Euclidean to Polar coordinates, x is the xz distance, y, the latitude and z the longitude.
See also
GLM_GTX_polar_coordinates
Definition at line 14 of file polar_coordinates.inl.
References glm::atan(), glm::degrees(), glm::length(), glm::sqrt(), glm::T, glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 T const Length(length(euclidean));
                 detail::tvec3<T> const tmp(euclidean / Length);
                 T const xz_dist(sqrt(tmp.x * tmp.x + tmp.z * tmp.z));
 #ifdef GLM_FORCE_RADIANS
                 return detail::tvec3<T>(
                         atan(xz_dist, tmp.y),   // latitude
                         atan(tmp.x, tmp.z),             // longitude
                         xz_dist);                               // xz distance
 #else
                 return detail::tvec3<T>(
                         degrees(atan(xz_dist, tmp.y)),  // latitude
                         degrees(atan(tmp.x, tmp.z)),    // longitude
                         xz_dist);                                               // xz distance
 #endif
         }