SDL: GLM_GTX_transform
GLM_GTX_transform
GTX Extensions (Experimental)
Add transformation matrices.
Functions
template<typename T >
detail::tmat4x4< T > glm::translate (T x, T y, T z)
template<typename T >
detail::tmat4x4< T > glm::translate (detail::tmat4x4< T > const &m, T x, T y, T z)
template<typename T >
detail::tmat4x4< T > glm::translate (detail::tvec3< T > const &v)
template<typename T >
detail::tmat4x4< T > glm::rotate (T angle, T x, T y, T z)
template<typename T >
detail::tmat4x4< T > glm::rotate (T angle, detail::tvec3< T > const &v)
template<typename T >
detail::tmat4x4< T > glm::rotate (detail::tmat4x4< T > const &m, T angle, T x, T y, T z)
template<typename T >
detail::tmat4x4< T > glm::scale (T x, T y, T z)
template<typename T >
detail::tmat4x4< T > glm::scale (detail::tmat4x4< T > const &m, T x, T y, T z)
template<typename T >
detail::tmat4x4< T > glm::scale (detail::tvec3< T > const &v)
Detailed Description
Add transformation matrices.
<glm/gtx/transform.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > detail::tmat4x4<T> glm::rotate (T angle, T x, T y, T z)
Builds a rotation 4 * 4 matrix created from an axis of 3 scalars and an angle expressed in degrees.
From GLM_GTX_transform extension
Definition at line 39 of file transform.inl.
References glm::rotate().
     {
                 return rotate(
                         detail::tmat4x4<T>(1), angle, detail::tvec3<T>(x, y, z));
     }
template<typename T > detail::tmat4x4<T> glm::rotate (T angle, detail::tvec3< T > const & v)
Builds a rotation 4 * 4 matrix created from an axis of 3 scalars and an angle expressed in degrees.
From GLM_GTX_transform extension
Definition at line 48 of file transform.inl.
References glm::rotate().
     {
                 return rotate(
                         detail::tmat4x4<T>(1), angle, v);
     }
template<typename T > detail::tmat4x4<T> glm::rotate (detail::tmat4x4< T > const & m, T angle, T x, T y, T z)
Transforms a matrix with a rotation 4 * 4 matrix created from an axis of 3 scalars and an angle expressed in degrees.
From GLM_GTX_transform extension
Definition at line 57 of file transform.inl.
References glm::rotate().
     {
                 return rotate(
                         m, angle, detail::tvec3<T>(x, y, z));
     }
template<typename T > detail::tmat4x4<T> glm::scale (T x, T y, T z)
Builds a scale 4 * 4 matrix created from 3 scalars.
From GLM_GTX_transform extension
Definition at line 67 of file transform.inl.
References glm::scale().
     {
                 return scale(
                         detail::tmat4x4<T>(1), detail::tvec3<T>(x, y, z));
     }
template<typename T > detail::tmat4x4<T> glm::scale (detail::tmat4x4< T > const & m, T x, T y, T z)
Transforms a matrix with a scale 4 * 4 matrix created from 3 scalars.
From GLM_GTX_transform extension
Definition at line 74 of file transform.inl.
References glm::scale().
     {
         return scale(
                         m, detail::tvec3<T>(x, y, z));
     }
template<typename T > detail::tmat4x4<T> glm::scale (detail::tvec3< T > const & v)
Transforms a matrix with a scale 4 * 4 matrix created from a vector of 3 components.
From GLM_GTX_transform extension
Definition at line 83 of file transform.inl.
References glm::scale().
     {
         return scale(
                         detail::tmat4x4<T>(1.0f), v);
     }
template<typename T > detail::tmat4x4<T> glm::translate (T x, T y, T z)
Builds a translation 4 * 4 matrix created from 3 scalars.
From GLM_GTX_transform extension
Definition at line 13 of file transform.inl.
References glm::translate().
     {
                 return translate(
                         detail::tmat4x4<T>(1.0f),
                         detail::tvec3<T>(x, y , z));
     }
template<typename T > detail::tmat4x4<T> glm::translate (detail::tmat4x4< T > const & m, T x, T y, T z)
Transforms a matrix with a translation 4 * 4 matrix created from 3 scalars.
From GLM_GTX_transform extension
Definition at line 22 of file transform.inl.
References glm::translate().
     {
         return translate(
                         m, detail::tvec3<T>(x, y , z));
     }
template<typename T > detail::tmat4x4<T> glm::translate (detail::tvec3< T > const & v)
Transforms a matrix with a translation 4 * 4 matrix created from 3 scalars.
From GLM_GTX_transform extension
Definition at line 31 of file transform.inl.
References glm::translate().
     {
                 return translate(
                         detail::tmat4x4<T>(1.0f), v);
     }