SDL: GLM_GTX_fast_square_root
GLM_GTX_fast_square_root
GTX Extensions (Experimental)
Fast but less accurate implementations of square root based functions.
Functions
template<typename genType >
genType glm::fastSqrt (genType const &x)
template<typename genType >
genType glm::fastInverseSqrt (genType const &x)
template<typename genType >
genType::value_type glm::fastLength (genType const &x)
template<typename genType >
genType::value_type glm::fastDistance (genType const &x, genType const &y)
template<typename genType >
genType glm::fastNormalize (genType const &x)
Detailed Description
Fast but less accurate implementations of square root based functions.
Sqrt optimisation based on Newton's method, www.gamedev.net/community/forums/topic.asp?topic id=139956
<glm/gtx/fast_square_root.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > genType::value_type glm::fastDistance (genType const & x, genType const & y)
Faster than the common distance function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 89 of file fast_square_root.inl.
References glm::fastLength().
         {
                 return fastLength(y - x);
         }
template<typename genType > genType glm::fastInverseSqrt (genType const & x)
Faster than the common inversesqrt function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 29 of file fast_square_root.inl.
References glm::detail::uif32::f.
Referenced by glm::fastNormalize(), glm::fastNormalizeDot(), and glm::fastSqrt().
         {
                 genType tmp = x;
                 float xhalf = 0.5f * float(tmp);
                 uint i = *(uint*)&x;
                 i = 0x5f375a86 - (i >> 1);
                 //x = *(float*)&i;
                 //x = *((float*)(char*)&i);
                 tmp = detail::uif(i).f;
                 tmp = tmp * (1.5f - xhalf * tmp * tmp);
                 return genType(tmp);
         }
template<typename genType > genType::value_type glm::fastLength (genType const & x)
Faster than the common length function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 49 of file fast_square_root.inl.
References glm::abs().
Referenced by glm::fastDistance().
         {
                 return abs(x);
         }
template<typename genType > genType glm::fastNormalize (genType const & x)
Faster than the common normalize function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 100 of file fast_square_root.inl.
         {
                 return x > genType(0) ? genType(1) : -genType(1);
         }
template<typename genType > genType glm::fastSqrt (genType const & x)
Faster than the common sqrt function but less accurate. From GLM_GTX_fast_square_root extension.
Definition at line 15 of file fast_square_root.inl.
References glm::fastInverseSqrt(), and GLM_STATIC_ASSERT.
Referenced by glm::fastLength(), and glm::fastLength4().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'fastSqrt' only accept floating-point input");
                 return genType(1) / fastInverseSqrt(x);
         }