SDL: Exponential functions
Exponential functions
GLM Core
Functions
template<typename genType >
GLM_FUNC_DECL genType glm::pow (genType const &base, genType const &exponent)
template<typename genType >
GLM_FUNC_DECL genType glm::exp (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::log (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::exp2 (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::log2 (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::sqrt (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::inversesqrt (genType const &x)
Detailed Description
These all operate component-wise. The description is per component.
Function Documentation
template<typename genType > GLM_FUNC_DECL genType glm::exp (genType const & x)
Returns the natural exponentiation of x, i.e., e^x.
Parameters
x exp function is defined for input values of x defined in the range (inf-, inf+) in the limit of the type precision.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL exp man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 49 of file func_exponential.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::exp2(), glm::fastPow(), and glm::intermediate().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'exp' only accept floating-point input");
                 return genType(::std::exp(x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::exp2 (genType const & x)
Returns 2 raised to the x power.
Parameters
x exp2 function is defined for input values of x defined in the range (inf-, inf+) in the limit of the type precision.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL exp2 man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 77 of file func_exponential.inl.
References glm::exp(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'exp2' only accept floating-point input");
                 return genType(::std::exp(genType(0.69314718055994530941723212145818) * x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::inversesqrt (genType const & x)
Returns the reciprocal of the positive square root of x.
Parameters
x inversesqrt function is defined for input values of x defined in the range [0, inf+) in the limit of the type precision.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL inversesqrt man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 144 of file func_exponential.inl.
References GLM_STATIC_ASSERT, and glm::sqrt().
Referenced by glm::normalize(), glm::normalizeDot(), and glm::sqrt().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'inversesqrt' only accept floating-point input");
                 assert(x > genType(0));
                 return genType(1) / ::std::sqrt(x);
         }
template<typename genType > GLM_FUNC_DECL genType glm::log (genType const & x)
Returns the natural logarithm of x, i.e., returns the value y which satisfies the equation x = e^y. Results are undefined if x <= 0.
Parameters
x log function is defined for input values of x defined in the range (0, inf+) in the limit of the type precision.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL log man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 63 of file func_exponential.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::acosh(), glm::asinh(), glm::atanh(), glm::fastLog(), glm::fastPow(), glm::gaussRand(), glm::intermediate(), glm::log(), and glm::_detail::_compute_log2< detail::float_or_int_value::GLM_FLOAT >::operator()().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'log' only accept floating-point input");
                 return genType(::std::log(x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::log2 (genType const & x)
Returns the base 2 log of x, i.e., returns the value y, which satisfies the equation x = 2 ^ y.
Parameters
x log2 function is defined for input values of x defined in the range (0, inf+) in the limit of the type precision.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL log2 man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 118 of file func_exponential.inl.
         {
                 assert(x > genType(0)); // log2 is only defined on the range (0, inf]
                 return _detail::_compute_log2<detail::float_or_int_trait<genType>::ID>()(x);
         }
template<typename genType > GLM_FUNC_DECL genType glm::pow (genType const & base, genType const & exponent)
Returns 'base' raised to the power 'exponent'.
Parameters
base Floating point value. pow function is defined for input values of x defined in the range (inf-, inf+) in the limit of the type precision.
exponent Floating point value representing the 'exponent'.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL pow man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 34 of file func_exponential.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::lxNorm().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'pow' only accept floating-point input");
                 return genType(::std::pow(x, y));
         }
template<typename genType > GLM_FUNC_DECL genType glm::sqrt (genType const & x)
Returns the positive square root of x.
Parameters
x sqrt function is defined for input values of x defined in the range [0, inf+) in the limit of the type precision.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL sqrt man page
GLSL 4.20.8 specification, section 8.2 Exponential Functions
Definition at line 131 of file func_exponential.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::acosh(), glm::asinh(), glm::axis(), glm::axisAngle(), glm::extractRealComponent(), glm::gaussRand(), glm::intersectLineSphere(), glm::intersectRaySphere(), glm::inversesqrt(), glm::length(), glm::length4(), glm::log(), glm::polar(), glm::quat_cast(), glm::radialGradient(), glm::refract(), glm::shortMix(), and glm::sphericalRand().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'sqrt' only accept floating-point input");
                 return genType(::std::sqrt(x));
         }