SDL: Common functions
Common functions
GLM Core
Functions
template<typename genType >
GLM_FUNC_DECL genType glm::abs (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::sign (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::floor (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::trunc (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::round (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::roundEven (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::ceil (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::fract (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::mod (genType const &x, genType const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::mod (genType const &x, typename genType::value_type const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::modf (genType const &x, genType &i)
template<typename genType >
GLM_FUNC_DECL genType glm::min (genType const &x, genType const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::min (genType const &x, typename genType::value_type const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::max (genType const &x, genType const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::max (genType const &x, typename genType::value_type const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::clamp (genType const &x, genType const &minVal, genType const &maxVal)
template<typename genType >
GLM_FUNC_DECL genType glm::clamp (genType const &x, typename genType::value_type const &minVal, typename genType::value_type const &maxVal)
template<typename genTypeT , typename genTypeU >
GLM_FUNC_DECL genTypeT glm::mix (genTypeT const &x, genTypeT const &y, genTypeU const &a)
template<typename genType >
GLM_FUNC_DECL genType glm::step (genType const &edge, genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::step (typename genType::value_type const &edge, genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::smoothstep (genType const &edge0, genType const &edge1, genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::smoothstep (typename genType::value_type const &edge0, typename genType::value_type const &edge1, genType const &x)
template<typename genType >
GLM_FUNC_DECL genType::bool_type glm::isnan (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType::bool_type glm::isinf (genType const &x)
template<typename genType , typename genIType >
GLM_FUNC_DECL genIType glm::floatBitsToInt (genType const &value)
template<typename genType , typename genUType >
GLM_FUNC_DECL genUType glm::floatBitsToUint (genType const &value)
template<typename genType , typename genIType >
GLM_FUNC_DECL genType glm::intBitsToFloat (genIType const &value)
template<typename genType , typename genUType >
GLM_FUNC_DECL genType glm::uintBitsToFloat (genUType const &value)
template<typename genType >
GLM_FUNC_DECL genType glm::fma (genType const &a, genType const &b, genType const &c)
template<typename genType , typename genIType >
GLM_FUNC_DECL genType glm::frexp (genType const &x, genIType &exp)
template<typename genType , typename genIType >
GLM_FUNC_DECL genType glm::ldexp (genType const &x, genIType const &exp)
Detailed Description
These all operate component-wise. The description is per component.
Function Documentation
template<typename genType > GLM_FUNC_DECL genType glm::abs (genType const & x)
Returns x if x >= 0; otherwise, it returns -x.
Template Parameters
genType floating-point or signed integer; scalar or vector types.
See also
GLSL abs man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::areOrthogonal(), glm::areOrthonormal(), glm::asinh(), glm::atanh(), glm::axisAngle(), glm::epsilonEqual(), glm::epsilonNotEqual(), glm::fastAtan(), glm::fastLength(), glm::grad4(), glm::isCompNull(), glm::isIdentity(), glm::isNormalized(), glm::isPowerOfTwo(), glm::l1Norm(), glm::noise1(), glm::perlin(), glm::pow(), glm::rotate(), and glm::simplex().
template<typename genType > GLM_FUNC_DECL genType glm::ceil (genType const & x)
Returns a value equal to the nearest integer that is greater than or equal to x.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL ceil man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 184 of file func_common.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'ceil' only accept floating-point inputs");
                 return ::std::ceil(x);
         }
template<typename genType > GLM_FUNC_DECL genType glm::clamp (genType const & x, genType const & minVal, genType const & maxVal)
Returns min(max(x, minVal), maxVal) for each component in x using the floating-point values minVal and maxVal.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
GLSL clamp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::clamp(), glm::noise1(), glm::packSnorm2x16(), glm::packSnorm4x8(), glm::packUnorm2x16(), glm::packUnorm4x8(), glm::saturate(), glm::simplex(), glm::smoothstep(), glm::unpackSnorm2x16(), and glm::unpackSnorm4x8().
template<typename genType > GLM_FUNC_DECL genType glm::clamp (genType const & x, typename genType::value_type const & minVal, typename genType::value_type const & maxVal)
template<typename genType , typename genIType > GLM_FUNC_DECL genIType glm::floatBitsToInt (genType const & value)
Returns a signed integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
Template Parameters
genType Single-precision floating-point scalar or vector types.
genIType Signed integer scalar or vector types.
See also
GLSL floatBitsToInt man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::floatBitsToInt().
template<typename genType , typename genUType > GLM_FUNC_DECL genUType glm::floatBitsToUint (genType const & value)
Returns a unsigned integer value representing the encoding of a floating-point value. The floatingpoint value's bit-level representation is preserved.
Template Parameters
genType Single-precision floating-point scalar or vector types.
genUType Unsigned integer scalar or vector types.
See also
GLSL floatBitsToUint man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::floatBitsToUint().
template<typename genType > GLM_FUNC_DECL genType glm::floor (genType const & x)
Returns a value equal to the nearest integer that is less then or equal to x.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL floor man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 105 of file func_common.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::floor< detail::half >(), glm::fract(), glm::grad4(), glm::mirrorRepeat(), glm::mod(), glm::mod289(), glm::noise1(), glm::perlin(), glm::rgbColor(), glm::simplex(), and glm::trunc().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'floor' only accept floating-point inputs");
                 return ::std::floor(x);
         }
template<typename genType > GLM_FUNC_DECL genType glm::fma (genType const & a, genType const & b, genType const & c)
Computes and returns a * b + c.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL fma man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 1137 of file func_common.inl.
         {
                 return a * b + c;
         }
template<typename genType > GLM_FUNC_DECL genType glm::fract (genType const & x)
Return x - floor(x).
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL fract man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 196 of file func_common.inl.
References glm::floor(), and GLM_STATIC_ASSERT.
Referenced by glm::grad4(), glm::noise1(), glm::perlin(), glm::repeat(), glm::roundEven(), and glm::simplex().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'fract' only accept floating-point inputs");
                 return x - ::std::floor(x);
         }
template<typename genType , typename genIType > GLM_FUNC_DECL genType glm::frexp (genType const & x, genIType & exp)
Splits x into a floating-point significand in the range [0.5, 1.0) and an integral exponent of two, such that: x = significand * exp(2, exponent)
The significand is returned by the function and the exponent is returned in the parameter exp. For a floating-point value of zero, the significant and exponent are both zero. For a floating-point value that is an infinity or is not a number, the results are undefined.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL frexp man page
GLSL 4.20.8 specification, section 8.3 Common Functions
template<typename genType , typename genIType > GLM_FUNC_DECL genType glm::intBitsToFloat (genIType const & value)
Returns a floating-point value corresponding to a signed integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
Template Parameters
genType Single-precision floating-point scalar or vector types.
genIType Signed integer scalar or vector types.
See also
GLSL intBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Todo:
Clarify this declaration, we don't need to actually specify the return type
Referenced by glm::intBitsToFloat().
template<typename genType > GLM_FUNC_DECL genType::bool_type glm::isinf (genType const & x)
Returns true if x holds a positive infinity or negative infinity representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no infinity representations.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL isinf man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 897 of file func_common.inl.
References GLM_STATIC_ASSERT, and glm::isinf().
Referenced by glm::isinf().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'isinf' only accept floating-point inputs");
 #               if(GLM_COMPILER & (GLM_COMPILER_INTEL | GLM_COMPILER_VC))
                         return _fpclass(x) == _FPCLASS_NINF || _fpclass(x) == _FPCLASS_PINF;
 #               elif(GLM_COMPILER & (GLM_COMPILER_GCC | GLM_COMPILER_CLANG))
 #                       if(GLM_PLATFORM & GLM_PLATFORM_ANDROID)
                                 return _isinf(x) != 0;
 #                       else
                                 return std::isinf(x);
 #                       endif
 #               elif(GLM_COMPILER & GLM_COMPILER_CUDA)
                         // http://developer.download.nvidia.com/compute/cuda/4_2/rel/toolkit/docs/online/group__CUDA__MATH__DOUBLE_g13431dd2b40b51f9139cbb7f50c18fab.html#g13431dd2b40b51f9139cbb7f50c18fab
                         return isinf(double(x)) != 0;
 #               else
                         return std::isinf(x);
 #               endif
         }
template<typename genType > GLM_FUNC_DECL genType::bool_type glm::isnan (genType const & x)
Returns true if x holds a NaN (not a number) representation in the underlying implementation's set of floating point representations. Returns false otherwise, including for implementations with no NaN representations.
/!\ When using compiler fast math, this function may fail.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL isnan man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 841 of file func_common.inl.
References GLM_STATIC_ASSERT, and glm::isnan().
Referenced by glm::isnan().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'isnan' only accept floating-point inputs");
 #               if(GLM_COMPILER & (GLM_COMPILER_VC | GLM_COMPILER_INTEL))
                         return _isnan(x) != 0;
 #               elif(GLM_COMPILER & (GLM_COMPILER_GCC | GLM_COMPILER_CLANG))
 #                       if(GLM_PLATFORM & GLM_PLATFORM_ANDROID)
                                 return _isnan(x) != 0;
 #                       else
                                 return std::isnan(x);
 #                       endif
 #               elif(GLM_COMPILER & GLM_COMPILER_CUDA)
                         return isnan(x) != 0;
 #               else
                         return std::isnan(x);
 #               endif
         }
template<typename genType , typename genIType > GLM_FUNC_DECL genType glm::ldexp (genType const & x, genIType const & exp)
Builds a floating-point number from x and the corresponding integral exponent of two in exp, returning: significand * exp(2, exponent)
If this product is too large to be represented in the floating-point type, the result is undefined.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL ldexp man page;
GLSL 4.20.8 specification, section 8.3 Common Functions
template<typename genType > GLM_FUNC_DECL genType glm::max (genType const & x, genType const & y)
Returns y if x < y; otherwise, it returns x.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
GLSL max man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 305 of file func_common.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::areOrthogonal(), glm::associatedMax(), glm::clamp(), glm::compMax(), glm::float_distance(), glm::hsvColor(), glm::max(), glm::next_float(), glm::noise1(), and glm::simplex().
         {
                 GLM_STATIC_ASSERT(
                         detail::type<genType>::is_float ||
                         detail::type<genType>::is_int ||
                         detail::type<genType>::is_uint, "'max' only accept numbers");
                 return x > y ? x : y;
         }
template<typename genType > GLM_FUNC_DECL genType glm::max (genType const & x, typename genType::value_type const & y)
template<typename genType > GLM_FUNC_DECL genType glm::min (genType const & x, genType const & y)
Returns y if y < x; otherwise, it returns x.
Template Parameters
genType Floating-point or integer; scalar or vector types.
See also
GLSL min man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 286 of file func_common.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::associatedMin(), glm::clamp(), glm::compMin(), glm::hsvColor(), glm::min(), glm::noise1(), glm::prev_float(), and glm::simplex().
         {
                 GLM_STATIC_ASSERT(
                         detail::type<genType>::is_float ||
                         detail::type<genType>::is_int ||
                         detail::type<genType>::is_uint, "'min' only accept numbers");
                 return x < y ? x : y;
         }
template<typename genType > GLM_FUNC_DECL genType glm::min (genType const & x, typename genType::value_type const & y)
template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT glm::mix (genTypeT const & x, genTypeT const & y, genTypeU const & a)
If genTypeU is a floating scalar or vector: Returns x * (1.0 - a) + y * a, i.e., the linear blend of x and y using the floating-point value a. The value for a is not restricted to the range [0, 1].
If genTypeU is a boolean scalar or vector: Selects which vector each returned component comes from. For a component of that is false, the corresponding component of x is returned. For a component of a that is true, the corresponding component of y is returned. Components of x and y that are not selected are allowed to be invalid floating point values and will have no effect on the results. Thus, this provides different functionality than genType mix(genType x, genType y, genType(a)) where a is a Boolean vector.
See also
GLSL mix man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Parameters
[in] x Value to interpolate.
[in] y Value to interpolate.
[in] a Interpolant.
Template Parameters
genTypeT Floating point scalar or vector.
genTypeU Floating point or boolean scalar or vector. It can't be a vector if it is the length of genTypeT.
#include <glm/glm.hpp>
...
float a;
bool b;
glm::dvec3 e;
glm::dvec3 f;
glm::vec4 g;
glm::vec4 h;
...
glm::vec4 r = glm::mix(g, h, a); // Interpolate with a floating-point scalar two vectors.
glm::vec4 s = glm::mix(g, h, b); // Teturns g or h;
glm::dvec3 t = glm::mix(e, f, a); // Types of the third parameter is not required to match with the first and the second.
glm::vec4 u = glm::mix(g, h, r); // Interpolations can be perform per component with a vector for the last parameter.
Referenced by glm::lerp(), glm::mix(), glm::perlin(), glm::slerp(), and glm::squad().
template<typename genType > GLM_FUNC_DECL genType glm::mod (genType const & x, genType const & y)
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL mod man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 210 of file func_common.inl.
References glm::floor(), and GLM_STATIC_ASSERT.
Referenced by glm::noise1(), glm::perlin(), and glm::simplex().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'mod' only accept floating-point inputs");
                 return x - y * floor(x / y);
         }
template<typename genType > GLM_FUNC_DECL genType glm::mod (genType const & x, typename genType::value_type const & y)
Modulus. Returns x - y * floor(x / y) for each component in x using the floating point value y.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL mod man page
GLSL 4.20.8 specification, section 8.3 Common Functions
template<typename genType > GLM_FUNC_DECL genType glm::modf (genType const & x, genType & i)
Returns the fractional part of x and sets i to the integer part (as a whole number floating point value). Both the return value and the output parameter will have the same sign as x.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL modf man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 226 of file func_common.inl.
References GLM_STATIC_ASSERT, and glm::modf().
Referenced by glm::modf().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'modf' only accept floating-point inputs");
                 return std::modf(x, &i);
         }
template<typename genType > GLM_FUNC_DECL genType glm::round (genType const & x)
Returns a value equal to the nearest integer to x. The fraction 0.5 will round in a direction chosen by the implementation, presumably the direction that is fastest. This includes the possibility that round(x) returns the same value as roundEven(x) for all values of x.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL round man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 126 of file func_common.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::packSnorm2x16(), glm::packSnorm4x8(), glm::packUnorm2x16(), glm::packUnorm4x8(), and glm::roundEven().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'round' only accept floating-point inputs");
                 if(x < 0)
                         return genType(int(x - genType(0.5)));
                 return genType(int(x + genType(0.5)));
         }
template<typename genType > GLM_FUNC_DECL genType glm::roundEven (genType const & x)
Returns a value equal to the nearest integer to x. A fractional part of 0.5 will round toward the nearest even integer. (Both 3.5 and 4.5 for x will return 4.0.)
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL roundEven man page
GLSL 4.20.8 specification, section 8.3 Common Functions
New round to even technique
Definition at line 150 of file func_common.inl.
References glm::fract(), GLM_STATIC_ASSERT, int(), and glm::round().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'roundEven' only accept floating-point inputs");
                 int Integer = int(x);
                 genType IntegerPart = genType(Integer);
                 genType FractionalPart = fract(x);
                 if(FractionalPart > genType(0.5) || FractionalPart < genType(0.5))
                 {
                         return round(x);
                 }
                 else if((Integer % 2) == 0)
                 {
                         return IntegerPart;
                 }
                 else if(x <= genType(0)) // Work around...
                 {
                         return IntegerPart - 1;
                 }
                 else
                 {
                         return IntegerPart + 1;
                 }
                 //else // Bug on MinGW 4.5.2
                 //{
                 //      return mix(IntegerPart + genType(-1), IntegerPart + genType(1), x <= genType(0));
                 //}
         }
template<typename genType > GLM_FUNC_DECL genType glm::sign (genType const & x)
Returns 1.0 if x > 0, 0.0 if x == 0, or -1.0 if x < 0.
Template Parameters
genType Floating-point or signed integer; scalar or vector types.
See also
GLSL sign man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Referenced by glm::fastAtan().
template<typename genType > GLM_FUNC_DECL genType glm::smoothstep (genType const & edge0, genType const & edge1, genType const & x)
Returns 0.0 if x <= edge0 and 1.0 if x >= edge1 and performs smooth Hermite interpolation between 0 and 1 when edge0 < x < edge1. This is useful in cases where you would want a threshold function with a smooth transition. This is equivalent to: genType t; t = clamp ((x - edge0) / (edge1 - edge0), 0, 1); return t * t * (3 - 2 * t); Results are undefined if edge0 >= edge1.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL smoothstep man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 743 of file func_common.inl.
References glm::clamp(), and GLM_STATIC_ASSERT.
Referenced by glm::smoothstep().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'smoothstep' only accept floating-point inputs");
                 genType tmp = clamp((x - edge0) / (edge1 - edge0), genType(0), genType(1));
                 return tmp * tmp * (genType(3) - genType(2) * tmp);
         }
template<typename genType > GLM_FUNC_DECL genType glm::smoothstep (typename genType::value_type const & edge0, typename genType::value_type const & edge1, genType const & x)
template<typename genType > GLM_FUNC_DECL genType glm::step (genType const & edge, genType const & x)
Returns 0.0 if x < edge, otherwise it returns 1.0.
See also
GLSL step man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 652 of file func_common.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::noise1(), glm::perlin(), and glm::simplex().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'step' only accept floating-point inputs");
                 return x < edge ? genType(0) : genType(1);
         }
template<typename genType > GLM_FUNC_DECL genType glm::step (typename genType::value_type const & edge, genType const & x)
template<typename genType > GLM_FUNC_DECL genType glm::trunc (genType const & x)
Returns a value equal to the nearest integer to x whose absolute value is not larger than the absolute value of x.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL trunc man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Definition at line 116 of file func_common.inl.
References glm::floor(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'trunc' only accept floating-point inputs");
                 return x < 0 ? -floor(-x) : floor(x);
         }
template<typename genType , typename genUType > GLM_FUNC_DECL genType glm::uintBitsToFloat (genUType const & value)
Returns a floating-point value corresponding to a unsigned integer encoding of a floating-point value. If an inf or NaN is passed in, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit-level representation is preserved.
Template Parameters
genType Single-precision floating-point scalar or vector types.
genUType Unsigned integer scalar or vector types.
See also
GLSL uintBitsToFloat man page
GLSL 4.20.8 specification, section 8.3 Common Functions
Todo:
Clarify this declaration, we don't need to actually specify the return type
Referenced by glm::uintBitsToFloat().