SDL: GLM_GTC_random
GLM_GTC_random
GTC Extensions (Stable)
Generate random number from various distribution methods.
Functions
template<typename genType >
genType glm::linearRand (genType const &Min, genType const &Max)
template<typename genType >
genType glm::gaussRand (genType const &Mean, genType const &Deviation)
template<typename T >
detail::tvec2< T > glm::circularRand (T const &Radius)
template<typename T >
detail::tvec3< T > glm::sphericalRand (T const &Radius)
template<typename T >
detail::tvec2< T > glm::diskRand (T const &Radius)
template<typename T >
GLM_FUNC_QUALIFIER
detail::tvec3< T > glm::ballRand (T const &Radius)
Detailed Description
Generate random number from various distribution methods.
<glm/gtc/random.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > GLM_FUNC_QUALIFIER detail::tvec3< T > glm::ballRand (T const & Radius)
Generate a random 3D vector which coordinates are regulary distributed within the volume of a ball of a given radius
Parameters
Radius
See also
GLM_GTC_random
Definition at line 127 of file random.inl.
References glm::length(), glm::linearRand(), and glm::T.
         {
                 detail::tvec3<T> Result(T(0));
                 T LenRadius(T(0));
                 do
                 {
                         Result = linearRand(detail::tvec3<T>(-Radius), detail::tvec3<T>(Radius));
                         LenRadius = length(Result);
                 }
                 while(LenRadius > Radius);
                 return Result;
         }
template<typename T > detail::tvec2<T> glm::circularRand (T const & Radius)
Generate a random 2D vector which coordinates are regulary distributed on a circle of a given radius
Parameters
Radius
See also
GLM_GTC_random
Definition at line 146 of file random.inl.
References glm::cos(), glm::linearRand(), glm::sin(), and glm::T.
         {
                 T a = linearRand(T(0), T(6.283185307179586476925286766559f));
                 return detail::tvec2<T>(cos(a), sin(a)) * Radius;
         }
template<typename T > detail::tvec2<T> glm::diskRand (T const & Radius)
Generate a random 2D vector which coordinates are regulary distributed within the area of a disk of a given radius
Parameters
Radius
See also
GLM_GTC_random
Definition at line 108 of file random.inl.
References glm::length(), glm::linearRand(), and glm::T.
         {
                 detail::tvec2<T> Result(T(0));
                 T LenRadius(T(0));
                 do
                 {
                         Result = linearRand(detail::tvec2<T>(-Radius), detail::tvec2<T>(Radius));
                         LenRadius = length(Result);
                 }
                 while(LenRadius > Radius);
                 return Result;
         }
template<typename genType > genType glm::gaussRand (genType const & Mean, genType const & Deviation)
Generate random numbers in the interval [Min, Max], according a gaussian distribution
Parameters
Mean
Deviation
See also
GLM_GTC_random
Definition at line 86 of file random.inl.
References glm::linearRand(), glm::log(), and glm::sqrt().
         {
                 genType w, x1, x2;
                 do
                 {
                         x1 = linearRand(genType(-1), genType(1));
                         x2 = linearRand(genType(-1), genType(1));
                         w = x1 * x1 + x2 * x2;
                 } while(w > genType(1));
                 return x2 * Deviation * Deviation * sqrt((genType(-2) * log(w)) / w) + Mean;
         }
template<typename genType > genType glm::linearRand (genType const & Min, genType const & Max)
Generate random numbers in the interval [Min, Max], according a linear distribution
Parameters
Min
Max
Template Parameters
genType Value type. Currently supported: half (not recommanded), float or double scalars and vectors.
See also
GLM_GTC_random
Definition at line 74 of file random.inl.
Referenced by glm::ballRand(), glm::circularRand(), glm::diskRand(), glm::gaussRand(), and glm::sphericalRand().
         {
                 return detail::compute_linearRand()(Min, Max);
         }
template<typename T > detail::tvec3<T> glm::sphericalRand (T const & Radius)
Generate a random 3D vector which coordinates are regulary distributed on a sphere of a given radius
Parameters
Radius
See also
GLM_GTC_random
Definition at line 156 of file random.inl.
References glm::cos(), glm::linearRand(), glm::sin(), glm::sqrt(), and glm::T.
         {
                 T z = linearRand(T(-1), T(1));
                 T a = linearRand(T(0), T(6.283185307179586476925286766559f));
                 T r = sqrt(T(1) - z * z);
                 T x = r * cos(a);
                 T y = r * sin(a);
                 return detail::tvec3<T>(x, y, z) * Radius;
         }