SDL: GLM_GTX_extented_min_max
GLM_GTX_extented_min_max
GTX Extensions (Experimental)
Functions
template<typename T >
T glm::min (T const &x, T const &y, T const &z)
template<typename T , template< typename > class C>
C< T > glm::min (C< T > const &x, typename C< T >::value_type const &y, typename C< T >::value_type const &z)
template<typename T , template< typename > class C>
C< T > glm::min (C< T > const &x, C< T > const &y, C< T > const &z)
template<typename T >
T glm::min (T const &x, T const &y, T const &z, T const &w)
template<typename T , template< typename > class C>
C< T > glm::min (C< T > const &x, typename C< T >::value_type const &y, typename C< T >::value_type const &z, typename C< T >::value_type const &w)
template<typename T , template< typename > class C>
C< T > glm::min (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)
template<typename T >
T glm::max (T const &x, T const &y, T const &z)
template<typename T , template< typename > class C>
C< T > glm::max (C< T > const &x, typename C< T >::value_type const &y, typename C< T >::value_type const &z)
template<typename T , template< typename > class C>
C< T > glm::max (C< T > const &x, C< T > const &y, C< T > const &z)
template<typename T >
T glm::max (T const &x, T const &y, T const &z, T const &w)
template<typename T , template< typename > class C>
C< T > glm::max (C< T > const &x, typename C< T >::value_type const &y, typename C< T >::value_type const &z, typename C< T >::value_type const &w)
template<typename T , template< typename > class C>
C< T > glm::max (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)
Detailed Description
Min and max functions for 3 to 4 parameters.
<glm/gtx/extented_min_max.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > T glm::max (T const & x, T const & y, T const & z)
Return the maximum component-wise values of 3 inputs
See also
GLM_GTX_extented_min_max
Definition at line 96 of file extented_min_max.inl.
References glm::max().
         {
                 return glm::max(glm::max(x, y), z);
         }
template<typename T , template< typename > class C> C<T> glm::max (C< T > const & x, typename C< T >::value_type const & y, typename C< T >::value_type const & z)
Return the maximum component-wise values of 3 inputs
See also
GLM_GTX_extented_min_max
Definition at line 110 of file extented_min_max.inl.
References glm::max().
         {
                 return glm::max(glm::max(x, y), z);
         }
template<typename T , template< typename > class C> C<T> glm::max (C< T > const & x, C< T > const & y, C< T > const & z)
Return the maximum component-wise values of 3 inputs
See also
GLM_GTX_extented_min_max
Definition at line 125 of file extented_min_max.inl.
References glm::max().
         {
                 return glm::max(glm::max(x, y), z);
         }
template<typename T > T glm::max (T const & x, T const & y, T const & z, T const & w)
Return the maximum component-wise values of 4 inputs
See also
GLM_GTX_extented_min_max
Definition at line 136 of file extented_min_max.inl.
References glm::max().
         {
                 return glm::max(glm::max(x, y), glm::max(z, w));
         }
template<typename T , template< typename > class C> C<T> glm::max (C< T > const & x, typename C< T >::value_type const & y, typename C< T >::value_type const & z, typename C< T >::value_type const & w)
Return the maximum component-wise values of 4 inputs
See also
GLM_GTX_extented_min_max
Definition at line 152 of file extented_min_max.inl.
References glm::max().
         {
                 return glm::max(glm::max(x, y), glm::max(z, w));
         }
template<typename T , template< typename > class C> C<T> glm::max (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w)
Return the maximum component-wise values of 4 inputs
See also
GLM_GTX_extented_min_max
Definition at line 168 of file extented_min_max.inl.
References glm::max().
         {
                 return glm::max(glm::max(x, y), glm::max(z, w));
         }
template<typename T > T glm::min (T const & x, T const & y, T const & z)
Return the minimum component-wise values of 3 inputs
See also
GLM_GTX_extented_min_max
Definition at line 13 of file extented_min_max.inl.
References glm::min().
         {
                 return glm::min(glm::min(x, y), z);
         }
template<typename T , template< typename > class C> C<T> glm::min (C< T > const & x, typename C< T >::value_type const & y, typename C< T >::value_type const & z)
Return the minimum component-wise values of 3 inputs
See also
GLM_GTX_extented_min_max
Definition at line 27 of file extented_min_max.inl.
References glm::min().
         {
                 return glm::min(glm::min(x, y), z);
         }
template<typename T , template< typename > class C> C<T> glm::min (C< T > const & x, C< T > const & y, C< T > const & z)
Return the minimum component-wise values of 3 inputs
See also
GLM_GTX_extented_min_max
Definition at line 42 of file extented_min_max.inl.
References glm::min().
         {
                 return glm::min(glm::min(x, y), z);
         }
template<typename T > T glm::min (T const & x, T const & y, T const & z, T const & w)
Return the minimum component-wise values of 4 inputs
See also
GLM_GTX_extented_min_max
Definition at line 53 of file extented_min_max.inl.
References glm::min().
         {
                 return glm::min(glm::min(x, y), glm::min(z, w));
         }
template<typename T , template< typename > class C> C<T> glm::min (C< T > const & x, typename C< T >::value_type const & y, typename C< T >::value_type const & z, typename C< T >::value_type const & w)
Return the minimum component-wise values of 4 inputs
See also
GLM_GTX_extented_min_max
Definition at line 69 of file extented_min_max.inl.
References glm::min().
         {
                 return glm::min(glm::min(x, y), glm::min(z, w));
         }
template<typename T , template< typename > class C> C<T> glm::min (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w)
Return the minimum component-wise values of 4 inputs
See also
GLM_GTX_extented_min_max
Definition at line 85 of file extented_min_max.inl.
References glm::min().
         {
                 return glm::min(glm::min(x, y), glm::min(z, w));
         }