SDL: Floating-Point Pack and Unpack Functions
Floating-Point Pack and Unpack Functions
GLM Core
Functions
GLM_FUNC_DECL detail::uint32 glm::packUnorm2x16 (detail::tvec2< detail::float32 > const &v)
GLM_FUNC_DECL detail::uint32 glm::packSnorm2x16 (detail::tvec2< detail::float32 > const &v)
GLM_FUNC_DECL detail::uint32 glm::packUnorm4x8 (detail::tvec4< detail::float32 > const &v)
GLM_FUNC_DECL detail::uint32 glm::packSnorm4x8 (detail::tvec4< detail::float32 > const &v)
GLM_FUNC_DECL detail::tvec2
< detail::float32 > glm::unpackUnorm2x16 (detail::uint32 const &p)
GLM_FUNC_DECL detail::tvec2
< detail::float32 > glm::unpackSnorm2x16 (detail::uint32 const &p)
GLM_FUNC_DECL detail::tvec4
< detail::float32 > glm::unpackUnorm4x8 (detail::uint32 const &p)
GLM_FUNC_DECL detail::tvec4
< detail::float32 > glm::unpackSnorm4x8 (detail::uint32 const &p)
GLM_FUNC_DECL double glm::packDouble2x32 (detail::tvec2< detail::uint32 > const &v)
GLM_FUNC_DECL detail::tvec2
< detail::uint32 > glm::unpackDouble2x32 (double const &v)
GLM_FUNC_DECL uint glm::packHalf2x16 (vec2 const &v)
GLM_FUNC_DECL vec2 glm::unpackHalf2x16 (uint const &v)
Detailed Description
These functions do not operate component-wise, rather as described in each case.
Function Documentation
GLM_FUNC_QUALIFIER double glm::packDouble2x32 (detail::tvec2< detail::uint32 > const & v)
Returns a double-precision value obtained by packing the components of v into a 64-bit value. If an IEEE 754 Inf or NaN is created, it will not signal, and the resulting floating point value is unspecified. Otherwise, the bit- level representation of v is preserved. The first vector component specifies the 32 least significant bits; the second component specifies the 32 most significant bits.
See also
GLSL packDouble2x32 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 137 of file func_packing.inl.
References glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 struct uint32_pair
                 {
                         detail::uint32 x;
                         detail::uint32 y;
                 };
                 union helper
                 {
                         uint32_pair input;
                         double output;
                 } Helper;
                 Helper.input.x = v.x;
                 Helper.input.y = v.y;
                 return Helper.output;
                 //return *(double*)&v;
         }
GLM_FUNC_DECL uint glm::packHalf2x16 (vec2 const & v)
Returns an unsigned integer obtained by converting the components of a two-component floating-point vector to the 16-bit floating-point representation found in the OpenGL Specification, and then packing these two 16- bit integers into a 32-bit unsigned integer. The first vector component specifies the 16 least-significant bits of the result; the second component specifies the 16 most-significant bits.
See also
GLSL packHalf2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
GLM_FUNC_QUALIFIER detail::uint32 glm::packSnorm2x16 (detail::tvec2< detail::float32 > const & v)
First, converts each component of the normalized floating-point value v into 8- or 16-bit integer values. Then, the results are packed into the returned 32-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packSnorm2x16: round(clamp(v, -1, +1) * 32767.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also
GLSL packSnorm2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 48 of file func_packing.inl.
References glm::A, glm::B, glm::clamp(), glm::round(), glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 union iu
                 {
                         detail::int16 i;
                         detail::uint16 u;
                 } A, B;
                 detail::tvec2<detail::float32> Unpack = clamp(v ,-1.0f, 1.0f) * 32767.0f;
                 A.i = detail::int16(round(Unpack.x));
                 B.i = detail::int16(round(Unpack.y));
                 detail::uint32 Pack = (detail::uint32(B.u) << 16) | (detail::uint32(A.u) << 0);
                 return Pack;
         }
GLM_FUNC_QUALIFIER detail::uint32 glm::packSnorm4x8 (detail::tvec4< detail::float32 > const & v)
First, converts each component of the normalized floating-point value v into 8- or 16-bit integer values. Then, the results are packed into the returned 32-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packSnorm4x8: round(clamp(c, -1, +1) * 127.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also
GLSL packSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 102 of file func_packing.inl.
References glm::A, glm::B, glm::clamp(), glm::round(), glm::detail::tvec4< T >::w, glm::detail::tvec4< T >::x, glm::detail::tvec4< T >::y, and glm::detail::tvec4< T >::z.
         {
                 union iu
                 {
                         detail::int8 i;
                         detail::uint8 u;
                 } A, B, C, D;
                 detail::tvec4<detail::float32> Unpack = clamp(v ,-1.0f, 1.0f) * 127.0f;
                 A.i = detail::int8(round(Unpack.x));
                 B.i = detail::int8(round(Unpack.y));
                 C.i = detail::int8(round(Unpack.z));
                 D.i = detail::int8(round(Unpack.w));
                 detail::uint32 Pack = (detail::uint32(D.u) << 24) | (detail::uint32(C.u) << 16) | (detail::uint32(B.u) << 8) | (detail::uint32(A.u) << 0);
                 return Pack;
         }
GLM_FUNC_QUALIFIER detail::uint32 glm::packUnorm2x16 (detail::tvec2< detail::float32 > const & v)
First, converts each component of the normalized floating-point value v into 8- or 16-bit integer values. Then, the results are packed into the returned 32-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm2x16: round(clamp(c, 0, +1) * 65535.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also
GLSL packUnorm2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 31 of file func_packing.inl.
References glm::A, glm::B, glm::clamp(), glm::round(), glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 detail::uint16 A(detail::uint16(round(clamp(v.x, 0.0f, 1.0f) * 65535.0f)));
                 detail::uint16 B(detail::uint16(round(clamp(v.y, 0.0f, 1.0f) * 65535.0f)));
                 return detail::uint32((B << 16) | A);
         }
GLM_FUNC_QUALIFIER detail::uint32 glm::packUnorm4x8 (detail::tvec4< detail::float32 > const & v)
First, converts each component of the normalized floating-point value v into 8- or 16-bit integer values. Then, the results are packed into the returned 32-bit unsigned integer.
The conversion for component c of v to fixed point is done as follows: packUnorm4x8: round(clamp(c, 0, +1) * 255.0)
The first component of the vector will be written to the least significant bits of the output; the last component will be written to the most significant bits.
See also
GLSL packUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 79 of file func_packing.inl.
References glm::A, glm::B, glm::clamp(), glm::round(), glm::detail::tvec4< T >::w, glm::detail::tvec4< T >::x, glm::detail::tvec4< T >::y, and glm::detail::tvec4< T >::z.
         {
                 detail::uint8 A((detail::uint8)round(clamp(v.x, 0.0f, 1.0f) * 255.0f));
                 detail::uint8 B((detail::uint8)round(clamp(v.y, 0.0f, 1.0f) * 255.0f));
                 detail::uint8 C((detail::uint8)round(clamp(v.z, 0.0f, 1.0f) * 255.0f));
                 detail::uint8 D((detail::uint8)round(clamp(v.w, 0.0f, 1.0f) * 255.0f));
                 return detail::uint32((D << 24) | (C << 16) | (B << 8) | A);
         }
GLM_FUNC_QUALIFIER detail::tvec2< uint > glm::unpackDouble2x32 (double const & v)
Returns a two-component unsigned integer vector representation of v. The bit-level representation of v is preserved. The first component of the vector contains the 32 least significant bits of the double; the second component consists the 32 most significant bits.
See also
GLSL unpackDouble2x32 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 158 of file func_packing.inl.
         {
                 struct uint32_pair
                 {
                         detail::uint32 x;
                         detail::uint32 y;
                 };
                 union helper
                 {
                         double input;
                         uint32_pair output;
                 } Helper;
                 Helper.input = v;
                 return detail::tvec2<uint>(Helper.output.x, Helper.output.y);
         }
GLM_FUNC_QUALIFIER vec2 glm::unpackHalf2x16 (uint const & v)
Returns a two-component floating-point vector with components obtained by unpacking a 32-bit unsigned integer into a pair of 16-bit values, interpreting those values as 16-bit floating-point numbers according to the OpenGL Specification, and converting them to 32-bit floating-point values. The first component of the vector is obtained from the 16 least-significant bits of v; the second component is obtained from the 16 most-significant bits of v.
See also
GLSL unpackHalf2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 193 of file func_packing.inl.
References glm::detail::toFloat32().
         {
                 union helper
                 {
                         uint other;
                         struct
{
                                 detail::hdata a, b;
                         } orig;
                 } Unpack;
                 Unpack.other = v;
                 return vec2(detail::toFloat32(Unpack.orig.a), detail::toFloat32(Unpack.orig.b));
         }
GLM_FUNC_QUALIFIER detail::tvec2< detail::float32 > glm::unpackSnorm2x16 (detail::uint32 const & p)
First, unpacks a single 32-bit unsigned integer p into a pair of 16-bit unsigned integers, four 8-bit unsigned integers, or four 8-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned two- or four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm2x16: clamp(f / 32767.0, -1, +1)
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also
GLSL unpackSnorm2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 63 of file func_packing.inl.
References glm::A, glm::B, and glm::clamp().
         {
                 union iu
                 {
                         detail::int16 i;
                         detail::uint16 u;
                 } A, B;
                 detail::uint32 Mask16((1 << 16) - 1);
                 A.u = detail::uint16((p >>  0) & Mask16);
                 B.u = detail::uint16((p >> 16) & Mask16);
                 detail::tvec2<detail::float32> Pack(A.i, B.i);
                 return clamp(Pack * 1.0f / 32767.0f, -1.0f, 1.0f);
         }
GLM_FUNC_QUALIFIER detail::tvec4< detail::float32 > glm::unpackSnorm4x8 (detail::uint32 const & p)
First, unpacks a single 32-bit unsigned integer p into a pair of 16-bit unsigned integers, four 8-bit unsigned integers, or four 8-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned two- or four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackSnorm4x8: clamp(f / 127.0, -1, +1)
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also
GLSL unpackSnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 119 of file func_packing.inl.
References glm::A, glm::B, and glm::clamp().
         {
                 union iu
                 {
                         detail::int8 i;
                         detail::uint8 u;
                 } A, B, C, D;
                 detail::uint32 Mask8((1 << 8) - 1);
                 A.u = detail::uint8((p >>  0) & Mask8);
                 B.u = detail::uint8((p >>  8) & Mask8);
                 C.u = detail::uint8((p >> 16) & Mask8);
                 D.u = detail::uint8((p >> 24) & Mask8);
                 detail::tvec4<detail::float32> Pack(A.i, B.i, C.i, D.i);
                 return clamp(Pack * 1.0f / 127.0f, -1.0f, 1.0f);
         }
GLM_FUNC_QUALIFIER detail::tvec2< detail::float32 > glm::unpackUnorm2x16 (detail::uint32 const & p)
First, unpacks a single 32-bit unsigned integer p into a pair of 16-bit unsigned integers, four 8-bit unsigned integers, or four 8-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned two- or four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackUnorm2x16: f / 65535.0
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also
GLSL unpackUnorm2x16 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 38 of file func_packing.inl.
References glm::A, and glm::B.
         {
                 detail::uint32 Mask16((1 << 16) - 1);
                 detail::uint32 A((p >>  0) & Mask16);
                 detail::uint32 B((p >> 16) & Mask16);
                 return detail::tvec2<detail::float32>(
                         A * 1.0f / 65535.0f,
                         B * 1.0f / 65535.0f);
         }
GLM_FUNC_QUALIFIER detail::tvec4< detail::float32 > glm::unpackUnorm4x8 (detail::uint32 const & p)
First, unpacks a single 32-bit unsigned integer p into a pair of 16-bit unsigned integers, four 8-bit unsigned integers, or four 8-bit signed integers. Then, each component is converted to a normalized floating-point value to generate the returned two- or four-component vector.
The conversion for unpacked fixed-point value f to floating point is done as follows: unpackUnorm4x8: f / 255.0
The first component of the returned vector will be extracted from the least significant bits of the input; the last component will be extracted from the most significant bits.
See also
GLSL unpackUnorm4x8 man page
GLSL 4.20.8 specification, section 8.4 Floating-Point Pack and Unpack Functions
Definition at line 88 of file func_packing.inl.
References glm::A, and glm::B.
         {
                 detail::uint32 Mask8((1 << 8) - 1);
                 detail::uint32 A((p >>  0) & Mask8);
                 detail::uint32 B((p >>  8) & Mask8);
                 detail::uint32 C((p >> 16) & Mask8);
                 detail::uint32 D((p >> 24) & Mask8);
                 return detail::tvec4<detail::float32>(
                         A * 1.0f / 255.0f,
                         B * 1.0f / 255.0f,
                         C * 1.0f / 255.0f,
                         D * 1.0f / 255.0f);
         }