SDL: glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS > Struct Template Reference
glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS > Struct Template Reference
#include <_swizzle.hpp>
Public Types
typedef VecType vec_type
typedef ValueType value_type
Public Types inherited from glm::detail::_swizzle_base0< ValueType, N >
typedef ValueType value_type
Public Member Functions
_swizzle_base2 & operator= (const ValueType &t)
_swizzle_base2 & operator= (const VecType &that)
void operator-= (const VecType &that)
void operator+= (const VecType &that)
void operator*= (const VecType &that)
void operator/= (const VecType &that)
value_type & operator[] (size_t i)
value_type operator[] (size_t i) const
Protected Member Functions
template<typename T >
void _apply_op (const VecType &that, T op)
Protected Member Functions inherited from glm::detail::_swizzle_base0< ValueType, N >
value_type & elem (size_t i)
const value_type & elem (size_t i) const
Additional Inherited Members
Protected Attributes inherited from glm::detail::_swizzle_base0< ValueType, N >
char _buffer [1]
Detailed Description
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS>
struct glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >
Definition at line 108 of file _swizzle.hpp.
Member Typedef Documentation
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> typedef ValueType glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::value_type
Definition at line 111 of file _swizzle.hpp.
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> typedef VecType glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::vec_type
Definition at line 110 of file _swizzle.hpp.
Member Function Documentation
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> template<typename T > void glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::_apply_op (const VecType & that, T op) inline protected
Definition at line 173 of file _swizzle.hpp.
Referenced by glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator*=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator+=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator-=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator/=(), and glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator=().
                 {
                         // Make a copy of the data in this == &that.
                         // The copier should optimize out the copy in cases where the function is
                         // properly inlined and the copy is not necessary.
                         ValueType t[N];
                         for (int i = 0; i < N; ++i)
                                 t[i] = that[i];
                         for (int i = 0; i < N; ++i)
                                 op( (*this)[i], t[i] );
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> void glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator*= (const VecType & that) inline
Definition at line 145 of file _swizzle.hpp.
                 {
                         struct op {
                                 void operator() (value_type& e, value_type& t) { e *= t; }
                         };
                         _apply_op(that, op());
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> void glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator+= (const VecType & that) inline
Definition at line 137 of file _swizzle.hpp.
                 {
                         struct op {
                                 void operator() (value_type& e, value_type& t) { e += t; }
                         };
                         _apply_op(that, op());
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> void glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator-= (const VecType & that) inline
Definition at line 129 of file _swizzle.hpp.
                 {
                         struct op {
                                 void operator() (value_type& e, value_type& t) { e -= t; }
                         };
                         _apply_op(that, op());
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> void glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator/= (const VecType & that) inline
Definition at line 153 of file _swizzle.hpp.
                 {
                         struct op {
                                 void operator() (value_type& e, value_type& t) { e /= t; }
                         };
                         _apply_op(that, op());
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> _swizzle_base2& glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator= (const ValueType & t) inline
Definition at line 113 of file _swizzle.hpp.
                 {
                         for (int i = 0; i < N; ++i)
                                 (*this)[i] = t;
                         return *this;
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> _swizzle_base2& glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator= (const VecType & that) inline
Definition at line 120 of file _swizzle.hpp.
                 {
                         struct op {
                                 void operator() (value_type& e, value_type& t) { e = t; }
                         };
                         _apply_op(that, op());
                         return *this;
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> value_type& glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator[] (size_t i) inline
Definition at line 161 of file _swizzle.hpp.
                 {
                         static const int offset_dst[4] = { E0, E1, E2, E3 };
                         return this->elem(offset_dst[i]);
                 }
template<typename ValueType, typename VecType, int N, int E0, int E1, int E2, int E3, int DUPLICATE_ELEMENTS> value_type glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >::operator[] (size_t i) const inline
Definition at line 166 of file _swizzle.hpp.
                 {
                         static const int offset_dst[4] = { E0, E1, E2, E3 };
                         return this->elem(offset_dst[i]);
                 }
The documentation for this struct was generated from the following file:
glm/core/_swizzle.hpp