SDL: GLM_GTC_matrix_transform
GLM_GTC_matrix_transform
GTC Extensions (Stable)
Defines functions that generate common transformation matrices.
Functions
template<typename T >
detail::tmat4x4< T > glm::translate (detail::tmat4x4< T > const &m, detail::tvec3< T > const &v)
template<typename T >
detail::tmat4x4< T > glm::rotate (detail::tmat4x4< T > const &m, T const &angle, detail::tvec3< T > const &axis)
template<typename T >
detail::tmat4x4< T > glm::scale (detail::tmat4x4< T > const &m, detail::tvec3< T > const &v)
template<typename T >
detail::tmat4x4< T > glm::ortho (T const &left, T const &right, T const &bottom, T const &top, T const &zNear, T const &zFar)
template<typename T >
detail::tmat4x4< T > glm::ortho (T const &left, T const &right, T const &bottom, T const &top)
template<typename T >
detail::tmat4x4< T > glm::frustum (T const &left, T const &right, T const &bottom, T const &top, T const &near, T const &far)
template<typename T >
detail::tmat4x4< T > glm::perspective (T const &fovy, T const &aspect, T const &near, T const &far)
template<typename valType >
detail::tmat4x4< valType > glm::perspectiveFov (valType const &fov, valType const &width, valType const &height, valType const &near, valType const &far)
template<typename T >
detail::tmat4x4< T > glm::infinitePerspective (T fovy, T aspect, T near)
template<typename T >
detail::tmat4x4< T > glm::tweakedInfinitePerspective (T fovy, T aspect, T near)
template<typename T , typename U >
detail::tvec3< T > glm::project (detail::tvec3< T > const &obj, detail::tmat4x4< T > const &model, detail::tmat4x4< T > const &proj, detail::tvec4< U > const &viewport)
template<typename T , typename U >
detail::tvec3< T > glm::unProject (detail::tvec3< T > const &win, detail::tmat4x4< T > const &model, detail::tmat4x4< T > const &proj, detail::tvec4< U > const &viewport)
template<typename T , typename U >
detail::tmat4x4< T > glm::pickMatrix (detail::tvec2< T > const &center, detail::tvec2< T > const &delta, detail::tvec4< U > const &viewport)
template<typename T >
detail::tmat4x4< T > glm::lookAt (detail::tvec3< T > const &eye, detail::tvec3< T > const &center, detail::tvec3< T > const &up)
Detailed Description
Defines functions that generate common transformation matrices.
The matrices generated by this extension use standard OpenGL fixed-function conventions. For example, the lookAt function generates a transform from world space into the specific eye space that the projective matrix functions (perspective, ortho, etc) are designed to expect. The OpenGL compatibility specifications defines the particular layout of this eye space.
<glm/gtc/matrix_transform.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > detail::tmat4x4<T> glm::frustum (T const & left, T const & right, T const & bottom, T const & top, T const & near, T const & far)
Creates a frustum matrix.
Parameters
left
right
bottom
top
near
far
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
template<typename T > detail::tmat4x4<T> glm::infinitePerspective (T fovy, T aspect, T near)
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite.
Parameters
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
Definition at line 287 of file matrix_transform.inl.
References glm::radians(), glm::T, and glm::tan().
         {
 #ifdef GLM_FORCE_RADIANS
                 T const range = tan(fovy / T(2)) * zNear;
 #else
                 T const range = tan(radians(fovy / T(2))) * zNear;
 #endif
                 T left = -range * aspect;
                 T right = range * aspect;
                 T bottom = -range;
                 T top = range;
                 detail::tmat4x4<T> Result(T(0));
                 Result[0][0] = (T(2) * zNear) / (right - left);
                 Result[1][1] = (T(2) * zNear) / (top - bottom);
                 Result[2][2] = - T(1);
                 Result[2][3] = - T(1);
                 Result[3][2] = - T(2) * zNear;
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::lookAt (detail::tvec3< T > const & eye, detail::tvec3< T > const & center, detail::tvec3< T > const & up)
Build a look at view matrix.
Parameters
eye Position of the camera
center Position where the camera is looking at
up Normalized up vector, how the camera is oriented. Typically (0, 0, 1)
See also
GLM_GTC_matrix_transform
- frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal)
Definition at line 408 of file matrix_transform.inl.
References glm::cross(), glm::dot(), glm::normalize(), glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 detail::tvec3<T> f = normalize(center - eye);
                 detail::tvec3<T> u = normalize(up);
                 detail::tvec3<T> s = normalize(cross(f, u));
                 u = cross(s, f);
                 detail::tmat4x4<T> Result(1);
                 Result[0][0] = s.x;
                 Result[1][0] = s.y;
                 Result[2][0] = s.z;
                 Result[0][1] = u.x;
                 Result[1][1] = u.y;
                 Result[2][1] = u.z;
                 Result[0][2] =-f.x;
                 Result[1][2] =-f.y;
                 Result[2][2] =-f.z;
                 Result[3][0] =-dot(s, eye);
                 Result[3][1] =-dot(u, eye);
                 Result[3][2] = dot(f, eye);
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::ortho (T const & left, T const & right, T const & bottom, T const & top, T const & zNear, T const & zFar)
Creates a matrix for an orthographic parallel viewing volume.
Parameters
left
right
bottom
top
zNear
zFar
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
- glm::ortho(T const & left, T const & right, T const & bottom, T const & top)
template<typename T > detail::tmat4x4<T> glm::ortho (T const & left, T const & right, T const & bottom, T const & top)
Creates a matrix for projecting two-dimensional coordinates onto the screen.
Parameters
left
right
bottom
top
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
- glm::ortho(T const & left, T const & right, T const & bottom, T const & top, T const & zNear, T const & zFar)
template<typename T > detail::tmat4x4<T> glm::perspective (T const & fovy, T const & aspect, T const & near, T const & far)
Creates a matrix for a symetric perspective-view frustum.
Parameters
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
far
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
template<typename valType > detail::tmat4x4<valType> glm::perspectiveFov (valType const & fov, valType const & width, valType const & height, valType const & near, valType const & far)
Builds a perspective projection matrix based on a field of view.
Parameters
fov Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
width
height
near
far
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
todo max(width , Height) / min(width , Height)?
Definition at line 260 of file matrix_transform.inl.
References glm::cos(), glm::radians(), and glm::sin().
         {
 #ifdef GLM_FORCE_RADIANS
                 valType rad = fov;
 #else
                 valType rad = glm::radians(fov);
 #endif
                 valType h = glm::cos(valType(0.5) * rad) / glm::sin(valType(0.5) * rad);
                 valType w = h * height / width; ///todo max(width , Height) / min(width , Height)?
                 detail::tmat4x4<valType> Result(valType(0));
                 Result[0][0] = w;
                 Result[1][1] = h;
                 Result[2][2] = - (zFar + zNear) / (zFar - zNear);
                 Result[2][3] = - valType(1);
                 Result[3][2] = - (valType(2) * zFar * zNear) / (zFar - zNear);
                 return Result;
         }
template<typename T , typename U > detail::tmat4x4< T > glm::pickMatrix (detail::tvec2< T > const & center, detail::tvec2< T > const & delta, detail::tvec4< U > const & viewport)
Define a picking region
Parameters
center
delta
viewport
Template Parameters
T Native type used for the computation. Currently supported: half (not recommanded), float or double.
U Currently supported: Floating-point types and integer types.
See also
GLM_GTC_matrix_transform
Definition at line 384 of file matrix_transform.inl.
References glm::scale(), glm::T, glm::translate(), glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 assert(delta.x > T(0) && delta.y > T(0));
                 detail::tmat4x4<T> Result(1.0f);
                 if(!(delta.x > T(0) && delta.y > T(0)))
                         return Result; // Error
                 detail::tvec3<T> Temp(
                         (T(viewport[2]) - T(2) * (center.x - T(viewport[0]))) / delta.x,
                         (T(viewport[3]) - T(2) * (center.y - T(viewport[1]))) / delta.y,
                         T(0));
                 // Translate and scale the picked region to the entire window
                 Result = translate(Result, Temp);
                 return scale(Result, detail::tvec3<T>(T(viewport[2]) / delta.x, T(viewport[3]) / delta.y, T(1)));
         }
template<typename T , typename U > detail::tvec3<T> glm::project (detail::tvec3< T > const & obj, detail::tmat4x4< T > const & model, detail::tmat4x4< T > const & proj, detail::tvec4< U > const & viewport)
Map the specified object coordinates (obj.x, obj.y, obj.z) into window coordinates.
Parameters
obj
model
proj
viewport
Template Parameters
T Native type used for the computation. Currently supported: half (not recommanded), float or double.
U Currently supported: Floating-point types and integer types.
See also
GLM_GTC_matrix_transform
Definition at line 341 of file matrix_transform.inl.
References glm::T.
         {
                 detail::tvec4<T> tmp = detail::tvec4<T>(obj, T(1));
                 tmp = model * tmp;
                 tmp = proj * tmp;
                 tmp /= tmp.w;
                 tmp = tmp * T(0.5) + T(0.5);
                 tmp[0] = tmp[0] * T(viewport[2]) + T(viewport[0]);
                 tmp[1] = tmp[1] * T(viewport[3]) + T(viewport[1]);
                 return detail::tvec3<T>(tmp);
         }
template<typename T > detail::tmat4x4<T> glm::rotate (detail::tmat4x4< T > const & m, T const & angle, detail::tvec3< T > const & axis)
Builds a rotation 4 * 4 matrix created from an axis vector and an angle.
Parameters
m Input matrix multiplied by this rotation matrix.
angle Rotation angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Rotation axis, recommanded to be normalized.
Template Parameters
T Value type used to build the matrix. Supported: half, float or double.
See also
GLM_GTC_matrix_transform
GLM_GTX_transform
- rotate(T angle, T x, T y, T z)
- rotate(detail::tmat4x4<T> const & m, T angle, T x, T y, T z)
- rotate(T angle, detail::tvec3<T> const & v)
Definition at line 45 of file matrix_transform.inl.
References glm::angle(), glm::axis(), glm::cos(), glm::normalize(), glm::radians(), glm::sin(), and glm::T.
Referenced by glm::orientation(), glm::orientedAngle(), and glm::rotate().
         {
 #ifdef GLM_FORCE_RADIANS
                 T a = angle;
 #else
                 T a = radians(angle);
 #endif
                 T c = cos(a);
                 T s = sin(a);
                 detail::tvec3<T> axis = normalize(v);
                 detail::tvec3<T> temp = (T(1) - c) * axis;
                 detail::tmat4x4<T> Rotate(detail::tmat4x4<T>::null);
                 Rotate[0][0] = c + temp[0] * axis[0];
                 Rotate[0][1] = 0 + temp[0] * axis[1] + s * axis[2];
                 Rotate[0][2] = 0 + temp[0] * axis[2] - s * axis[1];
                 Rotate[1][0] = 0 + temp[1] * axis[0] - s * axis[2];
                 Rotate[1][1] = c + temp[1] * axis[1];
                 Rotate[1][2] = 0 + temp[1] * axis[2] + s * axis[0];
                 Rotate[2][0] = 0 + temp[2] * axis[0] + s * axis[1];
                 Rotate[2][1] = 0 + temp[2] * axis[1] - s * axis[0];
                 Rotate[2][2] = c + temp[2] * axis[2];
                 detail::tmat4x4<T> Result(detail::tmat4x4<T>::null);
                 Result[0] = m[0] * Rotate[0][0] + m[1] * Rotate[0][1] + m[2] * Rotate[0][2];
                 Result[1] = m[0] * Rotate[1][0] + m[1] * Rotate[1][1] + m[2] * Rotate[1][2];
                 Result[2] = m[0] * Rotate[2][0] + m[1] * Rotate[2][1] + m[2] * Rotate[2][2];
                 Result[3] = m[3];
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::scale (detail::tmat4x4< T > const & m, detail::tvec3< T > const & v)
Builds a scale 4 * 4 matrix created from 3 scalars.
Parameters
m Input matrix multiplied by this scale matrix.
v Ratio of scaling for each axis.
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
GLM_GTX_transform
- scale(T x, T y, T z) scale(T const & x, T const & y, T const & z)
- scale(detail::tmat4x4<T> const & m, T x, T y, T z)
- scale(detail::tvec3<T> const & v)
Definition at line 86 of file matrix_transform.inl.
Referenced by glm::pickMatrix(), glm::scale(), and glm::scaleBias().
         {
                 detail::tmat4x4<T> Result(detail::tmat4x4<T>::null);
                 Result[0] = m[0] * v[0];
                 Result[1] = m[1] * v[1];
                 Result[2] = m[2] * v[2];
                 Result[3] = m[3];
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::translate (detail::tmat4x4< T > const & m, detail::tvec3< T > const & v)
Builds a translation 4 * 4 matrix created from a vector of 3 components.
Parameters
m Input matrix multiplied by this translation matrix.
v Coordinates of a translation vector.
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
...
glm::mat4 m = glm::translate(glm::mat4(1.0f), glm::vec3(1.0f));
// m[0][0] == 1.0f, m[0][1] == 0.0f, m[0][2] == 0.0f, m[0][3] == 0.0f
// m[1][0] == 0.0f, m[1][1] == 1.0f, m[1][2] == 0.0f, m[1][3] == 0.0f
// m[2][0] == 0.0f, m[2][1] == 0.0f, m[2][2] == 1.0f, m[2][3] == 0.0f
// m[3][0] == 1.0f, m[3][1] == 1.0f, m[3][2] == 1.0f, m[3][3] == 1.0f
See also
GLM_GTC_matrix_transform
GLM_GTX_transform
- translate(T x, T y, T z)
- translate(detail::tmat4x4<T> const & m, T x, T y, T z)
- translate(detail::tvec3<T> const & v)
Definition at line 33 of file matrix_transform.inl.
Referenced by glm::pickMatrix(), and glm::translate().
         {
                 detail::tmat4x4<T> Result(m);
                 Result[3] = m[0] * v[0] + m[1] * v[1] + m[2] * v[2] + m[3];
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::tweakedInfinitePerspective (T fovy, T aspect, T near)
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping.
Parameters
fovy Expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
aspect
near
Template Parameters
T Value type used to build the matrix. Currently supported: half (not recommanded), float or double.
See also
GLM_GTC_matrix_transform
Definition at line 314 of file matrix_transform.inl.
References glm::radians(), glm::T, and glm::tan().
         {
 #ifdef GLM_FORCE_RADIANS
                 T range = tan(fovy / T(2)) * zNear;
 #else
                 T range = tan(radians(fovy / T(2))) * zNear;
 #endif
                 T left = -range * aspect;
                 T right = range * aspect;
                 T bottom = -range;
                 T top = range;
                 detail::tmat4x4<T> Result(T(0));
                 Result[0][0] = (T(2) * zNear) / (right - left);
                 Result[1][1] = (T(2) * zNear) / (top - bottom);
                 Result[2][2] = T(0.0001) - T(1);
                 Result[2][3] = T(-1);
                 Result[3][2] = - (T(0.0001) - T(2)) * zNear;
                 return Result;
         }
template<typename T , typename U > detail::tvec3<T> glm::unProject (detail::tvec3< T > const & win, detail::tmat4x4< T > const & model, detail::tmat4x4< T > const & proj, detail::tvec4< U > const & viewport)
Map the specified window coordinates (win.x, win.y, win.z) into object coordinates.
Parameters
win
model
proj
viewport
Template Parameters
T Native type used for the computation. Currently supported: half (not recommanded), float or double.
U Currently supported: Floating-point types and integer types.
See also
GLM_GTC_matrix_transform
Definition at line 362 of file matrix_transform.inl.
References glm::inverse(), glm::T, glm::detail::tvec4< T >::w, glm::detail::tvec4< T >::x, and glm::detail::tvec4< T >::y.
         {
                 detail::tmat4x4<T> inverse = glm::inverse(proj * model);
                 detail::tvec4<T> tmp = detail::tvec4<T>(win, T(1));
                 tmp.x = (tmp.x - T(viewport[0])) / T(viewport[2]);
                 tmp.y = (tmp.y - T(viewport[1])) / T(viewport[3]);
                 tmp = tmp * T(2) - T(1);
                 detail::tvec4<T> obj = inverse * tmp;
                 obj /= obj.w;
                 return detail::tvec3<T>(obj);
         }