SDL: GLM_GTC_type_ptr
GLM_GTC_type_ptr
GTC Extensions (Stable)
Handles the interaction between pointers and vector, matrix types.
Functions
template<typename genType >
genType::value_type const * glm::value_ptr (genType const &vec)
template<typename T >
detail::tvec2< T > glm::make_vec2 (T const *const ptr)
template<typename T >
detail::tvec3< T > glm::make_vec3 (T const *const ptr)
template<typename T >
detail::tvec4< T > glm::make_vec4 (T const *const ptr)
template<typename T >
detail::tmat2x2< T > glm::make_mat2x2 (T const *const ptr)
template<typename T >
detail::tmat2x3< T > glm::make_mat2x3 (T const *const ptr)
template<typename T >
detail::tmat2x4< T > glm::make_mat2x4 (T const *const ptr)
template<typename T >
detail::tmat3x2< T > glm::make_mat3x2 (T const *const ptr)
template<typename T >
detail::tmat3x3< T > glm::make_mat3x3 (T const *const ptr)
template<typename T >
detail::tmat3x4< T > glm::make_mat3x4 (T const *const ptr)
template<typename T >
detail::tmat4x2< T > glm::make_mat4x2 (T const *const ptr)
template<typename T >
detail::tmat4x3< T > glm::make_mat4x3 (T const *const ptr)
template<typename T >
detail::tmat4x4< T > glm::make_mat4x4 (T const *const ptr)
template<typename T >
detail::tmat2x2< T > glm::make_mat2 (T const *const ptr)
template<typename T >
detail::tmat3x3< T > glm::make_mat3 (T const *const ptr)
template<typename T >
detail::tmat4x4< T > glm::make_mat4 (T const *const ptr)
template<typename T >
detail::tquat< T > glm::make_quat (T const *const ptr)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tvec2< T > const &vec)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tvec2< T > &vec)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tvec3< T > const &vec)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tvec3< T > &vec)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tvec4< T > const &vec)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tvec4< T > &vec)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat2x2< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat2x2< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat3x3< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat3x3< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat4x4< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat4x4< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat2x3< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat2x3< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat3x2< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat3x2< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat2x4< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat2x4< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat4x2< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat4x2< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat3x4< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat3x4< T > &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tmat4x3< T > const &mat)
template<typename T >
GLM_FUNC_QUALIFIER T const * glm::value_ptr (detail::tquat< T > const &q)
template<typename T >
GLM_FUNC_QUALIFIER T * glm::value_ptr (detail::tmat4x3< T > &mat)
Detailed Description
Handles the interaction between pointers and vector, matrix types.
This extension defines an overloaded function, glm::value_ptr, which takes any of the core template types. It returns a pointer to the memory layout of the object. Matrix types store their values in column-major order.
This is useful for uploading data to matrices or copying data to buffer objects.
Example:
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
glm::vec3 aVector(3);
glm::mat4 someMatrix(1.0);
glUniform3fv(uniformLoc, 1, glm::value_ptr(aVector));
glUniformMatrix4fv(uniformMatrixLoc, 1, GL_FALSE, glm::value_ptr(someMatrix));
<glm/gtc/type_ptr.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > detail::tmat2x2<T> glm::make_mat2 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 429 of file type_ptr.inl.
References glm::make_mat2x2().
         {
                 return make_mat2x2(ptr);
         }
template<typename T > detail::tmat2x2<T> glm::make_mat2x2 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 339 of file type_ptr.inl.
References glm::value_ptr().
Referenced by glm::make_mat2().
         {
                 detail::tmat2x2<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat2x2<T>));
                 return Result;
         }
template<typename T > detail::tmat2x3<T> glm::make_mat2x3 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 349 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tmat2x3<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat2x3<T>));
                 return Result;
         }
template<typename T > detail::tmat2x4<T> glm::make_mat2x4 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 359 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tmat2x4<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat2x4<T>));
                 return Result;
         }
template<typename T > detail::tmat3x3<T> glm::make_mat3 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 437 of file type_ptr.inl.
References glm::make_mat3x3().
         {
                 return make_mat3x3(ptr);
         }
template<typename T > detail::tmat3x2<T> glm::make_mat3x2 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 369 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tmat3x2<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat3x2<T>));
                 return Result;
         }
template<typename T > detail::tmat3x3<T> glm::make_mat3x3 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 379 of file type_ptr.inl.
References glm::value_ptr().
Referenced by glm::make_mat3().
         {
                 detail::tmat3x3<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat3x3<T>));
                 return Result;
         }
template<typename T > detail::tmat3x4<T> glm::make_mat3x4 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 389 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tmat3x4<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat3x4<T>));
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::make_mat4 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 445 of file type_ptr.inl.
References glm::make_mat4x4().
         {
                 return make_mat4x4(ptr);
         }
template<typename T > detail::tmat4x2<T> glm::make_mat4x2 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 399 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tmat4x2<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat4x2<T>));
                 return Result;
         }
template<typename T > detail::tmat4x3<T> glm::make_mat4x3 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 409 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tmat4x3<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat4x3<T>));
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::make_mat4x4 (T const *const ptr)
Build a matrix from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 419 of file type_ptr.inl.
References glm::value_ptr().
Referenced by glm::make_mat4().
         {
                 detail::tmat4x4<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tmat4x4<T>));
                 return Result;
         }
template<typename T > detail::tquat<T> glm::make_quat (T const *const ptr)
Build a quaternion from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 453 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tquat<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tquat<T>));
                 return Result;
         }
template<typename T > detail::tvec2<T> glm::make_vec2 (T const *const ptr)
Build a vector from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 309 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tvec2<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tvec2<T>));
                 return Result;
         }
template<typename T > detail::tvec3<T> glm::make_vec3 (T const *const ptr)
Build a vector from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 319 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tvec3<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tvec3<T>));
                 return Result;
         }
template<typename T > detail::tvec4<T> glm::make_vec4 (T const *const ptr)
Build a vector from a pointer.
See also
GLM_GTC_type_ptr
Definition at line 329 of file type_ptr.inl.
References glm::value_ptr().
         {
                 detail::tvec4<T> Result;
                 memcpy(value_ptr(Result), ptr, sizeof(detail::tvec4<T>));
                 return Result;
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec2< T > const & vec)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 38 of file type_ptr.inl.
References glm::detail::tvec2< T >::x.
         {
                 return &(vec.x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec2< T > & vec)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 49 of file type_ptr.inl.
References glm::detail::tvec2< T >::x.
         {
                 return &(vec.x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec3< T > const & vec)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 60 of file type_ptr.inl.
References glm::detail::tvec3< T >::x.
         {
                 return &(vec.x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec3< T > & vec)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 71 of file type_ptr.inl.
References glm::detail::tvec3< T >::x.
         {
                 return &(vec.x);
         }
template<typename genType > genType::value_type const* glm::value_ptr (genType const & vec)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Referenced by glm::make_mat2x2(), glm::make_mat2x3(), glm::make_mat2x4(), glm::make_mat3x2(), glm::make_mat3x3(), glm::make_mat3x4(), glm::make_mat4x2(), glm::make_mat4x3(), glm::make_mat4x4(), glm::make_quat(), glm::make_vec2(), glm::make_vec3(), and glm::make_vec4().
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tvec4< T > const & vec)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 82 of file type_ptr.inl.
References glm::detail::tvec4< T >::x.
         {
                 return &(vec.x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tvec4< T > & vec)
Return the constant address to the data of the input parameter. From GLM_GTC_type_ptr extension.
Definition at line 93 of file type_ptr.inl.
References glm::detail::tvec4< T >::x.
         {
                 return &(vec.x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x2< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 104 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x2< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 115 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x3< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 126 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x3< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 137 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x4< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 148 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x4< T > & mat)
Return the constant address to the data of the input parameter. From GLM_GTC_type_ptr extension.
Definition at line 159 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x3< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 170 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x3< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 181 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x2< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 192 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x2< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 203 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat2x4< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 214 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat2x4< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 225 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x2< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 236 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x2< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 247 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat3x4< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 258 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat3x4< T > & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 269 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tmat4x3< T > const & mat)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 280 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }
template<typename T > GLM_FUNC_QUALIFIER T const* glm::value_ptr (detail::tquat< T > const & q)
Return the constant address to the data of the input parameter.
See also
GLM_GTC_type_ptr
Definition at line 291 of file type_ptr.inl.
         {
                 return &(q[0]);
         }
template<typename T > GLM_FUNC_QUALIFIER T* glm::value_ptr (detail::tmat4x3< T > & mat)
Get the address of the matrix content.
See also
GLM_GTC_type_ptr
Definition at line 301 of file type_ptr.inl.
         {
                 return &(mat[0].x);
         }