SDL: GLM_GTX_bit
GLM_GTX_bit
GTX Extensions (Experimental)
Allow to perform bit operations on integer values.
Functions
template<typename genIType >
genIType glm::mask (genIType const &count)
template<typename genIUType , typename sizeType >
GLM_DEPRECATED genIUType glm::extractField (genIUType const &v, sizeType const &first, sizeType const &count)
template<typename genType >
GLM_DEPRECATED int glm::lowestBit (genType const &value)
template<typename genType >
GLM_DEPRECATED int glm::highestBit (genType const &value)
template<typename genType >
genType glm::highestBitValue (genType const &value)
template<typename genType >
bool glm::isPowerOfTwo (genType const &value)
template<typename genType >
genType glm::powerOfTwoAbove (genType const &value)
template<typename genType >
genType glm::powerOfTwoBelow (genType const &value)
template<typename genType >
genType glm::powerOfTwoNearest (genType const &value)
template<typename genType >
GLM_DEPRECATED genType glm::bitRevert (genType const &value)
template<typename genType >
genType glm::bitRotateRight (genType const &In, std::size_t Shift)
template<typename genType >
genType glm::bitRotateLeft (genType const &In, std::size_t Shift)
template<typename genIUType >
genIUType glm::fillBitfieldWithOne (genIUType const &Value, int const &FromBit, int const &ToBit)
template<typename genIUType >
genIUType glm::fillBitfieldWithZero (genIUType const &Value, int const &FromBit, int const &ToBit)
Detailed Description
Allow to perform bit operations on integer values.
<glm/gtx/bit.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > GLM_DEPRECATED genType glm::bitRevert (genType const & value)
Revert all bits of any integer based type.
See also
GLM_GTX_bit
Definition at line 457 of file bit.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_integer, "'bitRevert' only accept integer values");
                 genType Out = 0;
                 std::size_t BitSize = sizeof(genType) * 8;
                 for(std::size_t i = 0; i < BitSize; ++i)
                         if(In & (genType(1) << i))
                                 Out |= genType(1) << (BitSize - 1 - i);
                 return Out;
         }
template<typename genType > genType glm::bitRotateLeft (genType const & In, std::size_t Shift)
Rotate all bits to the left.
See also
GLM_GTX_bit
Definition at line 520 of file bit.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::bitRotateLeft().
         {
                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_integer, "'bitRotateLeft' only accept integer values");
                 std::size_t BitSize = sizeof(genType) * 8;
                 return (In >> Shift) | (In << (BitSize - Shift));
         }
template<typename genType > genType glm::bitRotateRight (genType const & In, std::size_t Shift)
Rotate all bits to the right.
See also
GLM_GTX_bit
Definition at line 472 of file bit.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::bitRotateRight().
         {
                 GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_integer, "'bitRotateRight' only accept integer values");
                 std::size_t BitSize = sizeof(genType) * 8;
                 return (In << Shift) | (In >> (BitSize - Shift));
         }
template<typename genIUType , typename sizeType > GLM_DEPRECATED genIUType glm::extractField (genIUType const & v, sizeType const & first, sizeType const & count)
Component wise extraction of bit fields. genType and genIType could be a scalar or a vector.
See also
GLM_GTX_bit
Definition at line 62 of file bit.inl.
Referenced by glm::extractField().
         {
                 sizeType GenSize = sizeof(genIUType) << 3;
                 assert(First + Count <= GenSize);
                 genIUType ShiftLeft = Count ? Value << (GenSize - (Count + First)) : 0;
                 genIUType ShiftBack = ShiftLeft >> genIUType(GenSize - Count);
                 return ShiftBack;
         }
template<typename genIUType > genIUType glm::fillBitfieldWithOne (genIUType const & Value, int const & FromBit, int const & ToBit)
Set to 1 a range of bits.
See also
GLM_GTX_bit
Definition at line 569 of file bit.inl.
         {
                 assert(FromBit <= ToBit);
                 assert(ToBit <= sizeof(genIUType) * std::size_t(8));
                 genIUType Result = Value;
                 for(std::size_t i = 0; i <= ToBit; ++i)
                         Result |= (1 << i);
                 return Result;
         }
template<typename genIUType > genIUType glm::fillBitfieldWithZero (genIUType const & Value, int const & FromBit, int const & ToBit)
Set to 0 a range of bits.
See also
GLM_GTX_bit
Definition at line 586 of file bit.inl.
         {
                 assert(FromBit <= ToBit);
                 assert(ToBit <= sizeof(genIUType) * std::size_t(8));
                 genIUType Result = Value;
                 for(std::size_t i = 0; i <= ToBit; ++i)
                         Result &= ~(1 << i);
                 return Result;
         }
template<typename genType > GLM_DEPRECATED int glm::highestBit (genType const & value)
Find the highest bit set to 1 in a integer variable.
See also
GLM_GTX_bit
Definition at line 257 of file bit.inl.
Referenced by glm::highestBit().
         {
                 assert(value != genType(0)); // not valid call
                 genType bit = genType(-1);
                 for(genType tmp = value; tmp; tmp >>= 1, ++bit){}
                 return bit;
         }
template<typename genType > genType glm::highestBitValue (genType const & value)
Find the highest bit set to 1 in a integer variable and return its value.
See also
GLM_GTX_bit
Definition at line 318 of file bit.inl.
Referenced by glm::highestBitValue(), glm::powerOfTwoAbove(), glm::powerOfTwoBelow(), and glm::powerOfTwoNearest().
         {
                 genType tmp = value;
                 genType result = genType(0);
                 while(tmp)
                 {
                         result = (tmp & (~tmp + 1)); // grab lowest bit
                         tmp &= ~result; // clear lowest bit
                 }
                 return result;
         }
template<typename genType > bool glm::isPowerOfTwo (genType const & value)
Return true if the value is a power of two number.
See also
GLM_GTX_bit
Definition at line 370 of file bit.inl.
References glm::abs().
Referenced by glm::isPowerOfTwo(), glm::powerOfTwoAbove(), glm::powerOfTwoBelow(), and glm::powerOfTwoNearest().
         {
                 //detail::If<std::numeric_limits<genType>::is_signed>::apply(abs, Value);
                 //return !(Value & (Value - 1));
                 // For old complier?
                 genType Result = Value;
                 if(std::numeric_limits<genType>::is_signed)
                         Result = abs(Result);
                 return !(Result & (Result - 1));
         }
template<typename genType > GLM_DEPRECATED int glm::lowestBit (genType const & value)
Find the lowest bit set to 1 in a integer variable.
See also
GLM_GTX_bit
Definition at line 207 of file bit.inl.
Referenced by glm::lowestBit().
         {
                 assert(Value != genType(0)); // not valid call
                 genType Bit;
                 for(Bit = genType(0); !(Value & (1 << Bit)); ++Bit){}
                 return Bit;
         }
template<typename genIType > genIType glm::mask (genIType const & count)
Build a mask of 'count' bits
See also
GLM_GTX_bit
Definition at line 14 of file bit.inl.
         {
                 return ((genIType(1) << (count)) - genIType(1));
         }
template<typename genType > genType glm::powerOfTwoAbove (genType const & value)
Return the power of two number which value is just higher the input value.
See also
GLM_GTX_bit
Definition at line 420 of file bit.inl.
References glm::highestBitValue(), and glm::isPowerOfTwo().
         {
                 return isPowerOfTwo(value) ? value : highestBitValue(value) << 1;
         }
template<typename genType > genType glm::powerOfTwoBelow (genType const & value)
Return the power of two number which value is just lower the input value.
See also
GLM_GTX_bit
Definition at line 430 of file bit.inl.
References glm::highestBitValue(), and glm::isPowerOfTwo().
         {
                 return isPowerOfTwo(value) ? value : highestBitValue(value);
         }
template<typename genType > genType glm::powerOfTwoNearest (genType const & value)
Return the power of two number which value is the closet to the input value.
See also
GLM_GTX_bit
Definition at line 442 of file bit.inl.
References glm::highestBitValue(), and glm::isPowerOfTwo().
         {
                 if(isPowerOfTwo(value))
                         return value;
                 genType prev = highestBitValue(value);
                 genType next = prev << 1;
                 return (next - value) < (value - prev) ? next : prev;
         }