SDL: glm::detail::tmat4x4< T > Struct Template Reference
glm::detail::tmat4x4< T > Struct Template Reference
#include <type_mat2x2.hpp>
Public Types
enum ctor { null }
typedef T value_type
typedef std::size_t size_type
typedef tvec4< T > col_type
typedef tvec4< T > row_type
typedef tmat4x4< T > type
typedef tmat4x4< T > transpose_type
Public Member Functions
GLM_FUNC_DECL GLM_CONSTEXPR
size_type length () const
GLM_FUNC_DECL tmat4x4 ()
GLM_FUNC_DECL tmat4x4 (tmat4x4 const &m)
GLM_FUNC_DECL tmat4x4 (ctor Null)
GLM_FUNC_DECL tmat4x4 (value_type const &x)
GLM_FUNC_DECL tmat4x4 (value_type const &x0, value_type const &y0, value_type const &z0, value_type const &w0, value_type const &x1, value_type const &y1, value_type const &z1, value_type const &w1, value_type const &x2, value_type const &y2, value_type const &z2, value_type const &w2, value_type const &x3, value_type const &y3, value_type const &z3, value_type const &w3)
GLM_FUNC_DECL tmat4x4 (col_type const &v0, col_type const &v1, col_type const &v2, col_type const &v3)
template<typename U >
GLM_FUNC_DECL tmat4x4 (U const &x)
template<typename X1 , typename Y1 , typename Z1 , typename W1 , typename X2 , typename Y2 , typename Z2 , typename W2 , typename X3 , typename Y3 , typename Z3 , typename W3 , typename X4 , typename Y4 , typename Z4 , typename W4 >
GLM_FUNC_DECL tmat4x4 (X1 const &x1, Y1 const &y1, Z1 const &z1, W1 const &w1, X2 const &x2, Y2 const &y2, Z2 const &z2, W2 const &w2, X3 const &x3, Y3 const &y3, Z3 const &z3, W3 const &w3, X4 const &x4, Y4 const &y4, Z4 const &z4, W4 const &w4)
template<typename V1 , typename V2 , typename V3 , typename V4 >
GLM_FUNC_DECL tmat4x4 (tvec4< V1 > const &v1, tvec4< V2 > const &v2, tvec4< V3 > const &v3, tvec4< V4 > const &v4)
template<typename U >
GLM_FUNC_DECL tmat4x4 (tmat4x4< U > const &m)
GLM_FUNC_DECL tmat4x4 (tmat2x2< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat3x3< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat2x3< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat3x2< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat2x4< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat4x2< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat3x4< T > const &x)
GLM_FUNC_DECL tmat4x4 (tmat4x3< T > const &x)
GLM_FUNC_DECL col_type & operator[] (size_type i)
GLM_FUNC_DECL col_type const & operator[] (size_type i) const
GLM_FUNC_DECL tmat4x4< T > & operator= (tmat4x4< T > const &m)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator+= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator+= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator-= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator-= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator*= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator*= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator/= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat4x4< T > & operator/= (tmat4x4< U > const &m)
GLM_FUNC_DECL tmat4x4< T > & operator++ ()
GLM_FUNC_DECL tmat4x4< T > & operator-- ()
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4 (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator+= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator+= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator-= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator-= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator*= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator*= (tmat4x4< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator/= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat4x4< T > & operator/= (tmat4x4< U > const &m)
Static Public Member Functions
static GLM_FUNC_DECL size_type col_size ()
static GLM_FUNC_DECL size_type row_size ()
Private Attributes
col_type value [4]
Detailed Description
template<typename T>
struct glm::detail::tmat4x4< T >
Definition at line 49 of file type_mat2x2.hpp.
Member Typedef Documentation
template<typename T> typedef tvec4<T> glm::detail::tmat4x4< T >::col_type
Definition at line 57 of file type_mat4x4.hpp.
template<typename T> typedef tvec4<T> glm::detail::tmat4x4< T >::row_type
Definition at line 58 of file type_mat4x4.hpp.
template<typename T> typedef std::size_t glm::detail::tmat4x4< T >::size_type
Definition at line 56 of file type_mat4x4.hpp.
template<typename T> typedef tmat4x4<T> glm::detail::tmat4x4< T >::transpose_type
Definition at line 60 of file type_mat4x4.hpp.
template<typename T> typedef tmat4x4<T> glm::detail::tmat4x4< T >::type
Definition at line 59 of file type_mat4x4.hpp.
template<typename T> typedef T glm::detail::tmat4x4< T >::value_type
Definition at line 55 of file type_mat4x4.hpp.
Member Enumeration Documentation
template<typename T> enum glm::detail::tmat4x4::ctor
Enumerator
null
Definition at line 54 of file type_mat4x4.hpp.
 {null};
Constructor & Destructor Documentation
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 ()
Definition at line 79 of file type_mat4x4.inl.
         {
                 value_type Zero(0);
                 value_type One(1);
                 this->value[0] = col_type(One, Zero, Zero, Zero);
                 this->value[1] = col_type(Zero, One, Zero, Zero);
                 this->value[2] = col_type(Zero, Zero, One, Zero);
                 this->value[3] = col_type(Zero, Zero, Zero, One);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat4x4< T > const & m)
Definition at line 91 of file type_mat4x4.inl.
References glm::detail::tmat4x4< T >::value.
         {
                 this->value[0] = m.value[0];
                 this->value[1] = m.value[1];
                 this->value[2] = m.value[2];
                 this->value[3] = m.value[3];
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (ctor Null) explicit
Definition at line 103 of file type_mat4x4.inl.
         {}
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (value_type const & x) explicit
Definition at line 110 of file type_mat4x4.inl.
         {
                 value_type const Zero(0);
                 this->value[0] = col_type(s, Zero, Zero, Zero);
                 this->value[1] = col_type(Zero, s, Zero, Zero);
                 this->value[2] = col_type(Zero, Zero, s, Zero);
                 this->value[3] = col_type(Zero, Zero, Zero, s);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (value_type const & x0, value_type const & y0, value_type const & z0, value_type const & w0, value_type const & x1, value_type const & y1, value_type const & z1, value_type const & w1, value_type const & x2, value_type const & y2, value_type const & z2, value_type const & w2, value_type const & x3, value_type const & y3, value_type const & z3, value_type const & w3) explicit
Definition at line 123 of file type_mat4x4.inl.
         {
                 this->value[0] = col_type(x0, y0, z0, w0);
                 this->value[1] = col_type(x1, y1, z1, w1);
                 this->value[2] = col_type(x2, y2, z2, w2);
                 this->value[3] = col_type(x3, y3, z3, w3);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (col_type const & v0, col_type const & v1, col_type const & v2, col_type const & v3) explicit
Definition at line 138 of file type_mat4x4.inl.
         {
                 this->value[0] = v0;
                 this->value[1] = v1;
                 this->value[2] = v2;
                 this->value[3] = v3;
         }
template<typename T > template<typename U > GLM_FUNC_DECL glm::detail::tmat4x4< T >::tmat4x4 (U const & x) explicit
Definition at line 169 of file type_mat4x4.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<U>::is_float || std::numeric_limits<U>::is_integer, "*mat4x4 constructor only takes float and integer types");
                 value_type const Zero(0);
                 this->value[0] = tvec4<T>(value_type(s), Zero, Zero, Zero);
                 this->value[1] = tvec4<T>(Zero, value_type(s), Zero, Zero);
                 this->value[2] = tvec4<T>(Zero, Zero, value_type(s), Zero);
                 this->value[3] = tvec4<T>(Zero, Zero, Zero, value_type(s));
         }
template<typename T > template<typename X1 , typename Y1 , typename Z1 , typename W1 , typename X2 , typename Y2 , typename Z2 , typename W2 , typename X3 , typename Y3 , typename Z3 , typename W3 , typename X4 , typename Y4 , typename Z4 , typename W4 > GLM_FUNC_DECL glm::detail::tmat4x4< T >::tmat4x4 (X1 const & x1, Y1 const & y1, Z1 const & z1, W1 const & w1, X2 const & x2, Y2 const & y2, Z2 const & z2, W2 const & w2, X3 const & x3, Y3 const & y3, Z3 const & z3, W3 const & w3, X4 const & x4, Y4 const & y4, Z4 const & z4, W4 const & w4) explicit
Definition at line 189 of file type_mat4x4.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<X1>::is_float || std::numeric_limits<X1>::is_integer, "*mat4x4 constructor only takes float and integer types, 1st parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Y1>::is_float || std::numeric_limits<Y1>::is_integer, "*mat4x4 constructor only takes float and integer types, 2nd parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Z1>::is_float || std::numeric_limits<Z1>::is_integer, "*mat4x4 constructor only takes float and integer types, 3rd parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<W1>::is_float || std::numeric_limits<W1>::is_integer, "*mat4x4 constructor only takes float and integer types, 4th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<X2>::is_float || std::numeric_limits<X2>::is_integer, "*mat4x4 constructor only takes float and integer types, 5th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Y2>::is_float || std::numeric_limits<Y2>::is_integer, "*mat4x4 constructor only takes float and integer types, 6th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Z2>::is_float || std::numeric_limits<Z2>::is_integer, "*mat4x4 constructor only takes float and integer types, 7th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<W2>::is_float || std::numeric_limits<W2>::is_integer, "*mat4x4 constructor only takes float and integer types, 8th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<X3>::is_float || std::numeric_limits<X3>::is_integer, "*mat4x4 constructor only takes float and integer types, 9th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Y3>::is_float || std::numeric_limits<Y3>::is_integer, "*mat4x4 constructor only takes float and integer types, 10th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Z3>::is_float || std::numeric_limits<Z3>::is_integer, "*mat4x4 constructor only takes float and integer types, 11th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<W3>::is_float || std::numeric_limits<W3>::is_integer, "*mat4x4 constructor only takes float and integer types, 12th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<X4>::is_float || std::numeric_limits<X4>::is_integer, "*mat4x4 constructor only takes float and integer types, 13th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Y4>::is_float || std::numeric_limits<Y4>::is_integer, "*mat4x4 constructor only takes float and integer types, 14th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<Z4>::is_float || std::numeric_limits<Z4>::is_integer, "*mat4x4 constructor only takes float and integer types, 15th parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<W4>::is_float || std::numeric_limits<W4>::is_integer, "*mat4x4 constructor only takes float and integer types, 16th parameter type invalid.");
                 this->value[0] = col_type(value_type(x1), value_type(y1), value_type(z1), value_type(w1));
                 this->value[1] = col_type(value_type(x2), value_type(y2), value_type(z2), value_type(w2));
                 this->value[2] = col_type(value_type(x3), value_type(y3), value_type(z3), value_type(w3));
                 this->value[3] = col_type(value_type(x4), value_type(y4), value_type(z4), value_type(w4));
         }
template<typename T > template<typename V1 , typename V2 , typename V3 , typename V4 > GLM_FUNC_DECL glm::detail::tmat4x4< T >::tmat4x4 (tvec4< V1 > const & v1, tvec4< V2 > const & v2, tvec4< V3 > const & v3, tvec4< V4 > const & v4) explicit
Definition at line 225 of file type_mat4x4.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<V1>::is_float || std::numeric_limits<V1>::is_integer, "*mat4x4 constructor only takes float and integer types, 1st parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<V2>::is_float || std::numeric_limits<V2>::is_integer, "*mat4x4 constructor only takes float and integer types, 2nd parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<V3>::is_float || std::numeric_limits<V3>::is_integer, "*mat4x4 constructor only takes float and integer types, 3rd parameter type invalid.");
                 GLM_STATIC_ASSERT(detail::type<V4>::is_float || std::numeric_limits<V4>::is_integer, "*mat4x4 constructor only takes float and integer types, 4th parameter type invalid.");
                 this->value[0] = col_type(v1);
                 this->value[1] = col_type(v2);
                 this->value[2] = col_type(v3);
                 this->value[3] = col_type(v4);
         }
template<typename T> template<typename U > GLM_FUNC_DECL glm::detail::tmat4x4< T >::tmat4x4 (tmat4x4< U > const & m) explicit
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat2x2< T > const & x) explicit
Definition at line 247 of file type_mat4x4.inl.
         {
                 this->value[0] = col_type(m[0], detail::tvec2<T>(0));
                 this->value[1] = col_type(m[1], detail::tvec2<T>(0));
                 this->value[2] = col_type(value_type(0));
                 this->value[3] = col_type(value_type(0), value_type(0), value_type(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat3x3< T > const & x) explicit
Definition at line 259 of file type_mat4x4.inl.
         {
                 this->value[0] = col_type(m[0], value_type(0));
                 this->value[1] = col_type(m[1], value_type(0));
                 this->value[2] = col_type(m[2], value_type(0));
                 this->value[3] = col_type(value_type(0), value_type(0), value_type(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat2x3< T > const & x) explicit
Definition at line 271 of file type_mat4x4.inl.
         {
                 this->value[0] = col_type(m[0], value_type(0));
                 this->value[1] = col_type(m[1], value_type(0));
                 this->value[2] = col_type(value_type(0));
                 this->value[3] = col_type(value_type(0), value_type(0), value_type(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat3x2< T > const & x) explicit
Definition at line 283 of file type_mat4x4.inl.
         {
                 this->value[0] = col_type(m[0], detail::tvec2<T>(0));
                 this->value[1] = col_type(m[1], detail::tvec2<T>(0));
                 this->value[2] = col_type(m[2], detail::tvec2<T>(0));
                 this->value[3] = col_type(value_type(0), value_type(0), value_type(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat2x4< T > const & x) explicit
Definition at line 295 of file type_mat4x4.inl.
References glm::T.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = col_type(T(0));
                 this->value[3] = col_type(T(0), T(0), T(0), T(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat4x2< T > const & x) explicit
Definition at line 307 of file type_mat4x4.inl.
References glm::T.
         {
                 this->value[0] = col_type(m[0], detail::tvec2<T>(0));
                 this->value[1] = col_type(m[1], detail::tvec2<T>(0));
                 this->value[2] = col_type(T(0));
                 this->value[3] = col_type(T(0), T(0), T(0), T(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat3x4< T > const & x) explicit
Definition at line 319 of file type_mat4x4.inl.
References glm::T.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = m[2];
                 this->value[3] = col_type(T(0), T(0), T(0), T(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat4x3< T > const & x) explicit
Definition at line 331 of file type_mat4x4.inl.
References glm::T.
         {
                 this->value[0] = col_type(m[0], T(0));
                 this->value[1] = col_type(m[1], T(0));
                 this->value[2] = col_type(m[2], T(0));
                 this->value[3] = col_type(m[3], T(1));
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER glm::detail::tmat4x4< T >::tmat4x4 (tmat4x4< U > const & m)
Definition at line 154 of file type_mat4x4.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
                 this->value[2] = col_type(m[2]);
                 this->value[3] = col_type(m[3]);
         }
Member Function Documentation
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T >::size_type glm::detail::tmat4x4< T >::col_size () static
Definition at line 39 of file type_mat4x4.inl.
         {
                 return 4;
         }
template<typename T > GLM_FUNC_QUALIFIER GLM_CONSTEXPR tmat4x4< T >::size_type glm::detail::tmat4x4< T >::length () const
Definition at line 33 of file type_mat4x4.inl.
Referenced by glm::isNormalized(), and glm::outerProduct().
         {
                 return 4;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator*= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator*= (tmat4x4< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator*= (U const & s)
Definition at line 434 of file type_mat4x4.inl.
         {
                 this->value[0] *= s;
                 this->value[1] *= s;
                 this->value[2] *= s;
                 this->value[3] *= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator*= (tmat4x4< U > const & m)
Definition at line 448 of file type_mat4x4.inl.
         {
                 return (*this = *this * m);
         }
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T > & glm::detail::tmat4x4< T >::operator++ ()
Definition at line 480 of file type_mat4x4.inl.
         {
                 ++this->value[0];
                 ++this->value[1];
                 ++this->value[2];
                 ++this->value[3];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator+= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator+= (tmat4x4< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator+= (U const & s)
Definition at line 378 of file type_mat4x4.inl.
         {
                 this->value[0] += s;
                 this->value[1] += s;
                 this->value[2] += s;
                 this->value[3] += s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator+= (tmat4x4< U > const & m)
Definition at line 392 of file type_mat4x4.inl.
         {
                 this->value[0] += m[0];
                 this->value[1] += m[1];
                 this->value[2] += m[2];
                 this->value[3] += m[3];
                 return *this;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T > & glm::detail::tmat4x4< T >::operator-- ()
Definition at line 490 of file type_mat4x4.inl.
         {
                 --this->value[0];
                 --this->value[1];
                 --this->value[2];
                 --this->value[3];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator-= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator-= (tmat4x4< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator-= (U const & s)
Definition at line 406 of file type_mat4x4.inl.
         {
                 this->value[0] -= s;
                 this->value[1] -= s;
                 this->value[2] -= s;
                 this->value[3] -= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator-= (tmat4x4< U > const & m)
Definition at line 420 of file type_mat4x4.inl.
         {
                 this->value[0] -= m[0];
                 this->value[1] -= m[1];
                 this->value[2] -= m[2];
                 this->value[3] -= m[3];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator/= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator/= (tmat4x4< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator/= (U const & s)
Definition at line 458 of file type_mat4x4.inl.
         {
                 this->value[0] /= s;
                 this->value[1] /= s;
                 this->value[2] /= s;
                 this->value[3] /= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator/= (tmat4x4< U > const & m)
Definition at line 472 of file type_mat4x4.inl.
         {
                 return (*this = *this / m);
         }
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T > & glm::detail::tmat4x4< T >::operator= (tmat4x4< T > const & m)
Definition at line 346 of file type_mat4x4.inl.
         {
                 //memcpy could be faster
                 //memcpy(&this->value, &m.value, 16 * sizeof(valType));
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = m[2];
                 this->value[3] = m[3];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat4x4<T>& glm::detail::tmat4x4< T >::operator= (tmat4x4< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat4x4<T>& glm::detail::tmat4x4< T >::operator= (tmat4x4< U > const & m)
Definition at line 362 of file type_mat4x4.inl.
         {
                 //memcpy could be faster
                 //memcpy(&this->value, &m.value, 16 * sizeof(valType));
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = m[2];
                 this->value[3] = m[3];
                 return *this;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T >::col_type & glm::detail::tmat4x4< T >::operator[] (size_type i)
Definition at line 56 of file type_mat4x4.inl.
References glm::length().
         {
                 assert(i < this->length());
                 return this->value[i];
         }
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T >::col_type const & glm::detail::tmat4x4< T >::operator[] (size_type i) const
Definition at line 67 of file type_mat4x4.inl.
References glm::length().
         {
                 assert(i < this->length());
                 return this->value[i];
         }
template<typename T > GLM_FUNC_QUALIFIER tmat4x4< T >::size_type glm::detail::tmat4x4< T >::row_size () static
Definition at line 45 of file type_mat4x4.inl.
         {
                 return 4;
         }
Field Documentation
template<typename T> col_type glm::detail::tmat4x4< T >::value[4] private
Implementation detail
Definition at line 75 of file type_mat4x4.hpp.
Referenced by glm::detail::tmat4x4< T >::tmat4x4().
The documentation for this struct was generated from the following files:
glm/core/type_mat2x2.hpp
glm/core/type_mat4x4.hpp
glm/core/type_mat4x4.inl