var hierarchy =
[
    [ "glm::_detail::_compute_log2< _PATH >", "da/d75/structglm_1_1__detail_1_1__compute__log2.html", null ],
    [ "glm::_detail::_compute_log2< detail::float_or_int_value::GLM_FLOAT >", "df/df7/structglm_1_1__detail_1_1__compute__log2_3_01detail_1_1float__or__int__value_1_1_g_l_m___f_l_o_a_t_01_4.html", null ],
    [ "glm::_detail::_compute_log2< detail::float_or_int_value::GLM_INT >", "db/d8e/structglm_1_1__detail_1_1__compute__log2_3_01detail_1_1float__or__int__value_1_1_g_l_m___i_n_t_01_4.html", null ],
    [ "glm::detail::_swizzle_base0< T, N >", "df/de0/structglm_1_1detail_1_1__swizzle__base0.html", [
      [ "glm::detail::_swizzle_base1< T, V, E0, E1, E2, E3, N >", "d7/d42/structglm_1_1detail_1_1__swizzle__base1.html", null ]
    ] ],
    [ "glm::detail::_swizzle_base0< T, 2 >", "df/de0/structglm_1_1detail_1_1__swizzle__base0.html", [
      [ "glm::detail::_swizzle_base1< T, V, E0, E1,-1,-2, 2 >", "d6/dbc/structglm_1_1detail_1_1__swizzle__base1_3_01_t_00_01_v_00_01_e0_00_01_e1_00-1_00-2_00_012_01_4.html", null ]
    ] ],
    [ "glm::detail::_swizzle_base0< T, 3 >", "df/de0/structglm_1_1detail_1_1__swizzle__base0.html", [
      [ "glm::detail::_swizzle_base1< T, V, E0, E1, E2,-1, 3 >", "db/dfa/structglm_1_1detail_1_1__swizzle__base1_3_01_t_00_01_v_00_01_e0_00_01_e1_00_01_e2_00-1_00_013_01_4.html", null ]
    ] ],
    [ "glm::detail::_swizzle_base0< T, 4 >", "df/de0/structglm_1_1detail_1_1__swizzle__base0.html", [
      [ "glm::detail::_swizzle_base1< T, V, E0, E1, E2, E3, 4 >", "d9/d92/structglm_1_1detail_1_1__swizzle__base1_3_01_t_00_01_v_00_01_e0_00_01_e1_00_01_e2_00_01_e3_00_014_01_4.html", null ]
    ] ],
    [ "glm::detail::_swizzle_base0< ValueType, N >", "df/de0/structglm_1_1detail_1_1__swizzle__base0.html", [
      [ "glm::detail::_swizzle_base1< ValueType, VecType, E0, E1, E2, E3, N >", "d7/d42/structglm_1_1detail_1_1__swizzle__base1.html", [
        [ "glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>", "dd/d3d/structglm_1_1detail_1_1__swizzle__base2.html", [
          [ "glm::detail::swizzle< N, ValueType, VecType, E0, E1, E2, E3 >", "d3/de9/structglm_1_1detail_1_1swizzle.html", null ]
        ] ],
        [ "glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >", "dd/d3d/structglm_1_1detail_1_1__swizzle__base2.html", null ],
        [ "glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, 1 >", "d1/ddf/structglm_1_1detail_1_1__swizzle__base2_3_01_value_type_00_01_vec_type_00_01_n_00_01_e0_00_01_e1_00_01_e2_00_01_e3_00_011_01_4.html", null ]
      ] ]
    ] ],
    [ "glm::detail::Abs_< genFIType, bool >", "df/d17/structglm_1_1detail_1_1_abs__.html", null ],
    [ "glm::detail::Abs_< genFIType, false >", "df/d7a/structglm_1_1detail_1_1_abs___3_01gen_f_i_type_00_01false_01_4.html", null ],
    [ "glm::detail::Abs_< genFIType, true >", "dd/d87/structglm_1_1detail_1_1_abs___3_01gen_f_i_type_00_01true_01_4.html", null ],
    [ "gdl::AShader", "de/df0/classgdl_1_1_a_shader.html", [
      [ "gdl::BasicShader", "dc/d4b/classgdl_1_1_basic_shader.html", null ]
    ] ],
    [ "gdl::Attribute", "db/dde/structgdl_1_1_attribute.html", null ],
    [ "gdl::Clock", "d0/d90/classgdl_1_1_clock.html", null ],
    [ "MaterialCache::ColorChannel", "d7/d1a/struct_material_cache_1_1_color_channel.html", null ],
    [ "glm::detail::compute_linearRand", "d5/d62/structglm_1_1detail_1_1compute__linear_rand.html", null ],
    [ "glm::dont_care", "db/dfa/classglm_1_1dont__care.html", null ],
    [ "glm::fastest", "d8/d57/classglm_1_1fastest.html", null ],
    [ "glm::detail::float_or_int_trait< T >", "d7/d7a/structglm_1_1detail_1_1float__or__int__trait.html", null ],
    [ "glm::detail::float_or_int_trait< float16 >", "dc/d6a/structglm_1_1detail_1_1float__or__int__trait_3_01float16_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< float32 >", "d7/d81/structglm_1_1detail_1_1float__or__int__trait_3_01float32_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< float64 >", "d7/dc9/structglm_1_1detail_1_1float__or__int__trait_3_01float64_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< int16 >", "dc/d4c/structglm_1_1detail_1_1float__or__int__trait_3_01int16_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< int32 >", "d1/deb/structglm_1_1detail_1_1float__or__int__trait_3_01int32_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< int64 >", "d5/dd5/structglm_1_1detail_1_1float__or__int__trait_3_01int64_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< int8 >", "d8/dc4/structglm_1_1detail_1_1float__or__int__trait_3_01int8_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< uint16 >", "df/dcf/structglm_1_1detail_1_1float__or__int__trait_3_01uint16_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< uint32 >", "da/dc0/structglm_1_1detail_1_1float__or__int__trait_3_01uint32_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< uint64 >", "d9/dfe/structglm_1_1detail_1_1float__or__int__trait_3_01uint64_01_4.html", null ],
    [ "glm::detail::float_or_int_trait< uint8 >", "d2/dbb/structglm_1_1detail_1_1float__or__int__trait_3_01uint8_01_4.html", null ],
    [ "glm::detail::float_or_int_value", "da/da2/structglm_1_1detail_1_1float__or__int__value.html", null ],
    [ "gdl::Game", "da/da8/classgdl_1_1_game.html", null ],
    [ "glm::detail::genType< VALTYPE, TYPE >", "d1/dcf/structglm_1_1detail_1_1gen_type.html", null ],
    [ "gdl::Geometry", "dc/d47/classgdl_1_1_geometry.html", null ],
    [ "GLXBufferClobberEventSGIX", "da/d11/struct_g_l_x_buffer_clobber_event_s_g_i_x.html", null ],
    [ "GLXEvent", "d2/ddc/union_g_l_x_event.html", null ],
    [ "GLXHyperpipeConfigSGIX", "d4/df9/struct_g_l_x_hyperpipe_config_s_g_i_x.html", null ],
    [ "GLXHyperpipeNetworkSGIX", "d7/d72/struct_g_l_x_hyperpipe_network_s_g_i_x.html", null ],
    [ "GLXPbufferClobberEvent", "d5/d06/struct_g_l_x_pbuffer_clobber_event.html", null ],
    [ "GLXPipeRect", "dc/d27/struct_g_l_x_pipe_rect.html", null ],
    [ "GLXPipeRectLimits", "d2/d04/struct_g_l_x_pipe_rect_limits.html", null ],
    [ "glm::detail::half", "d8/d7f/classglm_1_1detail_1_1half.html", null ],
    [ "glm::detail::ieee754_QNAN::i", "d0/df3/structglm_1_1detail_1_1ieee754___q_n_a_n_1_1i.html", null ],
    [ "glm::detail::ieee754_QNAN", "d7/d92/unionglm_1_1detail_1_1ieee754___q_n_a_n.html", null ],
    [ "ieee_double_shape_type", "dd/d7f/unionieee__double__shape__type.html", null ],
    [ "ieee_float_shape_type", "d0/d20/unionieee__float__shape__type.html", null ],
    [ "glm::detail::If< C >", "d2/d66/structglm_1_1detail_1_1_if.html", null ],
    [ "glm::detail::If< false >", "d8/dcd/structglm_1_1detail_1_1_if_3_01false_01_4.html", null ],
    [ "gdl::Input", "d8/dc9/classgdl_1_1_input.html", null ],
    [ "gdl::IRenderContext", "de/d83/classgdl_1_1_i_render_context.html", [
      [ "gdl::SdlContext", "d9/d69/classgdl_1_1_sdl_context.html", null ]
    ] ],
    [ "glm::detail::is_bool< T >", "de/dc6/structglm_1_1detail_1_1is__bool.html", null ],
    [ "glm::detail::is_bool< bool >", "d5/d48/structglm_1_1detail_1_1is__bool_3_01bool_01_4.html", null ],
    [ "glm::detail::is_float< T >", "dd/d77/structglm_1_1detail_1_1is__float.html", null ],
    [ "glm::detail::is_int< T >", "d7/d21/structglm_1_1detail_1_1is__int.html", null ],
    [ "glm::detail::is_matrix< T >", "dd/d0e/structglm_1_1detail_1_1is__matrix.html", null ],
    [ "glm::detail::is_uint< T >", "d2/d65/structglm_1_1detail_1_1is__uint.html", null ],
    [ "glm::detail::is_vector< T >", "d4/d5b/structglm_1_1detail_1_1is__vector.html", null ],
    [ "glm::detail::mask< Value >", "db/db9/structglm_1_1detail_1_1mask.html", null ],
    [ "MaterialCache", "d9/d5a/class_material_cache.html", null ],
    [ "gdl::Model", "d6/de8/classgdl_1_1_model.html", null ],
    [ "glm::nicest", "db/dad/classglm_1_1nicest.html", null ],
    [ "PGPU_DEVICE", "d5/d42/struct_g_p_u___d_e_v_i_c_e.html", null ],
    [ "PGPU_DEVICE", "db/d70/struct___g_p_u___d_e_v_i_c_e.html", null ],
    [ "PropertyChannel", "dc/d2c/struct_property_channel.html", null ],
    [ "SDL_assert_data", "dc/df2/struct_s_d_l__assert__data.html", null ],
    [ "SDL_atomic_t", "de/d13/struct_s_d_l__atomic__t.html", null ],
    [ "SDL_AudioCVT", "d1/d4b/struct_s_d_l___audio_c_v_t.html", null ],
    [ "SDL_AudioSpec", "d1/d75/struct_s_d_l___audio_spec.html", null ],
    [ "SDL_Color", "d5/dcc/struct_s_d_l___color.html", null ],
    [ "SDL_CommonEvent", "dd/d06/struct_s_d_l___common_event.html", null ],
    [ "SDL_ControllerAxisEvent", "da/d9e/struct_s_d_l___controller_axis_event.html", null ],
    [ "SDL_ControllerButtonEvent", "d9/d15/struct_s_d_l___controller_button_event.html", null ],
    [ "SDL_ControllerDeviceEvent", "da/d81/struct_s_d_l___controller_device_event.html", null ],
    [ "SDL_DisplayMode", "d1/d16/struct_s_d_l___display_mode.html", null ],
    [ "SDL_DollarGestureEvent", "d7/dec/struct_s_d_l___dollar_gesture_event.html", null ],
    [ "SDL_DropEvent", "df/d97/struct_s_d_l___drop_event.html", null ],
    [ "SDL_Event", "df/d1f/union_s_d_l___event.html", null ],
    [ "SDL_Finger", "da/db6/struct_s_d_l___finger.html", null ],
    [ "SDL_GameControllerButtonBind", "dd/dc4/struct_s_d_l___game_controller_button_bind.html", null ],
    [ "SDL_HapticCondition", "d1/d00/struct_s_d_l___haptic_condition.html", null ],
    [ "SDL_HapticConstant", "d7/d4d/struct_s_d_l___haptic_constant.html", null ],
    [ "SDL_HapticCustom", "de/d46/struct_s_d_l___haptic_custom.html", null ],
    [ "SDL_HapticDirection", "dc/dc3/struct_s_d_l___haptic_direction.html", null ],
    [ "SDL_HapticEffect", "d4/d80/union_s_d_l___haptic_effect.html", null ],
    [ "SDL_HapticLeftRight", "d3/d93/struct_s_d_l___haptic_left_right.html", null ],
    [ "SDL_HapticPeriodic", "d1/d6b/struct_s_d_l___haptic_periodic.html", null ],
    [ "SDL_HapticRamp", "d2/df5/struct_s_d_l___haptic_ramp.html", null ],
    [ "SDL_JoyAxisEvent", "d3/d15/struct_s_d_l___joy_axis_event.html", null ],
    [ "SDL_JoyBallEvent", "df/d8b/struct_s_d_l___joy_ball_event.html", null ],
    [ "SDL_JoyButtonEvent", "d7/de3/struct_s_d_l___joy_button_event.html", null ],
    [ "SDL_JoyDeviceEvent", "d7/d5b/struct_s_d_l___joy_device_event.html", null ],
    [ "SDL_JoyHatEvent", "d8/d59/struct_s_d_l___joy_hat_event.html", null ],
    [ "SDL_JoystickGUID", "d5/d5c/struct_s_d_l___joystick_g_u_i_d.html", null ],
    [ "SDL_KeyboardEvent", "d8/db8/struct_s_d_l___keyboard_event.html", null ],
    [ "SDL_Keysym", "d4/de7/struct_s_d_l___keysym.html", null ],
    [ "SDL_MessageBoxButtonData", "d5/d6d/struct_s_d_l___message_box_button_data.html", null ],
    [ "SDL_MessageBoxColor", "d0/d93/struct_s_d_l___message_box_color.html", null ],
    [ "SDL_MessageBoxColorScheme", "db/d58/struct_s_d_l___message_box_color_scheme.html", null ],
    [ "SDL_MessageBoxData", "d0/d2c/struct_s_d_l___message_box_data.html", null ],
    [ "SDL_MouseButtonEvent", "d9/d8f/struct_s_d_l___mouse_button_event.html", null ],
    [ "SDL_MouseMotionEvent", "d2/d18/struct_s_d_l___mouse_motion_event.html", null ],
    [ "SDL_MouseWheelEvent", "d8/d9b/struct_s_d_l___mouse_wheel_event.html", null ],
    [ "SDL_MultiGestureEvent", "d7/d64/struct_s_d_l___multi_gesture_event.html", null ],
    [ "SDL_OSEvent", "d6/d78/struct_s_d_l___o_s_event.html", null ],
    [ "SDL_Palette", "de/d4f/struct_s_d_l___palette.html", null ],
    [ "SDL_PixelFormat", "de/d29/struct_s_d_l___pixel_format.html", null ],
    [ "SDL_Point", "dd/d4e/struct_s_d_l___point.html", null ],
    [ "SDL_QuitEvent", "d6/d71/struct_s_d_l___quit_event.html", null ],
    [ "SDL_Rect", "d4/dda/struct_s_d_l___rect.html", null ],
    [ "SDL_RendererInfo", "d8/d04/struct_s_d_l___renderer_info.html", null ],
    [ "SDL_RWops", "d2/d3b/struct_s_d_l___r_wops.html", null ],
    [ "SDL_Surface", "d6/d0f/struct_s_d_l___surface.html", null ],
    [ "SDL_SysWMEvent", "d8/d14/struct_s_d_l___sys_w_m_event.html", null ],
    [ "SDL_SysWMinfo", "d1/d59/struct_s_d_l___sys_w_minfo.html", null ],
    [ "SDL_SysWMmsg", "de/deb/struct_s_d_l___sys_w_mmsg.html", null ],
    [ "SDL_TextEditingEvent", "d9/d58/struct_s_d_l___text_editing_event.html", null ],
    [ "SDL_TextInputEvent", "d8/d47/struct_s_d_l___text_input_event.html", null ],
    [ "SDL_TouchFingerEvent", "d8/d17/struct_s_d_l___touch_finger_event.html", null ],
    [ "SDL_UserEvent", "d7/d78/struct_s_d_l___user_event.html", null ],
    [ "SDL_version", "d9/d84/struct_s_d_l__version.html", null ],
    [ "SDL_WindowEvent", "d1/d00/struct_s_d_l___window_event.html", null ],
    [ "SDL_WindowShapeMode", "dd/da3/struct_s_d_l___window_shape_mode.html", null ],
    [ "SDL_WindowShapeParams", "d3/d93/union_s_d_l___window_shape_params.html", null ],
    [ "SDLTest_CommonState", "d8/d8d/struct_s_d_l_test___common_state.html", null ],
    [ "SDLTest_Crc32Context", "d2/d0b/struct_s_d_l_test___crc32_context.html", null ],
    [ "SDLTest_Md5Context", "d4/d44/struct_s_d_l_test___md5_context.html", null ],
    [ "SDLTest_RandomContext", "d8/d07/struct_s_d_l_test___random_context.html", null ],
    [ "SDLTest_SurfaceImage_t", "d7/d0e/struct_s_d_l_test___surface_image__t.html", null ],
    [ "SDLTest_TestCaseReference", "d2/dd7/struct_s_d_l_test___test_case_reference.html", null ],
    [ "SDLTest_TestSuiteReference", "d2/d34/struct_s_d_l_test___test_suite_reference.html", null ],
    [ "glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, 1 >::Stub", "d2/dba/structglm_1_1detail_1_1__swizzle__base2_3_01_value_type_00_01_vec_type_00_01_n_00_01_e0_00_01_e1d74529ea3036199f62a3c164ac7e92d9.html", null ],
    [ "VBOMesh::SubMesh", "d5/d40/struct_v_b_o_mesh_1_1_sub_mesh.html", null ],
    [ "gdl::Texture", "d8/d0b/classgdl_1_1_texture.html", null ],
    [ "glm::detail::tmat2x2< T >", "db/dec/structglm_1_1detail_1_1tmat2x2.html", null ],
    [ "glm::detail::tmat2x3< T >", "d0/d33/structglm_1_1detail_1_1tmat2x3.html", null ],
    [ "glm::detail::tmat2x4< T >", "de/d02/structglm_1_1detail_1_1tmat2x4.html", null ],
    [ "glm::detail::tmat3x2< T >", "dc/d43/structglm_1_1detail_1_1tmat3x2.html", null ],
    [ "glm::detail::tmat3x3< T >", "d4/d28/structglm_1_1detail_1_1tmat3x3.html", null ],
    [ "glm::detail::tmat3x4< T >", "d1/d7e/structglm_1_1detail_1_1tmat3x4.html", null ],
    [ "glm::detail::tmat4x2< T >", "dd/d4e/structglm_1_1detail_1_1tmat4x2.html", null ],
    [ "glm::detail::tmat4x3< T >", "d9/d5a/structglm_1_1detail_1_1tmat4x3.html", null ],
    [ "glm::detail::tmat4x4< T >", "d6/d53/structglm_1_1detail_1_1tmat4x4.html", null ],
    [ "glm::detail::tquat< T >", "db/de1/structglm_1_1detail_1_1tquat.html", null ],
    [ "glm::detail::tref1< T >", "d9/d33/structglm_1_1detail_1_1tref1.html", null ],
    [ "glm::detail::tref2< T >", "d5/d23/structglm_1_1detail_1_1tref2.html", null ],
    [ "glm::detail::tref3< T >", "da/d52/structglm_1_1detail_1_1tref3.html", null ],
    [ "glm::detail::tref4< T >", "d8/d93/structglm_1_1detail_1_1tref4.html", null ],
    [ "glm::detail::tvec1< T >", "d7/deb/structglm_1_1detail_1_1tvec1.html", null ],
    [ "glm::detail::tvec2< T >", "d2/d16/structglm_1_1detail_1_1tvec2.html", null ],
    [ "glm::detail::tvec3< T >", "dc/d7d/structglm_1_1detail_1_1tvec3.html", null ],
    [ "glm::detail::tvec4< T >", "d3/db5/structglm_1_1detail_1_1tvec4.html", null ],
    [ "glm::detail::type< T >", "d2/d55/structglm_1_1detail_1_1type.html", null ],
    [ "glm::detail::uif32", "da/d29/unionglm_1_1detail_1_1uif32.html", null ],
    [ "glm::detail::uif64", "d8/d6a/unionglm_1_1detail_1_1uif64.html", null ],
    [ "VBOMesh", "d1/dbf/class_v_b_o_mesh.html", null ]
];