SDL: glm::detail::_swizzle_base0< T, N > Struct Template Reference
glm::detail::_swizzle_base0< T, N > Struct Template Reference
#include <_swizzle.hpp>
Public Types
typedef T value_type
Protected Member Functions
value_type & elem (size_t i)
const value_type & elem (size_t i) const
Protected Attributes
char _buffer [1]
Detailed Description
template<typename T, int N>
struct glm::detail::_swizzle_base0< T, N >
Definition at line 58 of file _swizzle.hpp.
Member Typedef Documentation
template<typename T, int N> typedef T glm::detail::_swizzle_base0< T, N >::value_type
Definition at line 60 of file _swizzle.hpp.
Member Function Documentation
template<typename T, int N> value_type& glm::detail::_swizzle_base0< T, N >::elem (size_t i) inline protected
Definition at line 63 of file _swizzle.hpp.
Referenced by glm::detail::_swizzle_base1< T, V, E0, E1,-1,-2, 2 >::operator()(), glm::detail::_swizzle_base1< T, V, E0, E1, E2,-1, 3 >::operator()(), and glm::detail::_swizzle_base1< T, V, E0, E1, E2, E3, 4 >::operator()().
 { return (reinterpret_cast<value_type*>(_buffer))[i]; }
template<typename T, int N> const value_type& glm::detail::_swizzle_base0< T, N >::elem (size_t i) const inline protected
Definition at line 64 of file _swizzle.hpp.
 { return (reinterpret_cast<const value_type*>(_buffer))[i]; }
Field Documentation
template<typename T, int N> char glm::detail::_swizzle_base0< T, N >::_buffer[1] protected
Definition at line 69 of file _swizzle.hpp.
Referenced by glm::detail::_swizzle_base0< T, 4 >::elem().
The documentation for this struct was generated from the following file:
glm/core/_swizzle.hpp