SDL: Angle and Trigonometry Functions
Angle and Trigonometry Functions
GLM Core
Functions
template<typename genType >
GLM_FUNC_DECL genType glm::radians (genType const &degrees)
template<typename genType >
GLM_FUNC_DECL genType glm::degrees (genType const &radians)
template<typename genType >
GLM_FUNC_DECL genType glm::sin (genType const &angle)
template<typename genType >
GLM_FUNC_DECL genType glm::cos (genType const &angle)
template<typename genType >
GLM_FUNC_DECL genType glm::tan (genType const &angle)
template<typename genType >
GLM_FUNC_DECL genType glm::asin (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::acos (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::atan (genType const &y, genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::atan (genType const &y_over_x)
template<typename genType >
GLM_FUNC_DECL genType glm::sinh (genType const &angle)
template<typename genType >
GLM_FUNC_DECL genType glm::cosh (genType const &angle)
template<typename genType >
GLM_FUNC_DECL genType glm::tanh (genType const &angle)
template<typename genType >
GLM_FUNC_DECL genType glm::asinh (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::acosh (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::atanh (genType const &x)
Detailed Description
Function parameters specified as angle are assumed to be in units of radians. In no case will any of these functions result in a divide by zero error. If the divisor of a ratio is 0, then results will be undefined.
These all operate component-wise. The description is per component.
Function Documentation
template<typename genType > GLM_FUNC_DECL genType glm::acos (genType const & x)
Arc cosine. Returns an angle whose sine is x. The range of values returned by this function is [0, PI]. Results are undefined if |x| > 1.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL acos man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 117 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::angle(), glm::asec(), glm::axisAngle(), glm::mix(), glm::orientation(), glm::orientedAngle(), glm::pow(), and glm::slerp().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'acos' only accept floating-point input");
                 return genType(::std::acos(x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::acosh (genType const & x)
Arc hyperbolic cosine; returns the non-negative inverse of cosh. Results are undefined if x < 1.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL acosh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 215 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT, glm::log(), and glm::sqrt().
Referenced by glm::asech().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'acosh' only accept floating-point input");
                 if(x < genType(1))
                         return genType(0);
                 return log(x + sqrt(x * x - genType(1)));
         }
template<typename genType > GLM_FUNC_DECL genType glm::asin (genType const & x)
Arc sine. Returns an angle whose sine is x. The range of values returned by this function is [-PI/2, PI/2]. Results are undefined if |x| > 1.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL asin man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 103 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::acsc(), and glm::yaw().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'asin' only accept floating-point input");
                 return genType(::std::asin(x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::asinh (genType const & x)
Arc hyperbolic sine; returns the inverse of sinh.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL asinh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 201 of file func_trigonometric.inl.
References glm::abs(), GLM_STATIC_ASSERT, glm::log(), and glm::sqrt().
Referenced by glm::acsch().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'asinh' only accept floating-point input");
                 return (x < genType(0) ? genType(-1) : (x > genType(0) ? genType(1) : genType(0))) * log(abs(x) + sqrt(genType(1) + x * x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::atan (genType const & y, genType const & x)
Arc tangent. Returns an angle whose tangent is y/x. The signs of x and y are used to determine what quadrant the angle is in. The range of values returned by this function is [-PI, PI]. Results are undefined if x and y are both 0.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL atan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 131 of file func_trigonometric.inl.
References glm::atan2(), and GLM_STATIC_ASSERT.
Referenced by glm::acot(), glm::atan2(), glm::log(), glm::pitch(), glm::polar(), glm::roll(), and glm::shortMix().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'atan' only accept floating-point input");
                 return genType(::std::atan2(y, x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::atan (genType const & y_over_x)
Arc tangent. Returns an angle whose tangent is y_over_x. The range of values returned by this function is [-PI/2, PI/2].
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL atan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 145 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'atan' only accept floating-point input");
                 return genType(::std::atan(x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::atanh (genType const & x)
Arc hyperbolic tangent; returns the inverse of tanh. Results are undefined if abs(x) >= 1.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL atanh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 231 of file func_trigonometric.inl.
References glm::abs(), GLM_STATIC_ASSERT, and glm::log().
Referenced by glm::acoth().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'atanh' only accept floating-point input");
                 if(abs(x) >= genType(1))
                         return 0;
                 return genType(0.5) * log((genType(1) + x) / (genType(1) - x));
         }
template<typename genType > GLM_FUNC_DECL genType glm::cos (genType const & angle)
The standard trigonometric cosine function. The values returned by this function will range from [-1, 1].
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL cos man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 77 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::angleAxis(), glm::axisAngleMatrix(), glm::circularRand(), glm::euclidean(), glm::eulerAngleX(), glm::eulerAngleXY(), glm::eulerAngleY(), glm::eulerAngleYX(), glm::eulerAngleYXZ(), glm::eulerAngleZ(), glm::exp(), glm::orientate2(), glm::orientate3(), glm::perspectiveFov(), glm::pow(), glm::rotate(), glm::rotate_slow(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), glm::sec(), glm::sphericalRand(), glm::detail::tquat< T >::tquat(), and glm::yawPitchRoll().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'cos' only accept floating-point input");
                 return genType(::std::cos(angle));
         }
template<typename genType > GLM_FUNC_DECL genType glm::cosh (genType const & angle)
Returns the hyperbolic cosine function, (exp(x) + exp(-x)) / 2
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL cosh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 173 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::coth(), and glm::sech().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'cosh' only accept floating-point input");
                 return genType(std::cosh(angle));
         }
template<typename genType > GLM_FUNC_DECL genType glm::degrees (genType const & radians)
Converts radians to degrees and returns the result.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL degrees man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 49 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT, and glm::pi().
Referenced by glm::angle(), glm::orientation(), glm::orientedAngle(), glm::pitch(), glm::polar(), glm::roll(), and glm::yaw().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'degrees' only accept floating-point input");
                 const genType pi = genType(3.1415926535897932384626433832795);
                 return radians * (genType(180) / pi);
         }
template<typename genType > GLM_FUNC_DECL genType glm::radians (genType const & degrees)
Converts degrees to radians and returns the result.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL radians man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 34 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT, and glm::pi().
Referenced by glm::angleAxis(), glm::euclidean(), glm::infinitePerspective(), glm::perspective(), glm::perspectiveFov(), glm::rotate(), glm::rotate_slow(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), and glm::tweakedInfinitePerspective().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'radians' only accept floating-point input");
                 genType const pi = genType(3.1415926535897932384626433832795);
                 return degrees * (pi / genType(180));
         }
template<typename genType > GLM_FUNC_DECL genType glm::sin (genType const & angle)
The standard trigonometric sine function. The values returned by this function will range from [-1, 1].
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL sin man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 64 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::angleAxis(), glm::axisAngleMatrix(), glm::circularRand(), glm::csc(), glm::euclidean(), glm::eulerAngleX(), glm::eulerAngleXY(), glm::eulerAngleY(), glm::eulerAngleYX(), glm::eulerAngleYXZ(), glm::eulerAngleZ(), glm::exp(), glm::mix(), glm::orientate2(), glm::orientate3(), glm::perspectiveFov(), glm::pow(), glm::rotate(), glm::rotate_slow(), glm::rotateX(), glm::rotateY(), glm::rotateZ(), glm::shortMix(), glm::slerp(), glm::sphericalRand(), glm::detail::tquat< T >::tquat(), and glm::yawPitchRoll().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'sin' only accept floating-point input");
                 return genType(::std::sin(angle));
         }
template<typename genType > GLM_FUNC_DECL genType glm::sinh (genType const & angle)
Returns the hyperbolic sine function, (exp(x) - exp(-x)) / 2
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL sinh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 159 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::coth(), and glm::csch().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'sinh' only accept floating-point input");
                 return genType(std::sinh(angle));
         }
template<typename genType > GLM_FUNC_DECL genType glm::tan (genType const & angle)
The standard trigonometric tangent function.
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL tan man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 89 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::cot(), glm::infinitePerspective(), glm::perspective(), and glm::tweakedInfinitePerspective().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'tan' only accept floating-point input");
                 return genType(::std::tan(angle));
         }
template<typename genType > GLM_FUNC_DECL genType glm::tanh (genType const & angle)
Returns the hyperbolic tangent function, sinh(angle) / cosh(angle)
Template Parameters
genType Floating-point scalar or vector types.
See also
GLSL tanh man page
GLSL 4.20.8 specification, section 8.1 Angle and Trigonometry Functions
Definition at line 187 of file func_trigonometric.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'tanh' only accept floating-point input");
                 return genType(std::tanh(angle));
         }