SDL: GLM_GTC_constants
GLM_GTC_constants
GTC Extensions (Stable)
Allow to perform bit operations on integer values.
Functions
template<typename genType >
GLM_FUNC_DECL genType glm::epsilon ()
template<typename genType >
GLM_FUNC_DECL genType glm::zero ()
template<typename genType >
GLM_FUNC_DECL genType glm::one ()
template<typename genType >
GLM_FUNC_DECL genType glm::pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::half_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::quarter_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::one_over_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::two_over_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::two_over_root_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::one_over_root_two ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_half_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_two_pi ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_ln_four ()
template<typename genType >
GLM_FUNC_DECL genType glm::e ()
template<typename genType >
GLM_FUNC_DECL genType glm::euler ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_two ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_three ()
template<typename genType >
GLM_FUNC_DECL genType glm::root_five ()
template<typename genType >
GLM_FUNC_DECL genType glm::ln_two ()
template<typename genType >
GLM_FUNC_DECL genType glm::ln_ten ()
template<typename genType >
GLM_FUNC_DECL genType glm::ln_ln_two ()
template<typename genType >
GLM_FUNC_DECL genType glm::third ()
template<typename genType >
GLM_FUNC_DECL genType glm::two_thirds ()
template<typename genType >
GLM_FUNC_DECL genType glm::golden_ratio ()
Detailed Description
Allow to perform bit operations on integer values.
<glm/gtc/constants.hpp> need to be included to use these features.
Function Documentation
template<typename genType > GLM_FUNC_DECL genType glm::e ()
Return e constant.
See also
GLM_GTC_constants
Definition at line 122 of file constants.inl.
Referenced by glm::epsilon(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator*=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator+=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator-=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator/=(), glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3,(E0==E1||E0==E2||E0==E3||E1==E2||E1==E3||E2==E3)>::operator=(), glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 return genType(2.71828182845904523536);
         }
template<typename genType > GLM_FUNC_DECL genType glm::epsilon ()
Return the epsilon constant for floating point types.
Todo:
Implement epsilon for half-precision floating point type.
See also
GLM_GTC_constants
Definition at line 32 of file constants.inl.
References glm::e(), and glm::epsilon().
Referenced by glm::areCollinear(), glm::areOrthogonal(), glm::areOrthonormal(), glm::axisAngle(), glm::epsilon(), glm::epsilonEqual(), glm::epsilonNotEqual(), glm::intersectLineSphere(), glm::intersectLineTriangle(), glm::intersectRaySphere(), glm::intersectRayTriangle(), glm::isCompNull(), glm::isIdentity(), glm::isNormalized(), and glm::isNull().
         {
                 return std::numeric_limits<genType>::epsilon();
         }
template<typename genType > GLM_FUNC_DECL genType glm::euler ()
Return Euler's constant.
See also
GLM_GTC_constants
Definition at line 128 of file constants.inl.
         {
                 return genType(0.577215664901532860606);
         }
template<typename genType > GLM_FUNC_DECL genType glm::golden_ratio ()
Return the golden ratio constant.
See also
GLM_GTC_constants
Definition at line 182 of file constants.inl.
         {
                 return genType(1.61803398874989484820458683436563811);
         }
template<typename genType > GLM_FUNC_DECL genType glm::half_pi ()
Return pi / 2.
See also
GLM_GTC_constants
Definition at line 68 of file constants.inl.
         {
                 return genType(1.57079632679489661923132169163975144);
         }
template<typename genType > GLM_FUNC_DECL genType glm::ln_ln_two ()
Return ln(ln(2)).
See also
GLM_GTC_constants
Definition at line 164 of file constants.inl.
         {
                 return genType(-0.3665129205816643);
         }
template<typename genType > GLM_FUNC_DECL genType glm::ln_ten ()
Return ln(10).
See also
GLM_GTC_constants
Definition at line 158 of file constants.inl.
         {
                 return genType(2.30258509299404568401799145468436421);
         }
template<typename genType > GLM_FUNC_DECL genType glm::ln_two ()
Return ln(2).
See also
GLM_GTC_constants
Definition at line 152 of file constants.inl.
         {
                 return genType(0.693147180559945309417232121458176568);
         }
template<typename genType > GLM_FUNC_DECL genType glm::one ()
Return 1.
See also
GLM_GTC_constants
Definition at line 50 of file constants.inl.
         {
                 return genType(1);
         }
template<typename genType > GLM_FUNC_DECL genType glm::one_over_pi ()
Return 1 / pi.
See also
GLM_GTC_constants
Definition at line 80 of file constants.inl.
         {
                 return genType(0.318309886183790671537767526745028724);
         }
template<typename genType > GLM_FUNC_DECL genType glm::one_over_root_two ()
Return 1 / sqrt(2).
See also
GLM_GTC_constants
Definition at line 98 of file constants.inl.
         {
                 return genType(0.707106781186547524400844362104849039);
         }
template<typename genType > GLM_FUNC_DECL genType glm::pi ()
Return the pi constant.
See also
GLM_GTC_constants
Definition at line 56 of file constants.inl.
Referenced by glm::degrees(), and glm::radians().
         {
                 return genType(3.14159265358979323846264338327950288);
         }
template<typename genType > GLM_FUNC_DECL genType glm::quarter_pi ()
Return pi / 4.
See also
GLM_GTC_constants
Definition at line 74 of file constants.inl.
         {
                 return genType(0.785398163397448309615660845819875721);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_five ()
Return sqrt(5).
See also
GLM_GTC_constants
Definition at line 146 of file constants.inl.
         {
                 return genType(2.23606797749978969640917366873127623);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_half_pi ()
Return sqrt(pi / 2).
See also
GLM_GTC_constants
Definition at line 104 of file constants.inl.
         {
                 return genType(1.253314137315500251);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_ln_four ()
Return sqrt(ln(4)).
See also
GLM_GTC_constants
Definition at line 116 of file constants.inl.
         {
                 return genType(1.17741002251547469);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_pi ()
Return square root of pi.
See also
GLM_GTC_constants
Definition at line 62 of file constants.inl.
         {
                 return genType(1.772453850905516027);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_three ()
Return sqrt(3).
See also
GLM_GTC_constants
Definition at line 140 of file constants.inl.
         {
                 return genType(1.73205080756887729352744634150587236);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_two ()
Return sqrt(2).
See also
GLM_GTC_constants
Definition at line 134 of file constants.inl.
         {
                 return genType(1.41421356237309504880168872420969808);
         }
template<typename genType > GLM_FUNC_DECL genType glm::root_two_pi ()
Return sqrt(2 * pi).
See also
GLM_GTC_constants
Definition at line 110 of file constants.inl.
         {
                 return genType(2.506628274631000502);
         }
template<typename genType > GLM_FUNC_DECL genType glm::third ()
Return 1 / 3.
See also
GLM_GTC_constants
Definition at line 170 of file constants.inl.
         {
                 return genType(0.3333333333333333333333333333333333333333);
         }
template<typename genType > GLM_FUNC_DECL genType glm::two_over_pi ()
Return 2 / pi.
See also
GLM_GTC_constants
Definition at line 86 of file constants.inl.
         {
                 return genType(0.636619772367581343075535053490057448);
         }
template<typename genType > GLM_FUNC_DECL genType glm::two_over_root_pi ()
Return 2 / sqrt(pi).
See also
GLM_GTC_constants
Definition at line 92 of file constants.inl.
         {
                 return genType(1.12837916709551257389615890312154517);
         }
template<typename genType > GLM_FUNC_DECL genType glm::two_thirds ()
Return 2 / 3.
See also
GLM_GTC_constants
Definition at line 176 of file constants.inl.
         {
                 return genType(0.666666666666666666666666666666666666667);
         }
template<typename genType > GLM_FUNC_DECL genType glm::zero ()
Return 0.
See also
GLM_GTC_constants
Definition at line 44 of file constants.inl.
         {
                 return genType(0);
         }