SDL: GLM_GTX_fast_exponential
GLM_GTX_fast_exponential
GTX Extensions (Experimental)
Fast but less accurate implementations of exponential based functions.
Functions
template<typename genType >
genType glm::fastPow (genType const &x, genType const &y)
template<typename genTypeT , typename genTypeU >
genTypeT glm::fastPow (genTypeT const &x, genTypeU const &y)
template<typename T >
T glm::fastExp (const T &x)
template<typename T >
T glm::fastLog (const T &x)
template<typename T >
T glm::fastExp2 (const T &x)
template<typename T >
T glm::fastLog2 (const T &x)
template<typename T >
T glm::fastLn (const T &x)
Detailed Description
Fast but less accurate implementations of exponential based functions.
<glm/gtx/fast_exponential.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > T glm::fastExp (const T & x)
Faster than the common exp function but less accurate.
See also
GLM_GTX_fast_exponential
Referenced by glm::fastExp2().
template<typename T > T glm::fastExp2 (const T & x)
Faster than the common exp2 function but less accurate.
See also
GLM_GTX_fast_exponential
template<typename T > T glm::fastLn (const T & x)
Faster than the common ln function but less accurate.
See also
GLM_GTX_fast_exponential
template<typename T > T glm::fastLog (const T & x)
Faster than the common log function but less accurate.
See also
GLM_GTX_fast_exponential
Referenced by glm::fastLog2().
template<typename T > T glm::fastLog2 (const T & x)
Faster than the common log2 function but less accurate.
See also
GLM_GTX_fast_exponential
template<typename genType > genType glm::fastPow (genType const & x, genType const & y)
Faster than the common pow function but less accurate.
See also
GLM_GTX_fast_exponential
Definition at line 14 of file fast_exponential.inl.
References glm::exp(), and glm::log().
Referenced by glm::fastPow().
         {
                 return exp(y * log(x));
         }
template<typename genTypeT , typename genTypeU > genTypeT glm::fastPow (genTypeT const & x, genTypeU const & y)
Faster than the common pow function but less accurate.
See also
GLM_GTX_fast_exponential