SDL: glm::detail::tmat2x2< T > Struct Template Reference
glm::detail::tmat2x2< T > Struct Template Reference
#include <type_mat2x2.hpp>
Public Types
enum ctor { null }
typedef T value_type
typedef std::size_t size_type
typedef tvec2< T > col_type
typedef tvec2< T > row_type
typedef tmat2x2< T > type
typedef tmat2x2< T > transpose_type
Public Member Functions
GLM_FUNC_DECL GLM_CONSTEXPR
size_type length () const
GLM_FUNC_DECL tmat2x2< T > _inverse () const
GLM_FUNC_DECL tmat2x2 ()
GLM_FUNC_DECL tmat2x2 (tmat2x2 const &m)
GLM_FUNC_DECL tmat2x2 (ctor Null)
GLM_FUNC_DECL tmat2x2 (value_type const &x)
GLM_FUNC_DECL tmat2x2 (value_type const &x1, value_type const &y1, value_type const &x2, value_type const &y2)
GLM_FUNC_DECL tmat2x2 (col_type const &v1, col_type const &v2)
template<typename U >
GLM_FUNC_DECL tmat2x2 (U const &x)
template<typename U , typename V , typename M , typename N >
GLM_FUNC_DECL tmat2x2 (U const &x1, V const &y1, M const &x2, N const &y2)
template<typename U , typename V >
GLM_FUNC_DECL tmat2x2 (tvec2< U > const &v1, tvec2< V > const &v2)
template<typename U >
GLM_FUNC_DECL tmat2x2 (tmat2x2< U > const &m)
GLM_FUNC_DECL tmat2x2 (tmat3x3< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat4x4< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat2x3< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat3x2< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat2x4< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat4x2< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat3x4< T > const &x)
GLM_FUNC_DECL tmat2x2 (tmat4x3< T > const &x)
GLM_FUNC_DECL col_type & operator[] (size_type i)
GLM_FUNC_DECL col_type const & operator[] (size_type i) const
GLM_FUNC_DECL tmat2x2< T > & operator= (tmat2x2< T > const &m)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator+= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator+= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator-= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator-= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator*= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator*= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator/= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat2x2< T > & operator/= (tmat2x2< U > const &m)
GLM_FUNC_DECL tmat2x2< T > & operator++ ()
GLM_FUNC_DECL tmat2x2< T > & operator-- ()
template<typename X1 , typename Y1 , typename X2 , typename Y2 >
GLM_FUNC_DECL tmat2x2 (X1 const &x1, Y1 const &y1, X2 const &x2, Y2 const &y2)
template<typename V1 , typename V2 >
GLM_FUNC_DECL tmat2x2 (tvec2< V1 > const &v1, tvec2< V2 > const &v2)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2 (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator+= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator+= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator-= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator-= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator*= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator*= (tmat2x2< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator/= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat2x2< T > & operator/= (tmat2x2< U > const &m)
Static Public Member Functions
static GLM_FUNC_DECL size_type col_size ()
static GLM_FUNC_DECL size_type row_size ()
Private Attributes
col_type value [2]
Detailed Description
template<typename T>
struct glm::detail::tmat2x2< T >
Definition at line 41 of file type_mat2x2.hpp.
Member Typedef Documentation
template<typename T> typedef tvec2<T> glm::detail::tmat2x2< T >::col_type
Definition at line 58 of file type_mat2x2.hpp.
template<typename T> typedef tvec2<T> glm::detail::tmat2x2< T >::row_type
Definition at line 59 of file type_mat2x2.hpp.
template<typename T> typedef std::size_t glm::detail::tmat2x2< T >::size_type
Definition at line 57 of file type_mat2x2.hpp.
template<typename T> typedef tmat2x2<T> glm::detail::tmat2x2< T >::transpose_type
Definition at line 61 of file type_mat2x2.hpp.
template<typename T> typedef tmat2x2<T> glm::detail::tmat2x2< T >::type
Definition at line 60 of file type_mat2x2.hpp.
template<typename T> typedef T glm::detail::tmat2x2< T >::value_type
Definition at line 56 of file type_mat2x2.hpp.
Member Enumeration Documentation
template<typename T> enum glm::detail::tmat2x2::ctor
Enumerator
null
Definition at line 55 of file type_mat2x2.hpp.
 {null};
Constructor & Destructor Documentation
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 ()
Definition at line 79 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(1, 0);
                 this->value[1] = col_type(0, 1);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat2x2< T > const & m)
Definition at line 87 of file type_mat2x2.inl.
References glm::detail::tmat2x2< T >::value.
         {
                 this->value[0] = m.value[0];
                 this->value[1] = m.value[1];
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (ctor Null) explicit
Definition at line 97 of file type_mat2x2.inl.
         {}
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (value_type const & x) explicit
Definition at line 104 of file type_mat2x2.inl.
         {
                 value_type const Zero(0);
                 this->value[0] = col_type(s, Zero);
                 this->value[1] = col_type(Zero, s);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (value_type const & x1, value_type const & y1, value_type const & x2, value_type const & y2) explicit
Definition at line 115 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(x0, y0);
                 this->value[1] = col_type(x1, y1);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (col_type const & v1, col_type const & v2) explicit
Definition at line 126 of file type_mat2x2.inl.
         {
                 this->value[0] = v0;
                 this->value[1] = v1;
         }
template<typename T > template<typename U > GLM_FUNC_DECL glm::detail::tmat2x2< T >::tmat2x2 (U const & x) explicit
Definition at line 140 of file type_mat2x2.inl.
         {
                 value_type const Zero(0);
                 this->value[0] = tvec2<T>(value_type(s), Zero);
                 this->value[1] = tvec2<T>(Zero, value_type(s));
         }
template<typename T> template<typename U , typename V , typename M , typename N > GLM_FUNC_DECL glm::detail::tmat2x2< T >::tmat2x2 (U const & x1, V const & y1, M const & x2, N const & y2) explicit
template<typename T> template<typename U , typename V > GLM_FUNC_DECL glm::detail::tmat2x2< T >::tmat2x2 (tvec2< U > const & v1, tvec2< V > const & v2) explicit
template<typename T> template<typename U > GLM_FUNC_DECL glm::detail::tmat2x2< T >::tmat2x2 (tmat2x2< U > const & m) explicit
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat3x3< T > const & x) explicit
Definition at line 189 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat4x4< T > const & x) explicit
Definition at line 199 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat2x3< T > const & x) explicit
Definition at line 209 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat3x2< T > const & x) explicit
Definition at line 219 of file type_mat2x2.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat2x4< T > const & x) explicit
Definition at line 229 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat4x2< T > const & x) explicit
Definition at line 239 of file type_mat2x2.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat3x4< T > const & x) explicit
Definition at line 249 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat4x3< T > const & x) explicit
Definition at line 259 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
template<typename T> template<typename X1 , typename Y1 , typename X2 , typename Y2 > GLM_FUNC_DECL glm::detail::tmat2x2< T >::tmat2x2 (X1 const & x1, Y1 const & y1, X2 const & x2, Y2 const & y2)
Definition at line 152 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(value_type(x1), value_type(y1));
                 this->value[1] = col_type(value_type(x2), value_type(y2));
         }
template<typename T> template<typename V1 , typename V2 > GLM_FUNC_DECL glm::detail::tmat2x2< T >::tmat2x2 (tvec2< V1 > const & v1, tvec2< V2 > const & v2)
Definition at line 164 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(v1);
                 this->value[1] = col_type(v2);
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER glm::detail::tmat2x2< T >::tmat2x2 (tmat2x2< U > const & m)
Definition at line 179 of file type_mat2x2.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
         }
Member Function Documentation
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T > glm::detail::tmat2x2< T >::_inverse () const
Definition at line 268 of file type_mat2x2.inl.
         {
                 typename tmat2x2<T>::value_type Determinant = this->value[0][0] * this->value[1][1] - this->value[1][0] * this->value[0][1];
                 tmat2x2<T> Inverse(
                         + this->value[1][1] / Determinant,
                         - this->value[0][1] / Determinant,
                         - this->value[1][0] / Determinant,
                         + this->value[0][0] / Determinant);
                 return Inverse;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T >::size_type glm::detail::tmat2x2< T >::col_size () static
Definition at line 39 of file type_mat2x2.inl.
         {
                 return 2;
         }
template<typename T > GLM_FUNC_QUALIFIER GLM_CONSTEXPR tmat2x2< T >::size_type glm::detail::tmat2x2< T >::length () const
Definition at line 33 of file type_mat2x2.inl.
Referenced by glm::isNormalized().
         {
                 return 2;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator*= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator*= (tmat2x2< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator*= (U const & s)
Definition at line 358 of file type_mat2x2.inl.
         {
                 this->value[0] *= s;
                 this->value[1] *= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator*= (tmat2x2< U > const & m)
Definition at line 370 of file type_mat2x2.inl.
         {
                 return (*this = *this * m);
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T > & glm::detail::tmat2x2< T >::operator++ ()
Definition at line 400 of file type_mat2x2.inl.
         {
                 ++this->value[0];
                 ++this->value[1];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator+= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator+= (tmat2x2< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator+= (U const & s)
Definition at line 310 of file type_mat2x2.inl.
         {
                 this->value[0] += s;
                 this->value[1] += s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator+= (tmat2x2< U > const & m)
Definition at line 322 of file type_mat2x2.inl.
         {
                 this->value[0] += m[0];
                 this->value[1] += m[1];
                 return *this;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T > & glm::detail::tmat2x2< T >::operator-- ()
Definition at line 408 of file type_mat2x2.inl.
         {
                 --this->value[0];
                 --this->value[1];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator-= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator-= (tmat2x2< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator-= (U const & s)
Definition at line 334 of file type_mat2x2.inl.
         {
                 this->value[0] -= s;
                 this->value[1] -= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator-= (tmat2x2< U > const & m)
Definition at line 346 of file type_mat2x2.inl.
         {
                 this->value[0] -= m[0];
                 this->value[1] -= m[1];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator/= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator/= (tmat2x2< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator/= (U const & s)
Definition at line 380 of file type_mat2x2.inl.
         {
                 this->value[0] /= s;
                 this->value[1] /= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator/= (tmat2x2< U > const & m)
Definition at line 392 of file type_mat2x2.inl.
         {
                 return (*this = *this / m);
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T > & glm::detail::tmat2x2< T >::operator= (tmat2x2< T > const & m)
Definition at line 286 of file type_mat2x2.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat2x2<T>& glm::detail::tmat2x2< T >::operator= (tmat2x2< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat2x2<T>& glm::detail::tmat2x2< T >::operator= (tmat2x2< U > const & m)
Definition at line 298 of file type_mat2x2.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 return *this;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T >::col_type & glm::detail::tmat2x2< T >::operator[] (size_type i)
Definition at line 56 of file type_mat2x2.inl.
References glm::length().
         {
                 assert(i < this->length());
                 return this->value[i];
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T >::col_type const & glm::detail::tmat2x2< T >::operator[] (size_type i) const
Definition at line 67 of file type_mat2x2.inl.
References glm::length().
         {
                 assert(i < this->length());
                 return this->value[i];
         }
template<typename T > GLM_FUNC_QUALIFIER tmat2x2< T >::size_type glm::detail::tmat2x2< T >::row_size () static
Definition at line 45 of file type_mat2x2.inl.
         {
                 return 2;
         }
Field Documentation
template<typename T> col_type glm::detail::tmat2x2< T >::value[2] private
Definition at line 75 of file type_mat2x2.hpp.
Referenced by glm::detail::tmat2x2< T >::tmat2x2().
The documentation for this struct was generated from the following files:
glm/core/type_mat2x2.hpp
glm/core/type_mat2x2.inl