SDL: GLM_GTX_normalize_dot
GLM_GTX_normalize_dot
GTX Extensions (Experimental)
Dot product of vectors that need to be normalize with a single square root.
Functions
template<typename genType >
genType::value_type glm::normalizeDot (genType const &x, genType const &y)
template<typename genType >
genType::value_type glm::fastNormalizeDot (genType const &x, genType const &y)
Detailed Description
Dot product of vectors that need to be normalize with a single square root.
<glm/gtx/normalized_dot.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > genType::value_type glm::fastNormalizeDot (genType const & x, genType const & y)
Normalize parameters and returns the dot product of x and y. Faster that dot(fastNormalize(x), fastNormalize(y)). From GLM_GTX_normalize_dot extension.
Definition at line 66 of file normalize_dot.inl.
References glm::dot(), and glm::fastInverseSqrt().
         {
                 return
                         glm::dot(x, y) *
                         fastInverseSqrt(glm::dot(x, x) *
                         glm::dot(y, y));
         }
template<typename genType > genType::value_type glm::normalizeDot (genType const & x, genType const & y)
Normalize parameters and returns the dot product of x and y. It's faster that dot(normalize(x), normalize(y)). From GLM_GTX_normalize_dot extension.
Definition at line 14 of file normalize_dot.inl.
References glm::dot(), and glm::inversesqrt().
         {
                 return
                         glm::dot(x, y) *
                         glm::inversesqrt(glm::dot(x, x) *
                         glm::dot(y, y));
         }