SDL: Integer functions
Integer functions
GLM Core
Functions
template<typename genUType >
GLM_FUNC_DECL genUType glm::uaddCarry (genUType const &x, genUType const &y, genUType &carry)
template<typename genUType >
GLM_FUNC_DECL genUType glm::usubBorrow (genUType const &x, genUType const &y, genUType &borrow)
template<typename genUType >
GLM_FUNC_DECL void glm::umulExtended (genUType const &x, genUType const &y, genUType &msb, genUType &lsb)
template<typename genIType >
GLM_FUNC_DECL void glm::imulExtended (genIType const &x, genIType const &y, genIType &msb, genIType &lsb)
template<typename genIUType >
GLM_FUNC_DECL genIUType glm::bitfieldExtract (genIUType const &Value, int const &Offset, int const &Bits)
template<typename genIUType >
GLM_FUNC_DECL genIUType glm::bitfieldInsert (genIUType const &Base, genIUType const &Insert, int const &Offset, int const &Bits)
template<typename genIUType >
GLM_FUNC_DECL genIUType glm::bitfieldReverse (genIUType const &Value)
template<typename T , template< typename > class genIUType>
GLM_FUNC_DECL genIUType< T >
::signed_type glm::bitCount (genIUType< T > const &Value)
template<typename T , template< typename > class genIUType>
GLM_FUNC_DECL genIUType< T >
::signed_type glm::findLSB (genIUType< T > const &Value)
template<typename T , template< typename > class genIUType>
GLM_FUNC_DECL genIUType< T >
::signed_type glm::findMSB (genIUType< T > const &Value)
Detailed Description
These all operate component-wise. The description is per component. The notation [a, b] means the set of bits from bit-number a through bit-number b, inclusive. The lowest-order bit is bit 0.
Function Documentation
template<typename T , template< typename > class genIUType> GLM_FUNC_DECL genIUType<T>::signed_type glm::bitCount (genIUType< T > const & Value)
Returns the number of bits set to 1 in the binary representation of value.
Template Parameters
genIUType Signed or unsigned integer scalar or vector types.
See also
GLSL bitCount man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Todo:
Clarify the declaration to specify that scalars are suported.
Referenced by glm::bitCount().
template<typename genIUType > GLM_FUNC_DECL genIUType glm::bitfieldExtract (genIUType const & Value, int const & Offset, int const & Bits)
Extracts bits [offset, offset + bits - 1] from value, returning them in the least significant bits of the result. For unsigned data types, the most significant bits of the result will be set to zero. For signed data types, the most significant bits will be set to the value of bit offset + base - 1.
If bits is zero, the result will be zero. The result will be undefined if offset or bits is negative, or if the sum of offset and bits is greater than the number of bits used to store the operand.
Template Parameters
genIUType Signed or unsigned integer scalar or vector types.
See also
GLSL bitfieldExtract man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 278 of file func_integer.inl.
References int().
Referenced by glm::bitfieldExtract().
         {
                 int GenSize = int(sizeof(genIUType)) << int(3);
                 assert(Offset + Bits <= GenSize);
                 genIUType ShiftLeft = Bits ? Value << (GenSize - (Bits + Offset)) : genIUType(0);
                 genIUType ShiftBack = ShiftLeft >> genIUType(GenSize - Bits);
                 return ShiftBack;
         }
template<typename genIUType > GLM_FUNC_DECL genIUType glm::bitfieldInsert (genIUType const & Base, genIUType const & Insert, int const & Offset, int const & Bits)
Returns the insertion the bits least-significant bits of insert into base.
The result will have bits [offset, offset + bits - 1] taken from bits [0, bits - 1] of insert, and all other bits taken directly from the corresponding bits of base. If bits is zero, the result will simply be base. The result will be undefined if offset or bits is negative, or if the sum of offset and bits is greater than the number of bits used to store the operand.
Template Parameters
genIUType Signed or unsigned integer scalar or vector types.
See also
GLSL bitfieldInsert man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 339 of file func_integer.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::bitfieldInsert().
         {
                 GLM_STATIC_ASSERT(std::numeric_limits<genIUType>::is_integer, "'bitfieldInsert' only accept integer values");
                 assert(Offset + Bits <= sizeof(genIUType));
                 if(Bits == 0)
                         return Base;
                 genIUType Mask = 0;
                 for(int Bit = Offset; Bit < Offset + Bits; ++Bit)
                         Mask |= (1 << Bit);
                 return (Base & ~Mask) | (Insert & Mask);
         }
template<typename genIUType > GLM_FUNC_DECL genIUType glm::bitfieldReverse (genIUType const & Value)
Returns the reversal of the bits of value. The bit numbered n of the result will be taken from bit (bits - 1) - n of value, where bits is the total number of bits used to represent value.
Template Parameters
genIUType Signed or unsigned integer scalar or vector types.
See also
GLSL bitfieldReverse man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 406 of file func_integer.inl.
References GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(std::numeric_limits<genIUType>::is_integer, "'bitfieldReverse' only accept integer values");
                 genIUType Out = 0;
                 std::size_t BitSize = sizeof(genIUType) * 8;
                 for(std::size_t i = 0; i < BitSize; ++i)
                         if(Value & (genIUType(1) << i))
                                 Out |= genIUType(1) << (BitSize - 1 - i);
                 return Out;
         }
template<typename T , template< typename > class genIUType> GLM_FUNC_DECL genIUType<T>::signed_type glm::findLSB (genIUType< T > const & Value)
Returns the bit number of the least significant bit set to 1 in the binary representation of value. If value is zero, -1 will be returned.
Template Parameters
genIUType Signed or unsigned integer scalar or vector types.
See also
GLSL findLSB man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Todo:
Clarify the declaration to specify that scalars are suported.
Referenced by glm::findLSB().
template<typename T , template< typename > class genIUType> GLM_FUNC_DECL genIUType<T>::signed_type glm::findMSB (genIUType< T > const & Value)
Returns the bit number of the most significant bit in the binary representation of value. For positive integers, the result will be the bit number of the most significant bit set to 1. For negative integers, the result will be the bit number of the most significant bit set to 0. For a value of zero or negative one, -1 will be returned.
Template Parameters
genIUType Signed or unsigned integer scalar or vector types.
See also
GLSL findMSB man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Todo:
Clarify the declaration to specify that scalars are suported.
Referenced by glm::findMSB().
template<typename genIType > GLM_FUNC_DECL void glm::imulExtended (genIType const & x, genIType const & y, genIType & msb, genIType & lsb)
Multiplies 32-bit integers x and y, producing a 64-bit result. The 32 least-significant bits are returned in lsb. The 32 most-significant bits are returned in msb.
Template Parameters
genIType Signed integer scalar or vector types.
See also
GLSL imulExtended man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 216 of file func_integer.inl.
Referenced by glm::imulExtended().
         {
                 detail::highp_int_t ValueX64 = x;
                 detail::highp_int_t ValueY64 = y;
                 detail::highp_int_t Value64 = ValueX64 * ValueY64;
                 msb = *(genIType*)&genIType(Value64 & ((detail::highp_uint_t(1) << detail::highp_uint_t(32)) - detail::highp_uint_t(1)));
                 lsb = *(genIType*)&genIType(Value64 >> detail::highp_uint_t(32));
         }
template<typename genUType > GLM_FUNC_DECL genUType glm::uaddCarry (genUType const & x, genUType const & y, genUType & carry)
Adds 32-bit unsigned integer x and y, returning the sum modulo pow(2, 32). The value carry is set to 0 if the sum was less than pow(2, 32), or to 1 otherwise.
Template Parameters
genUType Unsigned integer scalar or vector types.
See also
GLSL uaddCarry man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 39 of file func_integer.inl.
Referenced by glm::uaddCarry().
         {
                 detail::highp_uint_t Value64 = detail::highp_uint_t(x) + detail::highp_uint_t(y);
                 genUType Result = genUType(Value64 % (detail::highp_uint_t(1) << detail::highp_uint_t(32)));
                 Carry = (Value64 % (detail::highp_uint_t(1) << detail::highp_uint_t(32))) > 1 ? 1 : 0;
                 return Result;
         }
template<typename genUType > GLM_FUNC_DECL void glm::umulExtended (genUType const & x, genUType const & y, genUType & msb, genUType & lsb)
Multiplies 32-bit integers x and y, producing a 64-bit result. The 32 least-significant bits are returned in lsb. The 32 most-significant bits are returned in msb.
Template Parameters
genUType Unsigned integer scalar or vector types.
See also
GLSL umulExtended man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 154 of file func_integer.inl.
Referenced by glm::umulExtended().
         {
                 detail::highp_uint_t ValueX64 = x;
                 detail::highp_uint_t ValueY64 = y;
                 detail::highp_uint_t Value64 = ValueX64 * ValueY64;
                 msb = *(genUType*)&genUType(Value64 & ((detail::highp_uint_t(1) << detail::highp_uint_t(32)) - detail::highp_uint_t(1)));
                 lsb = *(genUType*)&genUType(Value64 >> detail::highp_uint_t(32));
         }
template<typename genUType > GLM_FUNC_DECL genUType glm::usubBorrow (genUType const & x, genUType const & y, genUType & borrow)
Subtracts the 32-bit unsigned integer y from x, returning the difference if non-negative, or pow(2, 32) plus the difference otherwise. The value borrow is set to 0 if x >= y, or to 1 otherwise.
Template Parameters
genUType Unsigned integer scalar or vector types.
See also
GLSL usubBorrow man page
GLSL 4.20.8 specification, section 8.8 Integer Functions
Definition at line 96 of file func_integer.inl.
Referenced by glm::usubBorrow().
         {
                 Borrow = x >= y ? 0 : 1;
                 if(x > y)
                         return genUType(detail::highp_int_t(x) - detail::highp_int_t(y));
                 else
                         return genUType((detail::highp_int_t(1) << detail::highp_int_t(32)) + detail::highp_int_t(x) - detail::highp_int_t(y));
         }