SDL: Geometric functions
Geometric functions
GLM Core
Functions
template<typename genType >
GLM_FUNC_DECL genType::value_type glm::length (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType::value_type glm::distance (genType const &p0, genType const &p1)
template<typename genType >
GLM_FUNC_DECL genType::value_type glm::dot (genType const &x, genType const &y)
template<typename valType >
GLM_FUNC_DECL detail::tvec3
< valType > glm::cross (detail::tvec3< valType > const &x, detail::tvec3< valType > const &y)
template<typename genType >
GLM_FUNC_DECL genType glm::normalize (genType const &x)
template<typename genType >
GLM_FUNC_DECL genType glm::faceforward (genType const &N, genType const &I, genType const &Nref)
template<typename genType >
GLM_FUNC_DECL genType glm::reflect (genType const &I, genType const &N)
template<typename genType >
GLM_FUNC_DECL genType glm::refract (genType const &I, genType const &N, typename genType::value_type const &eta)
Detailed Description
These operate on vectors as vectors, not component-wise.
Function Documentation
template<typename valType > GLM_FUNC_DECL detail::tvec3<valType> glm::cross (detail::tvec3< valType > const & x, detail::tvec3< valType > const & y)
Returns the cross product of x and y.
Template Parameters
valType Floating-point scalar types.
See also
GLSL cross man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Referenced by glm::areCollinear(), glm::intersectLineTriangle(), glm::intersectRayTriangle(), glm::leftHanded(), glm::lookAt(), glm::mixedProduct(), glm::detail::operator*(), glm::orientation(), glm::orientedAngle(), glm::rightHanded(), and glm::triangleNormal().
template<typename genType > GLM_FUNC_DECL genType::value_type glm::distance (genType const & p0, genType const & p1)
Returns the distance betwwen p0 and p1, i.e., length(p0 - p1).
Template Parameters
genType Floating-point vector types.
See also
GLSL distance man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 83 of file func_geometric.inl.
References GLM_STATIC_ASSERT, and glm::length().
Referenced by glm::closestPointOnLine(), and glm::intersectRaySphere().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'distance' only accept floating-point inputs");
                 return length(p1 - p0);
         }
template<typename genType > GLM_FUNC_DECL genType::value_type glm::dot (genType const & x, genType const & y)
Returns the dot product of x and y, i.e., result = x * y.
Template Parameters
genType Floating-point vector types.
See also
GLSL dot man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 132 of file func_geometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::angle(), glm::areOrthogonal(), glm::areOrthonormal(), glm::closestPointOnLine(), glm::faceforward(), glm::fastNormalizeDot(), glm::grad4(), glm::intersectLineSphere(), glm::intersectLineTriangle(), glm::intersectRaySphere(), glm::intersectRayTriangle(), glm::inverse(), glm::leftHanded(), glm::length(), glm::length2(), glm::linearGradient(), glm::lookAt(), glm::luminosity(), glm::mix(), glm::mixedProduct(), glm::noise1(), glm::normalizeDot(), glm::orientation(), glm::orientedAngle(), glm::orthonormalize(), glm::perlin(), glm::proj(), glm::reflect(), glm::refract(), glm::rightHanded(), glm::shortMix(), glm::simplex(), and glm::slerp().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'dot' only accept floating-point inputs");
                 return x * y;
         }
template<typename genType > GLM_FUNC_DECL genType glm::faceforward (genType const & N, genType const & I, genType const & Nref)
If dot(Nref, I) < 0.0, return N, otherwise, return -N.
Template Parameters
genType Floating-point vector types.
See also
GLSL faceforward man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 262 of file func_geometric.inl.
References glm::dot().
         {
                 return dot(Nref, I) < 0 ? N : -N;
         }
template<typename genType > GLM_FUNC_DECL genType::value_type glm::length (genType const & x)
Returns the length of x, i.e., sqrt(x * x).
Template Parameters
genType Floating-point vector types.
See also
GLSL length man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 34 of file func_geometric.inl.
References GLM_STATIC_ASSERT, and glm::sqrt().
Referenced by glm::areCollinear(), glm::areOrthogonal(), glm::ballRand(), glm::diskRand(), glm::distance(), glm::exp(), glm::isNormalized(), glm::isNull(), glm::l2Norm(), glm::normalize(), glm::detail::tvec1< T >::operator[](), glm::detail::tvec2< T >::operator[](), glm::detail::tvec3< T >::operator[](), glm::detail::tvec4< T >::operator[](), glm::detail::tmat2x3< T >::operator[](), glm::detail::tmat2x4< T >::operator[](), glm::detail::tmat3x2< T >::operator[](), glm::detail::tmat3x4< T >::operator[](), glm::detail::tmat2x2< T >::operator[](), glm::detail::tmat4x3< T >::operator[](), glm::detail::tmat4x2< T >::operator[](), glm::detail::tmat3x3< T >::operator[](), glm::detail::tmat4x4< T >::operator[](), glm::polar(), and glm::rotate().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'length' only accept floating-point inputs");
                 genType sqr = x * x;
                 return sqrt(sqr);
         }
template<typename genType > GLM_FUNC_DECL genType glm::normalize (genType const & x)
Returns a vector in the same direction as x but with length of 1.
See also
GLSL normalize man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 213 of file func_geometric.inl.
References GLM_STATIC_ASSERT.
Referenced by glm::axisAngleMatrix(), glm::fastMix(), glm::intersectLineSphere(), glm::lookAt(), glm::orthonormalize(), glm::rotate(), glm::rotate_slow(), and glm::triangleNormal().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'normalize' only accept floating-point inputs");
                 return x < genType(0) ? genType(-1) : genType(1);
         }
template<typename genType > GLM_FUNC_DECL genType glm::reflect (genType const & I, genType const & N)
For the incident vector I and surface orientation N, returns the reflection direction : result = I - 2.0 * dot(N, I) * N.
Template Parameters
genType Floating-point vector types.
See also
GLSL reflect man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 274 of file func_geometric.inl.
References glm::dot().
         {
                 return I - N * dot(N, I) * genType(2);
         }
template<typename genType > GLM_FUNC_DECL genType glm::refract (genType const & I, genType const & N, typename genType::value_type const & eta)
For the incident vector I and surface normal N, and the ratio of indices of refraction eta, return the refraction vector.
Template Parameters
genType Floating-point vector types.
See also
GLSL refract man page
GLSL 4.20.8 specification, section 8.5 Geometric Functions
Definition at line 304 of file func_geometric.inl.
References glm::dot(), and glm::sqrt().
         {
                 //It could be a vector
                 //GLM_STATIC_ASSERT(detail::type<genType>::is_float);
                 typename genType::value_type dotValue = dot(N, I);
                 typename genType::value_type k = typename genType::value_type(1) - eta * eta * (typename genType::value_type(1) - dotValue * dotValue);
                 if(k < typename genType::value_type(0))
                         return genType(0);
                 else
                         return eta * I - (eta * dotValue + sqrt(k)) * N;
         }