SDL: GLM_GTX_quaternion
GLM_GTX_quaternion
GTX Extensions (Experimental)
Extented quaternion types and functions.
Functions
template<typename valType >
detail::tvec3< valType > glm::cross (detail::tquat< valType > const &q, detail::tvec3< valType > const &v)
template<typename valType >
detail::tvec3< valType > glm::cross (detail::tvec3< valType > const &v, detail::tquat< valType > const &q)
template<typename valType >
detail::tquat< valType > glm::squad (detail::tquat< valType > const &q1, detail::tquat< valType > const &q2, detail::tquat< valType > const &s1, detail::tquat< valType > const &s2, valType const &h)
template<typename valType >
detail::tquat< valType > glm::intermediate (detail::tquat< valType > const &prev, detail::tquat< valType > const &curr, detail::tquat< valType > const &next)
template<typename valType >
detail::tquat< valType > glm::exp (detail::tquat< valType > const &q)
template<typename valType >
detail::tquat< valType > glm::log (detail::tquat< valType > const &q)
template<typename valType >
detail::tquat< valType > glm::pow (detail::tquat< valType > const &x, valType const &y)
template<typename valType >
detail::tvec3< valType > glm::rotate (detail::tquat< valType > const &q, detail::tvec3< valType > const &v)
template<typename valType >
detail::tvec4< valType > glm::rotate (detail::tquat< valType > const &q, detail::tvec4< valType > const &v)
template<typename valType >
valType glm::extractRealComponent (detail::tquat< valType > const &q)
template<typename valType >
detail::tmat3x3< valType > glm::toMat3 (detail::tquat< valType > const &x)
template<typename valType >
detail::tmat4x4< valType > glm::toMat4 (detail::tquat< valType > const &x)
template<typename valType >
detail::tquat< valType > glm::toQuat (detail::tmat3x3< valType > const &x)
template<typename valType >
detail::tquat< valType > glm::toQuat (detail::tmat4x4< valType > const &x)
template<typename T >
detail::tquat< T > glm::shortMix (detail::tquat< T > const &x, detail::tquat< T > const &y, T const &a)
template<typename T >
detail::tquat< T > glm::fastMix (detail::tquat< T > const &x, detail::tquat< T > const &y, T const &a)
Detailed Description
Extented quaternion types and functions.
<glm/gtx/quaternion.hpp> need to be included to use these functionalities.
Function Documentation
template<typename valType > detail::tvec3<valType> glm::cross (detail::tquat< valType > const & q, detail::tvec3< valType > const & v)
Compute a cross product between a quaternion and a vector.
See also
GLM_GTX_quaternion
Definition at line 26 of file quaternion.inl.
         {
                 return q * v;
         }
template<typename valType > detail::tvec3<valType> glm::cross (detail::tvec3< valType > const & v, detail::tquat< valType > const & q)
Compute a cross product between a vector and a quaternion.
See also
GLM_GTX_quaternion
Definition at line 16 of file quaternion.inl.
References glm::inverse().
         {
                 return inverse(q) * v;
         }
template<typename valType > detail::tquat<valType> glm::exp (detail::tquat< valType > const & q)
Returns a exp of a quaternion.
See also
GLM_GTX_quaternion
template<typename valType > valType glm::extractRealComponent (detail::tquat< valType > const & q)
Extract the real component of a quaternion.
See also
GLM_GTX_quaternion
template<typename T > detail::tquat<T> glm::fastMix (detail::tquat< T > const & x, detail::tquat< T > const & y, T const & a)
Quaternion normalized linear interpolation.
See also
GLM_GTX_quaternion
Definition at line 200 of file quaternion.inl.
References glm::normalize(), and glm::T.
         {
                 return glm::normalize(x * (T(1) - a) + (y * a));
         }
template<typename valType > detail::tquat<valType> glm::intermediate (detail::tquat< valType > const & prev, detail::tquat< valType > const & curr, detail::tquat< valType > const & next)
Returns an intermediate control point for squad interpolation.
See also
GLM_GTX_quaternion
template<typename valType > detail::tquat<valType> glm::log (detail::tquat< valType > const & q)
Returns a log of a quaternion.
See also
GLM_GTX_quaternion
template<typename valType > detail::tquat<valType> glm::pow (detail::tquat< valType > const & x, valType const & y)
Returns x raised to the y power.
See also
GLM_GTX_quaternion
template<typename valType > detail::tvec3<valType> glm::rotate (detail::tquat< valType > const & q, detail::tvec3< valType > const & v)
Returns quarternion square root.
See also
GLM_GTX_quaternion Rotates a 3 components vector by a quaternion.
GLM_GTX_quaternion
template<typename valType > detail::tvec4<valType> glm::rotate (detail::tquat< valType > const & q, detail::tvec4< valType > const & v)
Rotates a 4 components vector by a quaternion.
See also
GLM_GTX_quaternion
template<typename T > detail::tquat<T> glm::shortMix (detail::tquat< T > const & x, detail::tquat< T > const & y, T const & a)
Quaternion interpolation using the rotation short path.
See also
GLM_GTX_quaternion
Definition at line 158 of file quaternion.inl.
References glm::atan(), glm::dot(), glm::sin(), glm::sqrt(), glm::T, glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
         {
                 if(a <= typename detail::tquat<T>::value_type(0)) return x;
                 if(a >= typename detail::tquat<T>::value_type(1)) return y;
                 T fCos = dot(x, y);
                 detail::tquat<T> y2(y); //BUG!!! tquat<T> y2;
                 if(fCos < T(0))
                 {
                         y2 = -y;
                         fCos = -fCos;
                 }
                 //if(fCos > 1.0f) // problem
                 T k0, k1;
                 if(fCos > T(0.9999))
                 {
                         k0 = T(1) - a;
                         k1 = T(0) + a; //BUG!!! 1.0f + a;
                 }
                 else
                 {
                         T fSin = sqrt(T(1) - fCos * fCos);
                         T fAngle = atan(fSin, fCos);
                         T fOneOverSin = T(1) / fSin;
                         k0 = sin((T(1) - a) * fAngle) * fOneOverSin;
                         k1 = sin((T(0) + a) * fAngle) * fOneOverSin;
                 }
                 return detail::tquat<T>(
                         k0 * x.w + k1 * y2.w,
                         k0 * x.x + k1 * y2.x,
                         k0 * x.y + k1 * y2.y,
                         k0 * x.z + k1 * y2.z);
         }
template<typename valType > detail::tquat<valType> glm::squad (detail::tquat< valType > const & q1, detail::tquat< valType > const & q2, detail::tquat< valType > const & s1, detail::tquat< valType > const & s2, valType const & h)
Compute a point on a path according squad equation. q1 and q2 are control points; s1 and s2 are intermediate control points.
See also
GLM_GTX_quaternion
template<typename valType > detail::tmat3x3<valType> glm::toMat3 (detail::tquat< valType > const & x)
Converts a quaternion to a 3 * 3 matrix.
See also
GLM_GTX_quaternion
Definition at line 148 of file quaternion.hpp.
References glm::mat3_cast().
                                                {return mat3_cast(x);}
template<typename valType > detail::tmat4x4<valType> glm::toMat4 (detail::tquat< valType > const & x)
Converts a quaternion to a 4 * 4 matrix.
See also
GLM_GTX_quaternion
Definition at line 155 of file quaternion.hpp.
References glm::mat4_cast().
                                                {return mat4_cast(x);}
template<typename valType > detail::tquat<valType> glm::toQuat (detail::tmat3x3< valType > const & x)
Converts a 3 * 3 matrix to a quaternion.
See also
GLM_GTX_quaternion
Definition at line 162 of file quaternion.hpp.
References glm::quat_cast().
                                                  {return quat_cast(x);}
template<typename valType > detail::tquat<valType> glm::toQuat (detail::tmat4x4< valType > const & x)
Converts a 4 * 4 matrix to a quaternion.
See also
GLM_GTX_quaternion
Definition at line 169 of file quaternion.hpp.
References glm::quat_cast().
                                                  {return quat_cast(x);}