SDL: GLM_GTX_gradient_paint
GLM_GTX_gradient_paint
GTX Extensions (Experimental)
Functions that return the color of procedural gradient for specific coordinates. <glm/gtx/gradient_paint.hpp> need to be included to use these functionalities.
Functions
template<typename valType >
valType glm::radialGradient (detail::tvec2< valType > const &Center, valType const &Radius, detail::tvec2< valType > const &Focal, detail::tvec2< valType > const &Position)
template<typename valType >
valType glm::linearGradient (detail::tvec2< valType > const &Point0, detail::tvec2< valType > const &Point1, detail::tvec2< valType > const &Position)
Detailed Description
Functions that return the color of procedural gradient for specific coordinates. <glm/gtx/gradient_paint.hpp> need to be included to use these functionalities.
Function Documentation
template<typename valType > valType glm::linearGradient (detail::tvec2< valType > const & Point0, detail::tvec2< valType > const & Point1, detail::tvec2< valType > const & Position)
Return a color from a linear gradient.
See also
- GLM_GTX_gradient_paint
Definition at line 34 of file gradient_paint.inl.
References glm::dot(), glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 detail::tvec2<valType> Dist = Point1 - Point0;
                 return (Dist.x * (Position.x - Point0.x) + Dist.y * (Position.y - Point0.y)) / glm::dot(Dist, Dist);
         }
template<typename valType > valType glm::radialGradient (detail::tvec2< valType > const & Center, valType const & Radius, detail::tvec2< valType > const & Focal, detail::tvec2< valType > const & Position)
Return a color from a radial gradient.
See also
- GLM_GTX_gradient_paint
Definition at line 14 of file gradient_paint.inl.
References glm::pow2(), glm::sqrt(), glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 detail::tvec2<valType> F = Focal - Center;
                 detail::tvec2<valType> D = Position - Focal;
                 valType Radius2 = pow2(Radius);
                 valType Fx2 = pow2(F.x);
                 valType Fy2 = pow2(F.y);
                 valType Numerator = (D.x * F.x + D.y * F.y) + sqrt(Radius2 * (pow2(D.x) + pow2(D.y)) - pow2(D.x * F.y - D.y * F.x));
                 valType Denominator = Radius2 - (Fx2 + Fy2);
                 return Numerator / Denominator;
         }