SDL: GLM_GTC_reciprocal
GLM_GTC_reciprocal
GTC Extensions (Stable)
Define secant, cosecant and cotangent functions.
Functions
template<typename genType >
genType glm::sec (genType const &angle)
template<typename genType >
genType glm::csc (genType const &angle)
template<typename genType >
genType glm::cot (genType const &angle)
template<typename genType >
genType glm::asec (genType const &x)
template<typename genType >
genType glm::acsc (genType const &x)
template<typename genType >
genType glm::acot (genType const &x)
template<typename genType >
genType glm::sech (genType const &angle)
template<typename genType >
genType glm::csch (genType const &angle)
template<typename genType >
genType glm::coth (genType const &angle)
template<typename genType >
genType glm::asech (genType const &x)
template<typename genType >
genType glm::acsch (genType const &x)
template<typename genType >
genType glm::acoth (genType const &x)
Detailed Description
Define secant, cosecant and cotangent functions.
<glm/gtc/reciprocal.hpp> need to be included to use these features.
Function Documentation
template<typename genType > genType glm::acot (genType const & x)
Inverse cotangent function.
See also
GLM_GTC_reciprocal
Definition at line 104 of file reciprocal.inl.
References glm::atan(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'acot' only accept floating-point values");
                 genType const pi_over_2 = genType(3.1415926535897932384626433832795 / 2.0);
                 return pi_over_2 - atan(x);
         }
template<typename genType > genType glm::acoth (genType const & x)
Inverse cotangent hyperbolic function.
See also
GLM_GTC_reciprocal
Definition at line 189 of file reciprocal.inl.
References glm::atanh(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'acoth' only accept floating-point values");
                 return atanh(genType(1) / x);
         }
template<typename genType > genType glm::acsc (genType const & x)
Inverse cosecant function.
See also
GLM_GTC_reciprocal
Definition at line 90 of file reciprocal.inl.
References glm::asin(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'acsc' only accept floating-point values");
                 return asin(genType(1) / x);
         }
template<typename genType > genType glm::acsch (genType const & x)
Inverse cosecant hyperbolic function.
See also
GLM_GTC_reciprocal
Definition at line 175 of file reciprocal.inl.
References glm::asinh(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'acsch' only accept floating-point values");
                 return asinh(genType(1) / x);
         }
template<typename genType > genType glm::asec (genType const & x)
Inverse secant function.
See also
GLM_GTC_reciprocal
Definition at line 76 of file reciprocal.inl.
References glm::acos(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'asec' only accept floating-point values");
                 return acos(genType(1) / x);
         }
template<typename genType > genType glm::asech (genType const & x)
Inverse secant hyperbolic function.
See also
GLM_GTC_reciprocal
Definition at line 161 of file reciprocal.inl.
References glm::acosh(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'asech' only accept floating-point values");
                 return acosh(genType(1) / x);
         }
template<typename genType > genType glm::cot (genType const & angle)
Cotangent function. adjacent / opposite or 1 / tan(x)
See also
GLM_GTC_reciprocal
Definition at line 62 of file reciprocal.inl.
References GLM_STATIC_ASSERT, and glm::tan().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'cot' only accept floating-point values");
                 return genType(1) / glm::tan(angle);
         }
template<typename genType > genType glm::coth (genType const & angle)
Cotangent hyperbolic function.
See also
GLM_GTC_reciprocal
Definition at line 147 of file reciprocal.inl.
References glm::cosh(), GLM_STATIC_ASSERT, and glm::sinh().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'coth' only accept floating-point values");
                 return glm::cosh(angle) / glm::sinh(angle);
         }
template<typename genType > genType glm::csc (genType const & angle)
Cosecant function. hypotenuse / opposite or 1 / sin(x)
See also
GLM_GTC_reciprocal
Definition at line 48 of file reciprocal.inl.
References GLM_STATIC_ASSERT, and glm::sin().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'csc' only accept floating-point values");
                 return genType(1) / glm::sin(angle);
         }
template<typename genType > genType glm::csch (genType const & angle)
Cosecant hyperbolic function.
See also
GLM_GTC_reciprocal
Definition at line 133 of file reciprocal.inl.
References GLM_STATIC_ASSERT, and glm::sinh().
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'csch' only accept floating-point values");
                 return genType(1) / glm::sinh(angle);
         }
template<typename genType > genType glm::sec (genType const & angle)
Secant function. hypotenuse / adjacent or 1 / cos(x)
See also
GLM_GTC_reciprocal
Definition at line 34 of file reciprocal.inl.
References glm::cos(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'sec' only accept floating-point values");
                 return genType(1) / glm::cos(angle);
         }
template<typename genType > genType glm::sech (genType const & angle)
Secant hyperbolic function.
See also
GLM_GTC_reciprocal
Definition at line 119 of file reciprocal.inl.
References glm::cosh(), and GLM_STATIC_ASSERT.
         {
                 GLM_STATIC_ASSERT(detail::type<genType>::is_float, "'sech' only accept floating-point values");
                 return genType(1) / glm::cosh(angle);
         }