SDL: GLM_GTX_spline
GLM_GTX_spline
GTX Extensions (Experimental)
Spline functions.
Functions
template<typename genType >
genType glm::catmullRom (genType const &v1, genType const &v2, genType const &v3, genType const &v4, typename genType::value_type const &s)
template<typename genType >
genType glm::hermite (genType const &v1, genType const &t1, genType const &v2, genType const &t2, typename genType::value_type const &s)
template<typename genType >
genType glm::cubic (genType const &v1, genType const &v2, genType const &v3, genType const &v4, typename genType::value_type const &s)
From GLM_GTX_spline extension.
Detailed Description
Spline functions.
<glm/gtx/spline.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > genType glm::catmullRom (genType const & v1, genType const & v2, genType const & v3, genType const & v4, typename genType::value_type const & s)
Return a point from a catmull rom curve. From GLM_GTX_spline extension.
Definition at line 14 of file spline.inl.
References glm::pow2(), and glm::pow3().
 {
         typename genType::value_type s1 = s;
         typename genType::value_type s2 = pow2(s);
         typename genType::value_type s3 = pow3(s);
         typename genType::value_type f1 = -s3 + typename genType::value_type(2) * s2 - s;
         typename genType::value_type f2 = typename genType::value_type(3) * s3 - typename genType::value_type(5) * s2 + typename genType::value_type(2);
         typename genType::value_type f3 = typename genType::value_type(-3) * s3 + typename genType::value_type(4) * s2 + s;
         typename genType::value_type f4 = s3 - s2;
         return (f1 * v1 + f2 * v2 + f3 * v3 + f4 * v4) / typename genType::value_type(2);
 }
template<typename genType > genType glm::cubic (genType const & v1, genType const & v2, genType const & v3, genType const & v4, typename genType::value_type const & s)
From GLM_GTX_spline extension.
Return a point from a cubic curve.
Definition at line 59 of file spline.inl.
 {
         return ((v1 * s + v2) * s + v3) * s + v4;
 }
template<typename genType > genType glm::hermite (genType const & v1, genType const & t1, genType const & v2, genType const & t2, typename genType::value_type const & s)
Return a point from a hermite curve. From GLM_GTX_spline extension.
Definition at line 37 of file spline.inl.
References glm::pow2(), and glm::pow3().
 {
         typename genType::value_type s1 = s;
         typename genType::value_type s2 = pow2(s);
         typename genType::value_type s3 = pow3(s);
         typename genType::value_type f1 = typename genType::value_type(2) * s3 - typename genType::value_type(3) * s2 + typename genType::value_type(1);
         typename genType::value_type f2 = typename genType::value_type(-2) * s3 + typename genType::value_type(3) * s2;
         typename genType::value_type f3 = s3 - typename genType::value_type(2) * s2 + s;
         typename genType::value_type f4 = s3 - s2;
         return f1 * v1 + f2 * v2 + f3 * t1 + f4 * t2;
 }