SDL: GLM_GTX_norm
GLM_GTX_norm
GTX Extensions (Experimental)
Various ways to compute vector norms.
Functions
template<typename T >
T glm::length2 (T const &x)
template<typename genType >
genType::value_type glm::length2 (genType const &x)
template<typename T >
T glm::length2 (detail::tquat< T > const &q)
template<typename T >
T glm::distance2 (T const &p0, T const &p1)
template<typename genType >
genType::value_type glm::distance2 (genType const &p0, genType const &p1)
template<typename T >
T glm::l1Norm (detail::tvec3< T > const &x, detail::tvec3< T > const &y)
template<typename T >
T glm::l1Norm (detail::tvec3< T > const &v)
template<typename T >
T glm::l2Norm (detail::tvec3< T > const &x, detail::tvec3< T > const &y)
template<typename T >
T glm::l2Norm (detail::tvec3< T > const &x)
template<typename T >
T glm::lxNorm (detail::tvec3< T > const &x, detail::tvec3< T > const &y, unsigned int Depth)
template<typename T >
T glm::lxNorm (detail::tvec3< T > const &x, unsigned int Depth)
Detailed Description
Various ways to compute vector norms.
<glm/gtx/norm.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > T glm::distance2 (T const & p0, T const & p1)
Returns the squared distance between p0 and p1, i.e., length(p0 - p1). From GLM_GTX_norm extension.
Definition at line 59 of file norm.inl.
References glm::length2().
         {
                 return length2(p1 - p0);
         }
template<typename genType > genType::value_type glm::distance2 (genType const & p0, genType const & p1)
Returns the squared distance between p0 and p1, i.e., length(p0 - p1). From GLM_GTX_norm extension.
template<typename T > T glm::l1Norm (detail::tvec3< T > const & x, detail::tvec3< T > const & y)
Returns the L1 norm between x and y. From GLM_GTX_norm extension.
Definition at line 99 of file norm.inl.
References glm::abs(), glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 return abs(b.x - a.x) + abs(b.y - a.y) + abs(b.z - a.z);
         }
template<typename T > T glm::l1Norm (detail::tvec3< T > const & v)
Returns the L1 norm of v. From GLM_GTX_norm extension.
Definition at line 109 of file norm.inl.
References glm::abs(), glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 return abs(v.x) + abs(v.y) + abs(v.z);
         }
template<typename T > T glm::l2Norm (detail::tvec3< T > const & x, detail::tvec3< T > const & y)
Returns the L2 norm between x and y. From GLM_GTX_norm extension.
Definition at line 118 of file norm.inl.
References glm::length().
         {
                 return length(b - a);
         }
template<typename T > T glm::l2Norm (detail::tvec3< T > const & x)
Returns the L2 norm of v. From GLM_GTX_norm extension.
Definition at line 128 of file norm.inl.
References glm::length().
         {
                 return length(v);
         }
template<typename T > T glm::length2 (T const & x)
Returns the squared length of x. From GLM_GTX_norm extension.
Definition at line 14 of file norm.inl.
Referenced by glm::distance2().
         {
                 return x * x;
         }
template<typename genType > genType::value_type glm::length2 (genType const & x)
Returns the squared length of x. From GLM_GTX_norm extension.
template<typename T > T glm::length2 (detail::tquat< T > const & q)
Returns the squared length of x. From GLM_GTX_norm extension.
Definition at line 50 of file norm.inl.
References glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
         {
                 return q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w;
         }
template<typename T > T glm::lxNorm (detail::tvec3< T > const & x, detail::tvec3< T > const & y, unsigned int Depth)
Returns the L norm between x and y. From GLM_GTX_norm extension.
Definition at line 137 of file norm.inl.
References glm::pow(), glm::T, glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 return pow(pow(y.x - x.x, T(Depth)) + pow(y.y - x.y, T(Depth)) + pow(y.z - x.z, T(Depth)), T(1) / T(Depth));
         }
template<typename T > T glm::lxNorm (detail::tvec3< T > const & x, unsigned int Depth)
Returns the L norm of v. From GLM_GTX_norm extension.
Definition at line 148 of file norm.inl.
References glm::pow(), glm::T, glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 return pow(pow(v.x, T(Depth)) + pow(v.y, T(Depth)) + pow(v.z, T(Depth)), T(1) / T(Depth));
         }