SDL: GLM_GTX_euler_angles
GLM_GTX_euler_angles
GTX Extensions (Experimental)
Build matrices from Euler angles.
Functions
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleX (valType const &angleX)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleY (valType const &angleY)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleZ (valType const &angleZ)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleXY (valType const &angleX, valType const &angleY)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleYX (valType const &angleY, valType const &angleX)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleXZ (valType const &angleX, valType const &angleZ)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleZX (valType const &angleZ, valType const &angleX)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleYZ (valType const &angleY, valType const &angleZ)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleZY (valType const &angleZ, valType const &angleY)
template<typename valType >
detail::tmat4x4< valType > glm::eulerAngleYXZ (valType const &yaw, valType const &pitch, valType const &roll)
template<typename valType >
detail::tmat4x4< valType > glm::yawPitchRoll (valType const &yaw, valType const &pitch, valType const &roll)
template<typename T >
detail::tmat2x2< T > glm::orientate2 (T const &angle)
template<typename T >
detail::tmat3x3< T > glm::orientate3 (T const &angle)
template<typename T >
detail::tmat3x3< T > glm::orientate3 (detail::tvec3< T > const &angles)
template<typename T >
detail::tmat4x4< T > glm::orientate4 (detail::tvec3< T > const &angles)
Detailed Description
Build matrices from Euler angles.
<glm/gtx/euler_angles.hpp> need to be included to use these functionalities.
Function Documentation
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleX (valType const & angleX)
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle X.
See also
GLM_GTX_euler_angles
Definition at line 14 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::eulerAngleXZ(), and glm::eulerAngleZX().
         {
                 valType cosX = glm::cos(angleX);
                 valType sinX = glm::sin(angleX);
                 return detail::tmat4x4<valType>(
                         valType(1), valType(0), valType(0), valType(0),
                         valType(0), cosX,               sinX,           valType(0),
                         valType(0),-sinX,               cosX,           valType(0),
                         valType(0), valType(0), valType(0), valType(1));
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleXY (valType const & angleX, valType const & angleY)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Y).
See also
GLM_GTX_euler_angles
Definition at line 62 of file euler_angles.inl.
References glm::cos(), and glm::sin().
         {
                 valType cosX = glm::cos(angleX);
                 valType sinX = glm::sin(angleX);
                 valType cosY = glm::cos(angleY);
                 valType sinY = glm::sin(angleY);
                 return detail::tmat4x4<valType>(
                         cosY,           -sinX * sinY,   cosX * sinY,    valType(0),
                         valType(0), cosX,                       sinX,                   valType(0),
                         -sinY ,         -sinX * cosY,   cosX * cosY,    valType(0),
                         valType(0), valType(0),     valType(0),         valType(1));
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleXZ (valType const & angleX, valType const & angleZ)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (X * Z).
See also
GLM_GTX_euler_angles
Definition at line 100 of file euler_angles.inl.
References glm::eulerAngleX(), and glm::eulerAngleZ().
         {
                 return eulerAngleX(angleX) * eulerAngleZ(angleZ);
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleY (valType const & angleY)
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle Y.
See also
GLM_GTX_euler_angles
Definition at line 30 of file euler_angles.inl.
References glm::cos(), and glm::sin().
         {
                 valType cosY = glm::cos(angleY);
                 valType sinY = glm::sin(angleY);
                 return detail::tmat4x4<valType>(
                         cosY,           valType(0),     sinY,           valType(0),
                         valType(0),     valType(1),     valType(0), valType(0),
                         -sinY,          valType(0),     cosY,           valType(0),
                         valType(0),     valType(0),     valType(0), valType(1));
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleYX (valType const & angleY, valType const & angleX)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X).
See also
GLM_GTX_euler_angles
Definition at line 81 of file euler_angles.inl.
References glm::cos(), and glm::sin().
         {
                 valType cosX = glm::cos(angleX);
                 valType sinX = glm::sin(angleX);
                 valType cosY = glm::cos(angleY);
                 valType sinY = glm::sin(angleY);
                 return detail::tmat4x4<valType>(
                         cosY,                   valType(0),             sinY,                   valType(0),
                         -sinX * sinY,   cosX,                   sinX * cosY,    valType(0),
                         -cosX * sinY,   -sinX,                  cosX * cosY,    valType(0),
                         valType(0),             valType(0),             valType(0),             valType(1));
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleYXZ (valType const & yaw, valType const & pitch, valType const & roll)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
Definition at line 120 of file euler_angles.inl.
References glm::cos(), and glm::sin().
         {
                 valType tmp_ch = glm::cos(yaw);
                 valType tmp_sh = glm::sin(yaw);
                 valType tmp_cp = glm::cos(pitch);
                 valType tmp_sp = glm::sin(pitch);
                 valType tmp_cb = glm::cos(roll);
                 valType tmp_sb = glm::sin(roll);
                 detail::tmat4x4<valType> Result;
                 Result[0][0] = tmp_ch * tmp_cb + tmp_sh * tmp_sp * tmp_sb;
                 Result[0][1] = tmp_sb * tmp_cp;
                 Result[0][2] = -tmp_sh * tmp_cb + tmp_ch * tmp_sp * tmp_sb;
                 Result[0][3] = valType(0);
                 Result[1][0] = -tmp_ch * tmp_sb + tmp_sh * tmp_sp * tmp_cb;
                 Result[1][1] = tmp_cb * tmp_cp;
                 Result[1][2] = tmp_sb * tmp_sh + tmp_ch * tmp_sp * tmp_cb;
                 Result[1][3] = valType(0);
                 Result[2][0] = tmp_sh * tmp_cp;
                 Result[2][1] = -tmp_sp;
                 Result[2][2] = tmp_ch * tmp_cp;
                 Result[2][3] = valType(0);
                 Result[3][0] = valType(0);
                 Result[3][1] = valType(0);
                 Result[3][2] = valType(0);
                 Result[3][3] = valType(1);
                 return Result;
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleYZ (valType const & angleY, valType const & angleZ)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * Z).
See also
GLM_GTX_euler_angles
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleZ (valType const & angleZ)
Creates a 3D 4 * 4 homogeneous rotation matrix from an euler angle Z.
See also
GLM_GTX_euler_angles
Definition at line 46 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::eulerAngleXZ(), and glm::eulerAngleZX().
         {
                 valType cosZ = glm::cos(angleZ);
                 valType sinZ = glm::sin(angleZ);
                 return detail::tmat4x4<valType>(
                         cosZ,           sinZ,           valType(0), valType(0),
                         -sinZ,          cosZ,           valType(0), valType(0),
                         valType(0),     valType(0),     valType(1), valType(0),
                         valType(0),     valType(0),     valType(0), valType(1));
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleZX (valType const & angleZ, valType const & angleX)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Z * X).
See also
GLM_GTX_euler_angles
Definition at line 110 of file euler_angles.inl.
References glm::eulerAngleX(), and glm::eulerAngleZ().
         {
                 return eulerAngleZ(angleZ) * eulerAngleX(angleX);
         }
template<typename valType > detail::tmat4x4<valType> glm::eulerAngleZY (valType const & angleZ, valType const & angleY)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Z * Y).
See also
GLM_GTX_euler_angles
template<typename T > detail::tmat2x2<T> glm::orientate2 (T const & angle)
Creates a 2D 2 * 2 rotation matrix from an euler angle.
See also
GLM_GTX_euler_angles
template<typename T > detail::tmat3x3<T> glm::orientate3 (T const & angle)
Creates a 2D 4 * 4 homogeneous rotation matrix from an euler angle.
See also
GLM_GTX_euler_angles
template<typename T > detail::tmat3x3<T> glm::orientate3 (detail::tvec3< T > const & angles)
Creates a 3D 3 * 3 rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
template<typename T > detail::tmat4x4<T> glm::orientate4 (detail::tvec3< T > const & angles)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
template<typename valType > detail::tmat4x4<valType> glm::yawPitchRoll (valType const & yaw, valType const & pitch, valType const & roll)
Creates a 3D 4 * 4 homogeneous rotation matrix from euler angles (Y * X * Z).
See also
GLM_GTX_euler_angles
Definition at line 155 of file euler_angles.inl.
References glm::cos(), and glm::sin().
Referenced by glm::orientate3(), and glm::orientate4().
         {
                 valType tmp_ch = glm::cos(yaw);
                 valType tmp_sh = glm::sin(yaw);
                 valType tmp_cp = glm::cos(pitch);
                 valType tmp_sp = glm::sin(pitch);
                 valType tmp_cb = glm::cos(roll);
                 valType tmp_sb = glm::sin(roll);
                 detail::tmat4x4<valType> Result;
                 Result[0][0] = tmp_ch * tmp_cb + tmp_sh * tmp_sp * tmp_sb;
                 Result[0][1] = tmp_sb * tmp_cp;
                 Result[0][2] = -tmp_sh * tmp_cb + tmp_ch * tmp_sp * tmp_sb;
                 Result[0][3] = valType(0);
                 Result[1][0] = -tmp_ch * tmp_sb + tmp_sh * tmp_sp * tmp_cb;
                 Result[1][1] = tmp_cb * tmp_cp;
                 Result[1][2] = tmp_sb * tmp_sh + tmp_ch * tmp_sp * tmp_cb;
                 Result[1][3] = valType(0);
                 Result[2][0] = tmp_sh * tmp_cp;
                 Result[2][1] = -tmp_sp;
                 Result[2][2] = tmp_ch * tmp_cp;
                 Result[2][3] = valType(0);
                 Result[3][0] = valType(0);
                 Result[3][1] = valType(0);
                 Result[3][2] = valType(0);
                 Result[3][3] = valType(1);
                 return Result;
         }