SDL: GLM_GTX_matrix_query
GLM_GTX_matrix_query
GTX Extensions (Experimental)
Query to evaluate matrix properties.
Functions
template<typename T >
bool glm::isNull (detail::tmat2x2< T > const &m, T const &epsilon)
template<typename T >
bool glm::isNull (detail::tmat3x3< T > const &m, T const &epsilon)
template<typename T >
bool glm::isNull (detail::tmat4x4< T > const &m, T const &epsilon)
template<typename genType >
bool glm::isIdentity (genType const &m, typename genType::value_type const &epsilon)
template<typename valType >
bool glm::isNormalized (detail::tmat2x2< valType > const &m, valType const &epsilon)
template<typename valType >
bool glm::isNormalized (detail::tmat3x3< valType > const &m, valType const &epsilon)
template<typename valType >
bool glm::isNormalized (detail::tmat4x4< valType > const &m, valType const &epsilon)
template<typename valType , template< typename > class matType>
bool glm::isOrthogonal (matType< valType > const &m, valType const &epsilon)
Detailed Description
Query to evaluate matrix properties.
<glm/gtx/matrix_query.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > bool glm::isIdentity (genType const & m, typename genType::value_type const & epsilon)
Return whether a matrix is an identity matrix. From GLM_GTX_matrix_query extension.
Definition at line 55 of file matrix_query.inl.
References glm::abs(), and glm::epsilon().
         {
                 bool result = true;
                 for(typename genType::size_type i = typename genType::size_type(0); result && i < genType::col_size(); ++i)
                 {
                         for(typename genType::size_type j = typename genType::size_type(0); result && j < i ; ++j)
                                 result = abs(m[i][j]) <= epsilon;
                         if(result)
                                 result = abs(m[i][i] - typename genType::value_type(1)) <= epsilon;
                         for(typename genType::size_type j = i + typename genType::size_type(1); result && j < genType::row_size(); ++j)
                                 result = abs(m[i][j]) <= epsilon;
                 }
                 return result;
         }
template<typename valType > bool glm::isNormalized (detail::tmat2x2< valType > const & m, valType const & epsilon)
Return whether a matrix is a normalized matrix. From GLM_GTX_matrix_query extension.
Referenced by glm::areOrthonormal(), and glm::isNormalized().
template<typename valType > bool glm::isNormalized (detail::tmat3x3< valType > const & m, valType const & epsilon)
Return whether a matrix is a normalized matrix. From GLM_GTX_matrix_query extension.
template<typename valType > bool glm::isNormalized (detail::tmat4x4< valType > const & m, valType const & epsilon)
Return whether a matrix is a normalized matrix. From GLM_GTX_matrix_query extension.
template<typename T > bool glm::isNull (detail::tmat2x2< T > const & m, T const & epsilon)
Return whether a matrix a null matrix. From GLM_GTX_matrix_query extension.
Definition at line 17 of file matrix_query.inl.
References glm::isNull().
Referenced by glm::isNull().
         {
                 bool result = true;
                 for(int i = 0; result && i < 2 ; ++i)
                         result = isNull(m[i], epsilon);
                 return result;
         }
template<typename T > bool glm::isNull (detail::tmat3x3< T > const & m, T const & epsilon)
Return whether a matrix a null matrix. From GLM_GTX_matrix_query extension.
Definition at line 29 of file matrix_query.inl.
References glm::isNull().
         {
                 bool result = true;
                 for(int i = 0; result && i < 3 ; ++i)
                         result = isNull(m[i], epsilon);
                 return result;
         }
template<typename T > bool glm::isNull (detail::tmat4x4< T > const & m, T const & epsilon)
Return whether a matrix is a null matrix. From GLM_GTX_matrix_query extension.
Definition at line 42 of file matrix_query.inl.
References glm::isNull().
         {
                 bool result = true;
                 for(int i = 0; result && i < 4 ; ++i)
                         result = isNull(m[i], epsilon);
                 return result;
         }
template<typename valType , template< typename > class matType> bool glm::isOrthogonal (matType< valType > const & m, valType const & epsilon)
Return whether a matrix is an orthonormalized matrix. From GLM_GTX_matrix_query extension.