SDL: glm::detail::half Class Reference
glm::detail::half Class Reference
#include <type_half.hpp>
Public Member Functions
GLM_FUNC_DECL half ()
GLM_FUNC_DECL half (half const &s)
template<typename U >
GLM_FUNC_DECL half (U const &s)
GLM_FUNC_DECL operator float () const
GLM_FUNC_DECL half & operator= (half const &s)
GLM_FUNC_DECL half & operator+= (half const &s)
GLM_FUNC_DECL half & operator-= (half const &s)
GLM_FUNC_DECL half & operator*= (half const &s)
GLM_FUNC_DECL half & operator/= (half const &s)
GLM_FUNC_DECL half & operator++ ()
GLM_FUNC_DECL half & operator-- ()
GLM_FUNC_DECL float toFloat () const
GLM_FUNC_DECL hdata _data () const
template<typename U >
GLM_FUNC_QUALIFIER half (U const &s)
Private Attributes
hdata data
Detailed Description
Definition at line 42 of file type_half.hpp.
Constructor & Destructor Documentation
GLM_FUNC_QUALIFIER glm::detail::half::half ()
Definition at line 257 of file type_half.inl.
                                       :
                 data(0)
         {}
GLM_FUNC_QUALIFIER glm::detail::half::half (half const & s)
Definition at line 261 of file type_half.inl.
                                                     :
                 data(s.data)
         {}
template<typename U > GLM_FUNC_DECL glm::detail::half::half (U const & s) explicit
template<typename U > GLM_FUNC_QUALIFIER glm::detail::half::half (U const & s)
Definition at line 266 of file type_half.inl.
                                                  :
                 data(toFloat16(float(s)))
         {}
Member Function Documentation
GLM_FUNC_DECL hdata glm::detail::half::_data () const inline
Definition at line 68 of file type_half.hpp.
References data.
Referenced by glm::extractField().
 {return data;}
GLM_FUNC_QUALIFIER glm::detail::half::operator float () const
Definition at line 277 of file type_half.inl.
References glm::detail::toFloat32().
         {
                 return toFloat32(this->data);
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator*= (half const & s)
Definition at line 301 of file type_half.inl.
References data, glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 data = toFloat16(toFloat32(data) * toFloat32(s.data));
                 return *this;
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator++ ()
Definition at line 313 of file type_half.inl.
References glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 float Casted = toFloat32(data);
                 this->data = toFloat16(++Casted);
                 return *this;
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator+= (half const & s)
Definition at line 289 of file type_half.inl.
References data, glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 data = toFloat16(toFloat32(data) + toFloat32(s.data));
                 return *this;
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator-- ()
Definition at line 320 of file type_half.inl.
References glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 float Casted = toFloat32(data);
                 this->data = toFloat16(--Casted);
                 return *this;
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator-= (half const & s)
Definition at line 295 of file type_half.inl.
References data, glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 data = toFloat16(toFloat32(data) - toFloat32(s.data));
                 return *this;
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator/= (half const & s)
Definition at line 307 of file type_half.inl.
References data, glm::detail::toFloat16(), and glm::detail::toFloat32().
         {
                 data = toFloat16(toFloat32(data) / toFloat32(s.data));
                 return *this;
         }
GLM_FUNC_QUALIFIER half & glm::detail::half::operator= (half const & s)
Definition at line 283 of file type_half.inl.
References data.
         {
                 data = s.data;
                 return *this;
         }
GLM_FUNC_DECL float glm::detail::half::toFloat () const inline
Definition at line 66 of file type_half.hpp.
References glm::detail::toFloat32().
Referenced by glm::higherMultiple(), and glm::lowerMultiple().
 {return toFloat32(data);}
Field Documentation
hdata glm::detail::half::data private
Definition at line 71 of file type_half.hpp.
Referenced by _data(), operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
The documentation for this class was generated from the following files:
glm/core/type_half.hpp
glm/core/type_half.inl