SDL: GLM_GTX_vector_query
GLM_GTX_vector_query
GTX Extensions (Experimental)
Query informations of vector types.
Functions
template<typename genType >
bool glm::areCollinear (genType const &v0, genType const &v1, typename genType::value_type const &epsilon)
template<typename genType >
bool glm::areOrthogonal (genType const &v0, genType const &v1, typename genType::value_type const &epsilon)
From GLM_GTX_vector_query extensions.
template<typename genType , template< typename > class vecType>
bool glm::isNormalized (vecType< genType > const &v, genType const &epsilon)
template<typename valType >
bool glm::isNull (detail::tvec2< valType > const &v, valType const &epsilon)
template<typename valType >
bool glm::isNull (detail::tvec3< valType > const &v, valType const &epsilon)
template<typename valType >
bool glm::isNull (detail::tvec4< valType > const &v, valType const &epsilon)
template<typename genType >
bool glm::areOrthonormal (genType const &v0, genType const &v1, typename genType::value_type const &epsilon)
Detailed Description
Query informations of vector types.
<glm/gtx/vector_query.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > bool glm::areCollinear (genType const & v0, genType const & v1, typename genType::value_type const & epsilon)
Check whether two vectors are collinears. From GLM_GTX_vector_query extensions.
template<typename genType > bool glm::areOrthogonal (genType const & v0, genType const & v1, typename genType::value_type const & epsilon)
From GLM_GTX_vector_query extensions.
Check whether two vectors are orthogonals.
Definition at line 52 of file vector_query.inl.
References glm::abs(), glm::dot(), glm::epsilon(), glm::length(), and glm::max().
Referenced by glm::isOrthogonal().
         {
                 return abs(dot(v0, v1)) <= max(
                         typename genType::value_type(1),
                         length(v0)) * max(
                                 typename genType::value_type(1),
                                 length(v1)) * epsilon;
         }
template<typename genType > bool glm::areOrthonormal (genType const & v0, genType const & v1, typename genType::value_type const & epsilon)
Check whether two vectors are orthonormal. From GLM_GTX_vector_query extensions.
Definition at line 155 of file vector_query.inl.
References glm::abs(), glm::dot(), glm::epsilon(), and glm::isNormalized().
         {
                 return isNormalized(v0, epsilon) && isNormalized(v1, epsilon) && (abs(dot(v0, v1)) <= epsilon);
         }
template<typename genType , template< typename > class vecType> bool glm::isNormalized (vecType< genType > const & v, genType const & epsilon)
Check whether a vector is normalized. From GLM_GTX_vector_query extensions.
Definition at line 67 of file vector_query.inl.
References glm::abs(), glm::epsilon(), and glm::length().
         {
                 return abs(length(v) - genType(1)) <= genType(2) * epsilon;
         }
template<typename valType > bool glm::isNull (detail::tvec2< valType > const & v, valType const & epsilon)
Check whether a vector is null. From GLM_GTX_vector_query extensions.
Definition at line 77 of file vector_query.inl.
References glm::epsilon(), and glm::length().
         {
                 return length(v) <= epsilon;
         }
template<typename valType > bool glm::isNull (detail::tvec3< valType > const & v, valType const & epsilon)
Check whether a vector is null. From GLM_GTX_vector_query extensions.
Definition at line 87 of file vector_query.inl.
References glm::epsilon(), and glm::length().
         {
                 return length(v) <= epsilon;
         }
template<typename valType > bool glm::isNull (detail::tvec4< valType > const & v, valType const & epsilon)
Check whether a vector is null. From GLM_GTX_vector_query extensions.
Definition at line 97 of file vector_query.inl.
References glm::epsilon(), and glm::length().
         {
                 return length(v) <= epsilon;
         }