SDL: glm::detail::tmat3x3< T > Struct Template Reference
glm::detail::tmat3x3< T > Struct Template Reference
#include <type_mat2x2.hpp>
Public Types
enum ctor { null }
typedef T value_type
typedef std::size_t size_type
typedef tvec3< T > col_type
typedef tvec3< T > row_type
typedef tmat3x3< T > type
typedef tmat3x3< T > transpose_type
Public Member Functions
GLM_FUNC_DECL GLM_CONSTEXPR
size_type length () const
GLM_FUNC_DECL tmat3x3 ()
GLM_FUNC_DECL tmat3x3 (tmat3x3 const &m)
GLM_FUNC_DECL tmat3x3 (ctor Null)
GLM_FUNC_DECL tmat3x3 (value_type const &s)
GLM_FUNC_DECL tmat3x3 (value_type const &x0, value_type const &y0, value_type const &z0, value_type const &x1, value_type const &y1, value_type const &z1, value_type const &x2, value_type const &y2, value_type const &z2)
GLM_FUNC_DECL tmat3x3 (col_type const &v0, col_type const &v1, col_type const &v2)
template<typename U >
GLM_FUNC_DECL tmat3x3 (U const &x)
template<typename X1 , typename Y1 , typename Z1 , typename X2 , typename Y2 , typename Z2 , typename X3 , typename Y3 , typename Z3 >
GLM_FUNC_DECL tmat3x3 (X1 const &x1, Y1 const &y1, Z1 const &z1, X2 const &x2, Y2 const &y2, Z2 const &z2, X3 const &x3, Y3 const &y3, Z3 const &z3)
template<typename V1 , typename V2 , typename V3 >
GLM_FUNC_DECL tmat3x3 (tvec3< V1 > const &v1, tvec3< V2 > const &v2, tvec3< V3 > const &v3)
template<typename U >
GLM_FUNC_DECL tmat3x3 (tmat3x3< U > const &m)
GLM_FUNC_DECL tmat3x3 (tmat2x2< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat4x4< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat2x3< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat3x2< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat2x4< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat4x2< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat3x4< T > const &x)
GLM_FUNC_DECL tmat3x3 (tmat4x3< T > const &x)
GLM_FUNC_DECL col_type & operator[] (size_type i)
GLM_FUNC_DECL col_type const & operator[] (size_type i) const
GLM_FUNC_DECL tmat3x3< T > & operator= (tmat3x3< T > const &m)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator+= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator+= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator-= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator-= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator*= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator*= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator/= (U const &s)
template<typename U >
GLM_FUNC_DECL tmat3x3< T > & operator/= (tmat3x3< U > const &m)
GLM_FUNC_DECL tmat3x3< T > & operator++ ()
GLM_FUNC_DECL tmat3x3< T > & operator-- ()
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3 (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator+= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator+= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator-= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator-= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator*= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator*= (tmat3x3< U > const &m)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator/= (U const &s)
template<typename U >
GLM_FUNC_QUALIFIER tmat3x3< T > & operator/= (tmat3x3< U > const &m)
Static Public Member Functions
static GLM_FUNC_DECL size_type col_size ()
static GLM_FUNC_DECL size_type row_size ()
Private Attributes
col_type value [3]
Detailed Description
template<typename T>
struct glm::detail::tmat3x3< T >
Definition at line 45 of file type_mat2x2.hpp.
Member Typedef Documentation
template<typename T> typedef tvec3<T> glm::detail::tmat3x3< T >::col_type
Definition at line 57 of file type_mat3x3.hpp.
template<typename T> typedef tvec3<T> glm::detail::tmat3x3< T >::row_type
Definition at line 58 of file type_mat3x3.hpp.
template<typename T> typedef std::size_t glm::detail::tmat3x3< T >::size_type
Definition at line 56 of file type_mat3x3.hpp.
template<typename T> typedef tmat3x3<T> glm::detail::tmat3x3< T >::transpose_type
Definition at line 60 of file type_mat3x3.hpp.
template<typename T> typedef tmat3x3<T> glm::detail::tmat3x3< T >::type
Definition at line 59 of file type_mat3x3.hpp.
template<typename T> typedef T glm::detail::tmat3x3< T >::value_type
Definition at line 55 of file type_mat3x3.hpp.
Member Enumeration Documentation
template<typename T> enum glm::detail::tmat3x3::ctor
Enumerator
null
Definition at line 54 of file type_mat3x3.hpp.
 {null};
Constructor & Destructor Documentation
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 ()
Definition at line 79 of file type_mat3x3.inl.
         {
                 value_type const Zero(0);
                 value_type const One(1);
                 this->value[0] = col_type(One, Zero, Zero);
                 this->value[1] = col_type(Zero, One, Zero);
                 this->value[2] = col_type(Zero, Zero, One);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat3x3< T > const & m)
Definition at line 90 of file type_mat3x3.inl.
References glm::detail::tmat3x3< T >::value.
         {
                 this->value[0] = m.value[0];
                 this->value[1] = m.value[1];
                 this->value[2] = m.value[2];
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (ctor Null) explicit
Definition at line 101 of file type_mat3x3.inl.
         {}
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (value_type const & s) explicit
Definition at line 108 of file type_mat3x3.inl.
         {
                 value_type const Zero(0);
                 this->value[0] = col_type(s, Zero, Zero);
                 this->value[1] = col_type(Zero, s, Zero);
                 this->value[2] = col_type(Zero, Zero, s);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (value_type const & x0, value_type const & y0, value_type const & z0, value_type const & x1, value_type const & y1, value_type const & z1, value_type const & x2, value_type const & y2, value_type const & z2) explicit
Definition at line 120 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(x0, y0, z0);
                 this->value[1] = col_type(x1, y1, z1);
                 this->value[2] = col_type(x2, y2, z2);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (col_type const & v0, col_type const & v1, col_type const & v2) explicit
Definition at line 133 of file type_mat3x3.inl.
         {
                 this->value[0] = v0;
                 this->value[1] = v1;
                 this->value[2] = v2;
         }
template<typename T > template<typename U > GLM_FUNC_DECL glm::detail::tmat3x3< T >::tmat3x3 (U const & x) explicit
Definition at line 149 of file type_mat3x3.inl.
         {
                 value_type const Zero(0);
                 this->value[0] = tvec3<T>(value_type(s), Zero, Zero);
                 this->value[1] = tvec3<T>(Zero, value_type(s), Zero);
                 this->value[2] = tvec3<T>(Zero, Zero, value_type(s));
         }
template<typename T > template<typename X1 , typename Y1 , typename Z1 , typename X2 , typename Y2 , typename Z2 , typename X3 , typename Y3 , typename Z3 > GLM_FUNC_DECL glm::detail::tmat3x3< T >::tmat3x3 (X1 const & x1, Y1 const & y1, Z1 const & z1, X2 const & x2, Y2 const & y2, Z2 const & z2, X3 const & x3, Y3 const & y3, Z3 const & z3) explicit
Definition at line 165 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(value_type(x1), value_type(y1), value_type(z1));
                 this->value[1] = col_type(value_type(x2), value_type(y2), value_type(z2));
                 this->value[2] = col_type(value_type(x3), value_type(y3), value_type(z3));
         }
template<typename T > template<typename V1 , typename V2 , typename V3 > GLM_FUNC_DECL glm::detail::tmat3x3< T >::tmat3x3 (tvec3< V1 > const & v1, tvec3< V2 > const & v2, tvec3< V3 > const & v3) explicit
Definition at line 179 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(v1);
                 this->value[1] = col_type(v2);
                 this->value[2] = col_type(v3);
         }
template<typename T> template<typename U > GLM_FUNC_DECL glm::detail::tmat3x3< T >::tmat3x3 (tmat3x3< U > const & m) explicit
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat2x2< T > const & x) explicit
Definition at line 207 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0], value_type(0));
                 this->value[1] = col_type(m[1], value_type(0));
                 this->value[2] = col_type(detail::tvec2<T>(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat4x4< T > const & x) explicit
Definition at line 218 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
                 this->value[2] = col_type(m[2]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat2x3< T > const & x) explicit
Definition at line 229 of file type_mat3x3.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = col_type(detail::tvec2<T>(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat3x2< T > const & x) explicit
Definition at line 240 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0], value_type(0));
                 this->value[1] = col_type(m[1], value_type(0));
                 this->value[2] = col_type(m[2], value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat2x4< T > const & x) explicit
Definition at line 251 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
                 this->value[2] = col_type(detail::tvec2<T>(0), value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat4x2< T > const & x) explicit
Definition at line 262 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0], value_type(0));
                 this->value[1] = col_type(m[1], value_type(0));
                 this->value[2] = col_type(m[2], value_type(1));
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat3x4< T > const & x) explicit
Definition at line 273 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
                 this->value[2] = col_type(m[2]);
         }
template<typename T > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat4x3< T > const & x) explicit
Definition at line 284 of file type_mat3x3.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = m[2];
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER glm::detail::tmat3x3< T >::tmat3x3 (tmat3x3< U > const & m)
Definition at line 196 of file type_mat3x3.inl.
         {
                 this->value[0] = col_type(m[0]);
                 this->value[1] = col_type(m[1]);
                 this->value[2] = col_type(m[2]);
         }
Member Function Documentation
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T >::size_type glm::detail::tmat3x3< T >::col_size () static
Definition at line 39 of file type_mat3x3.inl.
         {
                 return 3;
         }
template<typename T > GLM_FUNC_QUALIFIER GLM_CONSTEXPR tmat3x3< T >::size_type glm::detail::tmat3x3< T >::length () const
Definition at line 33 of file type_mat3x3.inl.
Referenced by glm::isNormalized(), and glm::outerProduct().
         {
                 return 3;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator*= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator*= (tmat3x3< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator*= (U const & s)
Definition at line 376 of file type_mat3x3.inl.
         {
                 this->value[0] *= s;
                 this->value[1] *= s;
                 this->value[2] *= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator*= (tmat3x3< U > const & m)
Definition at line 389 of file type_mat3x3.inl.
         {
                 return (*this = *this * m);
         }
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T > & glm::detail::tmat3x3< T >::operator++ ()
Definition at line 420 of file type_mat3x3.inl.
         {
                 ++this->value[0];
                 ++this->value[1];
                 ++this->value[2];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator+= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator+= (tmat3x3< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator+= (U const & s)
Definition at line 324 of file type_mat3x3.inl.
         {
                 this->value[0] += s;
                 this->value[1] += s;
                 this->value[2] += s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator+= (tmat3x3< U > const & m)
Definition at line 337 of file type_mat3x3.inl.
         {
                 this->value[0] += m[0];
                 this->value[1] += m[1];
                 this->value[2] += m[2];
                 return *this;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T > & glm::detail::tmat3x3< T >::operator-- ()
Definition at line 429 of file type_mat3x3.inl.
         {
                 --this->value[0];
                 --this->value[1];
                 --this->value[2];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator-= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator-= (tmat3x3< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator-= (U const & s)
Definition at line 350 of file type_mat3x3.inl.
         {
                 this->value[0] -= s;
                 this->value[1] -= s;
                 this->value[2] -= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator-= (tmat3x3< U > const & m)
Definition at line 363 of file type_mat3x3.inl.
         {
                 this->value[0] -= m[0];
                 this->value[1] -= m[1];
                 this->value[2] -= m[2];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator/= (U const & s)
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator/= (tmat3x3< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator/= (U const & s)
Definition at line 399 of file type_mat3x3.inl.
         {
                 this->value[0] /= s;
                 this->value[1] /= s;
                 this->value[2] /= s;
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator/= (tmat3x3< U > const & m)
Definition at line 412 of file type_mat3x3.inl.
         {
                 return (*this = *this / m);
         }
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T > & glm::detail::tmat3x3< T >::operator= (tmat3x3< T > const & m)
Definition at line 298 of file type_mat3x3.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = m[2];
                 return *this;
         }
template<typename T> template<typename U > GLM_FUNC_DECL tmat3x3<T>& glm::detail::tmat3x3< T >::operator= (tmat3x3< U > const & m)
template<typename T> template<typename U > GLM_FUNC_QUALIFIER tmat3x3<T>& glm::detail::tmat3x3< T >::operator= (tmat3x3< U > const & m)
Definition at line 311 of file type_mat3x3.inl.
         {
                 this->value[0] = m[0];
                 this->value[1] = m[1];
                 this->value[2] = m[2];
                 return *this;
         }
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T >::col_type & glm::detail::tmat3x3< T >::operator[] (size_type i)
Definition at line 56 of file type_mat3x3.inl.
References glm::length().
         {
                 assert(i < this->length());
                 return this->value[i];
         }
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T >::col_type const & glm::detail::tmat3x3< T >::operator[] (size_type i) const
Definition at line 67 of file type_mat3x3.inl.
References glm::length().
         {
                 assert(i < this->length());
                 return this->value[i];
         }
template<typename T > GLM_FUNC_QUALIFIER tmat3x3< T >::size_type glm::detail::tmat3x3< T >::row_size () static
Definition at line 45 of file type_mat3x3.inl.
         {
                 return 3;
         }
Field Documentation
template<typename T> col_type glm::detail::tmat3x3< T >::value[3] private
Implementation detail
Definition at line 75 of file type_mat3x3.hpp.
Referenced by glm::detail::tmat3x3< T >::tmat3x3().
The documentation for this struct was generated from the following files:
glm/core/type_mat2x2.hpp
glm/core/type_mat3x3.hpp
glm/core/type_mat3x3.inl