SDL: GLM_GTX_optimum_pow
GLM_GTX_optimum_pow
GTX Extensions (Experimental)
Integer exponentiation of power functions.
Functions
template<typename genType >
genType glm::gtx::pow2 (const genType &x)
template<typename genType >
genType glm::gtx::pow3 (const genType &x)
template<typename genType >
genType glm::gtx::pow4 (const genType &x)
bool glm::gtx::powOfTwo (int num)
detail::tvec2< bool > glm::gtx::powOfTwo (const detail::tvec2< int > &x)
detail::tvec3< bool > glm::gtx::powOfTwo (const detail::tvec3< int > &x)
detail::tvec4< bool > glm::gtx::powOfTwo (const detail::tvec4< int > &x)
Detailed Description
Integer exponentiation of power functions.
<glm/gtx/optimum_pow.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > genType glm::gtx::pow2 (const genType & x)
Returns x raised to the power of 2. From GLM_GTX_optimum_pow extension.
Definition at line 13 of file optimum_pow.inl.
Referenced by glm::catmullRom(), glm::hermite(), and glm::radialGradient().
         {
                 return x * x;
         }
template<typename genType > genType glm::gtx::pow3 (const genType & x)
Returns x raised to the power of 3. From GLM_GTX_optimum_pow extension.
Definition at line 19 of file optimum_pow.inl.
Referenced by glm::catmullRom(), and glm::hermite().
         {
                 return x * x * x;
         }
template<typename genType > genType glm::gtx::pow4 (const genType & x)
Returns x raised to the power of 4. From GLM_GTX_optimum_pow extension.
Definition at line 25 of file optimum_pow.inl.
         {
                 return x * x * x * x;
         }
bool glm::gtx::powOfTwo (int num)
Checks if the parameter is a power of 2 number. From GLM_GTX_optimum_pow extension.
Definition at line 30 of file optimum_pow.inl.
Referenced by glm::powOfTwo().
         {
                 return !(x & (x - 1));
         }
detail::tvec2<bool> glm::gtx::powOfTwo (const detail::tvec2< int > & x)
Checks to determine if the parameter component are power of 2 numbers. From GLM_GTX_optimum_pow extension.
Definition at line 35 of file optimum_pow.inl.
References glm::powOfTwo(), glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 return detail::tvec2<bool>(
                         powOfTwo(x.x),
                         powOfTwo(x.y));
         }
detail::tvec3<bool> glm::gtx::powOfTwo (const detail::tvec3< int > & x)
Checks to determine if the parameter component are power of 2 numbers. From GLM_GTX_optimum_pow extension.
Definition at line 42 of file optimum_pow.inl.
References glm::powOfTwo(), glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 return detail::tvec3<bool>(
                         powOfTwo(x.x),
                         powOfTwo(x.y),
                         powOfTwo(x.z));
         }
detail::tvec4<bool> glm::gtx::powOfTwo (const detail::tvec4< int > & x)
Checks to determine if the parameter component are power of 2 numbers. From GLM_GTX_optimum_pow extension.
Definition at line 50 of file optimum_pow.inl.
References glm::powOfTwo(), glm::detail::tvec4< T >::w, glm::detail::tvec4< T >::x, glm::detail::tvec4< T >::y, and glm::detail::tvec4< T >::z.
         {
                 return detail::tvec4<bool>(
                         powOfTwo(x.x),
                         powOfTwo(x.y),
                         powOfTwo(x.z),
                         powOfTwo(x.w));
         }