SDL: GLM_GTX_rotate_vector
GLM_GTX_rotate_vector
GTX Extensions (Experimental)
Function to directly rotate a vector.
Functions
template<typename T >
detail::tvec2< T > glm::rotate (detail::tvec2< T > const &v, T const &angle)
template<typename T >
detail::tvec3< T > glm::rotate (detail::tvec3< T > const &v, T const &angle, detail::tvec3< T > const &normal)
template<typename T >
detail::tvec4< T > glm::rotate (detail::tvec4< T > const &v, T const &angle, detail::tvec3< T > const &normal)
template<typename T >
detail::tvec3< T > glm::rotateX (detail::tvec3< T > const &v, T const &angle)
template<typename T >
detail::tvec3< T > glm::rotateY (detail::tvec3< T > const &v, T const &angle)
template<typename T >
detail::tvec3< T > glm::rotateZ (detail::tvec3< T > const &v, T const &angle)
template<typename T >
detail::tvec4< T > glm::rotateX (detail::tvec4< T > const &v, T const &angle)
template<typename T >
detail::tvec4< T > glm::rotateY (detail::tvec4< T > const &v, T const &angle)
template<typename T >
detail::tvec4< T > glm::rotateZ (detail::tvec4< T > const &v, T const &angle)
template<typename T >
detail::tmat4x4< T > glm::orientation (detail::tvec3< T > const &Normal, detail::tvec3< T > const &Up)
Detailed Description
Function to directly rotate a vector.
<glm/gtx/rotate_vector.hpp> need to be included to use these functionalities.
Function Documentation
template<typename T > detail::tmat4x4<T> glm::orientation (detail::tvec3< T > const & Normal, detail::tvec3< T > const & Up)
Build a rotation matrix from a normal and a up vector. From GLM_GTX_rotate_vector extension.
Definition at line 199 of file rotate_vector.inl.
References glm::acos(), glm::all(), glm::cross(), glm::degrees(), glm::dot(), glm::equal(), glm::rotate(), and glm::T.
         {
                 if(all(equal(Normal, Up)))
                         return detail::tmat4x4<T>(T(1));
                 detail::tvec3<T> RotationAxis = cross(Up, Normal);
                 T Angle = degrees(acos(dot(Normal, Up)));
                 return rotate(Angle, RotationAxis);
         }
template<typename T > detail::tvec2<T> glm::rotate (detail::tvec2< T > const & v, T const & angle)
Rotate a two dimensional vector. From GLM_GTX_rotate_vector extension.
Definition at line 14 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec2< T >::x, and glm::detail::tvec2< T >::y.
         {
                 detail::tvec2<T> Result;
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos = cos(radians(angle));
                 T const Sin = sin(radians(angle));
 #endif
                 Result.x = v.x * Cos - v.y * Sin;
                 Result.y = v.x * Sin + v.y * Cos;
                 return Result;
         }
template<typename T > detail::tvec3<T> glm::rotate (detail::tvec3< T > const & v, T const & angle, detail::tvec3< T > const & normal)
Rotate a three dimensional vector around an axis. From GLM_GTX_rotate_vector extension.
Definition at line 34 of file rotate_vector.inl.
References glm::rotate().
         {
                 return detail::tmat3x3<T>(glm::rotate(angle, normal)) * v;
         }
template<typename T > detail::tvec4<T> glm::rotate (detail::tvec4< T > const & v, T const & angle, detail::tvec3< T > const & normal)
Rotate a four dimensional vector around an axis. From GLM_GTX_rotate_vector extension.
Definition at line 56 of file rotate_vector.inl.
References glm::rotate().
         {
                 return rotate(angle, normal) * v;
         }
template<typename T > detail::tvec3<T> glm::rotateX (detail::tvec3< T > const & v, T const & angle)
Rotate a three dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 67 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 detail::tvec3<T> Result(v);
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos = cos(radians(angle));
                 T const Sin = sin(radians(angle));
 #endif
                 Result.y = v.y * Cos - v.z * Sin;
                 Result.z = v.y * Sin + v.z * Cos;
                 return Result;
         }
template<typename T > detail::tvec4<T> glm::rotateX (detail::tvec4< T > const & v, T const & angle)
Rotate a four dimentionnals vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 133 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec4< T >::y, and glm::detail::tvec4< T >::z.
         {
                 detail::tvec4<T> Result = v;
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos(cos(radians(angle)));
                 T const Sin(sin(radians(angle)));
 #endif
                 Result.y = v.y * Cos - v.z * Sin;
                 Result.z = v.y * Sin + v.z * Cos;
                 return Result;
         }
template<typename T > detail::tvec3<T> glm::rotateY (detail::tvec3< T > const & v, T const & angle)
Rotate a three dimensional vector around the Y axis. From GLM_GTX_rotate_vector extension.
Definition at line 89 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec3< T >::x, and glm::detail::tvec3< T >::z.
         {
                 detail::tvec3<T> Result = v;
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos(cos(radians(angle)));
                 T const Sin(sin(radians(angle)));
 #endif
                 Result.x =  v.x * Cos + v.z * Sin;
                 Result.z = -v.x * Sin + v.z * Cos;
                 return Result;
         }
template<typename T > detail::tvec4<T> glm::rotateY (detail::tvec4< T > const & v, T const & angle)
Rotate a four dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 155 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec4< T >::x, and glm::detail::tvec4< T >::z.
         {
                 detail::tvec4<T> Result = v;
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos(cos(radians(angle)));
                 T const Sin(sin(radians(angle)));
 #endif
                 Result.x =  v.x * Cos + v.z * Sin;
                 Result.z = -v.x * Sin + v.z * Cos;
                 return Result;
         }
template<typename T > detail::tvec3<T> glm::rotateZ (detail::tvec3< T > const & v, T const & angle)
Rotate a three dimensional vector around the Z axis. From GLM_GTX_rotate_vector extension.
Definition at line 111 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec3< T >::x, and glm::detail::tvec3< T >::y.
         {
                 detail::tvec3<T> Result = v;
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos(cos(radians(angle)));
                 T const Sin(sin(radians(angle)));
 #endif
                 Result.x = v.x * Cos - v.y * Sin;
                 Result.y = v.x * Sin + v.y * Cos;
                 return Result;
         }
template<typename T > detail::tvec4<T> glm::rotateZ (detail::tvec4< T > const & v, T const & angle)
Rotate a four dimensional vector around the X axis. From GLM_GTX_rotate_vector extension.
Definition at line 177 of file rotate_vector.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec4< T >::x, and glm::detail::tvec4< T >::y.
         {
                 detail::tvec4<T> Result = v;
 #ifdef GLM_FORCE_RADIANS
                 T const Cos(cos(angle));
                 T const Sin(sin(angle));
 #else
                 T const Cos(cos(radians(angle)));
                 T const Sin(sin(radians(angle)));
 #endif
                 Result.x = v.x * Cos - v.y * Sin;
                 Result.y = v.x * Sin + v.y * Cos;
                 return Result;
         }