SDL: GLM_GTC_quaternion
GLM_GTC_quaternion
GTC Extensions (Stable)
Defines a templated quaternion type and several quaternion operations.
Typedefs
typedef detail::tquat< float > glm::quat
typedef detail::tquat
< detail::half > glm::hquat
typedef detail::tquat< float > glm::fquat
typedef detail::tquat< double > glm::dquat
typedef detail::tquat< lowp_float > glm::lowp_quat
typedef detail::tquat
< mediump_float > glm::mediump_quat
typedef detail::tquat
< highp_float > glm::highp_quat
Functions
template<typename T >
T glm::length (detail::tquat< T > const &q)
template<typename T >
detail::tquat< T > glm::normalize (detail::tquat< T > const &q)
template<typename T >
T glm::dot (detail::tquat< T > const &q1, detail::tquat< T > const &q2)
template<typename T >
detail::tquat< T > glm::mix (detail::tquat< T > const &x, detail::tquat< T > const &y, T const &a)
template<typename T >
detail::tquat< T > glm::lerp (detail::tquat< T > const &x, detail::tquat< T > const &y, T const &a)
template<typename T >
detail::tquat< T > glm::slerp (detail::tquat< T > const &x, detail::tquat< T > const &y, T const &a)
Returns the slurp interpolation between two quaternions.
template<typename T >
detail::tquat< T > glm::conjugate (detail::tquat< T > const &q)
template<typename T >
detail::tquat< T > glm::inverse (detail::tquat< T > const &q)
template<typename T >
detail::tquat< T > glm::rotate (detail::tquat< T > const &q, typename detail::tquat< T >::value_type const &angle, detail::tvec3< T > const &axis)
template<typename T >
detail::tvec3< T > glm::eulerAngles (detail::tquat< T > const &x)
template<typename valType >
valType glm::roll (detail::tquat< valType > const &x)
template<typename valType >
valType glm::pitch (detail::tquat< valType > const &x)
template<typename valType >
valType glm::yaw (detail::tquat< valType > const &x)
template<typename T >
detail::tmat3x3< T > glm::mat3_cast (detail::tquat< T > const &x)
template<typename T >
detail::tmat4x4< T > glm::mat4_cast (detail::tquat< T > const &x)
template<typename T >
detail::tquat< T > glm::quat_cast (detail::tmat3x3< T > const &x)
template<typename T >
detail::tquat< T > glm::quat_cast (detail::tmat4x4< T > const &x)
template<typename valType >
valType glm::angle (detail::tquat< valType > const &x)
template<typename valType >
detail::tvec3< valType > glm::axis (detail::tquat< valType > const &x)
template<typename valType >
detail::tquat< valType > glm::angleAxis (valType const &angle, valType const &x, valType const &y, valType const &z)
template<typename valType >
detail::tquat< valType > glm::angleAxis (valType const &angle, detail::tvec3< valType > const &axis)
Detailed Description
Defines a templated quaternion type and several quaternion operations.
<glm/gtc/quaternion.hpp> need to be included to use these functionalities.
Typedef Documentation
typedef detail::tquat<double> glm::dquat
Quaternion of double-precision floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 359 of file quaternion.hpp.
typedef detail::tquat<float> glm::fquat
Quaternion of single-precision floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 354 of file quaternion.hpp.
typedef detail::tquat<highp_float> glm::highp_quat
Quaternion of high precision floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 374 of file quaternion.hpp.
typedef detail::tquat<detail::half> glm::hquat
Quaternion of half-precision floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 349 of file quaternion.hpp.
typedef detail::tquat<lowp_float> glm::lowp_quat
Quaternion of low precision floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 364 of file quaternion.hpp.
typedef detail::tquat<mediump_float> glm::mediump_quat
Quaternion of medium precision floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 369 of file quaternion.hpp.
typedef detail::tquat<float> glm::quat
Quaternion of floating-point numbers.
See also
GLM_GTC_quaternion
Definition at line 344 of file quaternion.hpp.
Function Documentation
template<typename valType > valType glm::angle (detail::tquat< valType > const & x)
Returns the quaternion rotation angle.
See also
GLM_GTC_quaternion
Referenced by glm::rotate(), and glm::rotate_slow().
template<typename valType > detail::tquat<valType> glm::angleAxis (valType const & angle, valType const & x, valType const & y, valType const & z)
Build a quaternion from an angle and a normalized axis.
Parameters
angle Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
x x component of the x-axis, x, y, z must be a normalized axis
y y component of the y-axis, x, y, z must be a normalized axis
z z component of the z-axis, x, y, z must be a normalized axis
See also
GLM_GTC_quaternion
Definition at line 759 of file quaternion.inl.
References glm::angleAxis().
Referenced by glm::angleAxis().
         {
                 return angleAxis(angle, detail::tvec3<valType>(x, y, z));
         }
template<typename valType > detail::tquat<valType> glm::angleAxis (valType const & angle, detail::tvec3< valType > const & axis)
Build a quaternion from an angle and a normalized axis.
Parameters
angle Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Axis of the quaternion, must be normalized.
See also
GLM_GTC_quaternion
Definition at line 771 of file quaternion.inl.
References glm::cos(), glm::radians(), glm::sin(), glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tvec3< T >::x, glm::detail::tquat< T >::y, glm::detail::tvec3< T >::y, glm::detail::tquat< T >::z, and glm::detail::tvec3< T >::z.
         {
                 detail::tquat<valType> result;
 #ifdef GLM_FORCE_RADIANS
                 valType a(angle);
 #else
                 valType a(glm::radians(angle));
 #endif
                 valType s = glm::sin(a * valType(0.5));
                 result.w = glm::cos(a * valType(0.5));
                 result.x = v.x * s;
                 result.y = v.y * s;
                 result.z = v.z * s;
                 return result;
         }
template<typename valType > detail::tvec3<valType> glm::axis (detail::tquat< valType > const & x)
Returns the q rotation axis.
See also
GLM_GTC_quaternion
Referenced by glm::rotate(), and glm::rotate_slow().
template<typename T > detail::tquat<T> glm::conjugate (detail::tquat< T > const & q)
Returns the q conjugate.
See also
GLM_GTC_quaternion
Definition at line 530 of file quaternion.inl.
References glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
Referenced by glm::inverse().
         {
                 return detail::tquat<T>(q.w, -q.x, -q.y, -q.z);
         }
template<typename T > T glm::dot (detail::tquat< T > const & q1, detail::tquat< T > const & q2)
Returns dot product of q1 and q2, i.e., q1[0] * q2[0] + q1[1] * q2[1] + ...
See also
GLM_GTC_quaternion
Definition at line 344 of file quaternion.inl.
References glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
         {
                 return q1.x * q2.x + q1.y * q2.y + q1.z * q2.z + q1.w * q2.w;
         }
template<typename T > detail::tvec3<T> glm::eulerAngles (detail::tquat< T > const & x)
Returns euler angles, yitch as x, yaw as y, roll as z.
See also
GLM_GTC_quaternion
Definition at line 579 of file quaternion.inl.
References glm::pitch(), glm::roll(), and glm::yaw().
         {
                 return detail::tvec3<T>(pitch(x), yaw(x), roll(x));
         }
template<typename T > detail::tquat<T> glm::inverse (detail::tquat< T > const & q)
Returns the q inverse.
See also
GLM_GTC_quaternion
Definition at line 539 of file quaternion.inl.
References glm::conjugate(), and glm::dot().
         {
                 return conjugate(q) / dot(q, q);
         }
template<typename T > T glm::length (detail::tquat< T > const & q)
Returns the length of the quaternion.
See also
GLM_GTC_quaternion
Definition at line 322 of file quaternion.inl.
References glm::dot(), and glm::sqrt().
         {
                 return glm::sqrt(dot(q, q));
         }
template<typename T > detail::tquat<T> glm::lerp (detail::tquat< T > const & x, detail::tquat< T > const & y, T const & a)
Linear interpolation of two quaternions. The interpolation is oriented.
Parameters
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined in the range [0, 1].
Template Parameters
T Value type used to build the quaternion. Supported: half, float or double.
See also
GLM_GTC_quaternion
Definition at line 477 of file quaternion.inl.
References glm::T.
         {
                 // Lerp is only defined in [0, 1]
                 assert(a >= T(0));
                 assert(a <= T(1));
                 return x * (T(1) - a) + (y * a);
         }
template<typename T > detail::tmat3x3<T> glm::mat3_cast (detail::tquat< T > const & x)
Converts a quaternion to a 3 * 3 matrix.
See also
GLM_GTC_quaternion
Definition at line 627 of file quaternion.inl.
References glm::T, glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
Referenced by glm::mat4_cast(), and glm::toMat3().
         {
                 detail::tmat3x3<T> Result(T(1));
                 Result[0][0] = 1 - 2 * q.y * q.y - 2 * q.z * q.z;
                 Result[0][1] = 2 * q.x * q.y + 2 * q.w * q.z;
                 Result[0][2] = 2 * q.x * q.z - 2 * q.w * q.y;
                 Result[1][0] = 2 * q.x * q.y - 2 * q.w * q.z;
                 Result[1][1] = 1 - 2 * q.x * q.x - 2 * q.z * q.z;
                 Result[1][2] = 2 * q.y * q.z + 2 * q.w * q.x;
                 Result[2][0] = 2 * q.x * q.z + 2 * q.w * q.y;
                 Result[2][1] = 2 * q.y * q.z - 2 * q.w * q.x;
                 Result[2][2] = 1 - 2 * q.x * q.x - 2 * q.y * q.y;
                 return Result;
         }
template<typename T > detail::tmat4x4<T> glm::mat4_cast (detail::tquat< T > const & x)
Converts a quaternion to a 4 * 4 matrix.
See also
GLM_GTC_quaternion
Definition at line 648 of file quaternion.inl.
References glm::mat3_cast().
Referenced by glm::toMat4().
         {
                 return detail::tmat4x4<T>(mat3_cast(q));
         }
template<typename T > detail::tquat<T> glm::mix (detail::tquat< T > const & x, detail::tquat< T > const & y, T const & a)
Spherical linear interpolation of two quaternions. The interpolation is oriented and the rotation is performed at constant speed. For short path spherical linear interpolation, use the slerp function.
Parameters
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
Template Parameters
T Value type used to build the quaternion. Supported: half, float or double.
See also
GLM_GTC_quaternion
- slerp(detail::tquat<T> const & x, detail::tquat<T> const & y, T const & a)
Definition at line 449 of file quaternion.inl.
References glm::acos(), glm::dot(), glm::mix(), glm::sin(), glm::T, glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
         {
                 T cosTheta = dot(x, y);
                 // Perform a linear interpolation when cosTheta is close to 1 to avoid side effect of sin(angle) becoming a zero denominator
                 if(cosTheta > T(1) - epsilon<T>())
                 {
                         // Linear interpolation
                         return detail::tquat<T>(
                                 mix(x.w, y.w, a),
                                 mix(x.x, y.x, a),
                                 mix(x.y, y.y, a),
                                 mix(x.z, y.z, a));
                 }
                 else
                 {
                         // Essential Mathematics, page 467
                         T angle = acos(cosTheta);
                         return (sin((T(1) - a) * angle) * x + sin(a * angle) * y) / sin(angle);
                 }
         }
template<typename T > detail::tquat<T> glm::normalize (detail::tquat< T > const & q)
Returns the normalized quaternion.
See also
GLM_GTC_quaternion
Definition at line 331 of file quaternion.inl.
References glm::length(), glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
         {
                 typename detail::tquat<T>::value_type len = length(q);
                 if(len <= typename detail::tquat<T>::value_type(0)) // Problem
                         return detail::tquat<T>(1, 0, 0, 0);
                 typename detail::tquat<T>::value_type oneOverLen = typename detail::tquat<T>::value_type(1) / len;
                 return detail::tquat<T>(q.w * oneOverLen, q.x * oneOverLen, q.y * oneOverLen, q.z * oneOverLen);
         }
template<typename valType > valType glm::pitch (detail::tquat< valType > const & x)
Returns pitch value of euler angles expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
See also
GLM_GTX_quaternion
Definition at line 601 of file quaternion.inl.
References glm::atan(), glm::atan2(), glm::degrees(), glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
Referenced by glm::eulerAngles().
         {
 #ifdef GLM_FORCE_RADIANS
                 return valType(atan2(valType(2) * (q.y * q.z + q.w * q.x), q.w * q.w - q.x * q.x - q.y * q.y + q.z * q.z));
 #else
                 return glm::degrees(atan(valType(2) * (q.y * q.z + q.w * q.x), q.w * q.w - q.x * q.x - q.y * q.y + q.z * q.z));
 #endif
         }
template<typename T > detail::tquat<T> glm::quat_cast (detail::tmat3x3< T > const & x)
Converts a 3 * 3 matrix to a quaternion.
See also
GLM_GTC_quaternion
Definition at line 657 of file quaternion.inl.
References glm::sqrt(), glm::T, glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
Referenced by glm::quat_cast(), glm::toQuat(), and glm::detail::tquat< T >::tquat().
         {
                 typename detail::tquat<T>::value_type fourXSquaredMinus1 = m[0][0] - m[1][1] - m[2][2];
                 typename detail::tquat<T>::value_type fourYSquaredMinus1 = m[1][1] - m[0][0] - m[2][2];
                 typename detail::tquat<T>::value_type fourZSquaredMinus1 = m[2][2] - m[0][0] - m[1][1];
                 typename detail::tquat<T>::value_type fourWSquaredMinus1 = m[0][0] + m[1][1] + m[2][2];
                 int biggestIndex = 0;
                 typename detail::tquat<T>::value_type fourBiggestSquaredMinus1 = fourWSquaredMinus1;
                 if(fourXSquaredMinus1 > fourBiggestSquaredMinus1)
                 {
                         fourBiggestSquaredMinus1 = fourXSquaredMinus1;
                         biggestIndex = 1;
                 }
                 if(fourYSquaredMinus1 > fourBiggestSquaredMinus1)
                 {
                         fourBiggestSquaredMinus1 = fourYSquaredMinus1;
                         biggestIndex = 2;
                 }
                 if(fourZSquaredMinus1 > fourBiggestSquaredMinus1)
                 {
                         fourBiggestSquaredMinus1 = fourZSquaredMinus1;
                         biggestIndex = 3;
                 }
                 typename detail::tquat<T>::value_type biggestVal = sqrt(fourBiggestSquaredMinus1 + T(1)) * T(0.5);
                 typename detail::tquat<T>::value_type mult = T(0.25) / biggestVal;
                 detail::tquat<T> Result;
                 switch(biggestIndex)
                 {
                 case 0:
                         Result.w = biggestVal;
                         Result.x = (m[1][2] - m[2][1]) * mult;
                         Result.y = (m[2][0] - m[0][2]) * mult;
                         Result.z = (m[0][1] - m[1][0]) * mult;
                         break;
                 case 1:
                         Result.w = (m[1][2] - m[2][1]) * mult;
                         Result.x = biggestVal;
                         Result.y = (m[0][1] + m[1][0]) * mult;
                         Result.z = (m[2][0] + m[0][2]) * mult;
                         break;
                 case 2:
                         Result.w = (m[2][0] - m[0][2]) * mult;
                         Result.x = (m[0][1] + m[1][0]) * mult;
                         Result.y = biggestVal;
                         Result.z = (m[1][2] + m[2][1]) * mult;
                         break;
                 case 3:
                         Result.w = (m[0][1] - m[1][0]) * mult;
                         Result.x = (m[2][0] + m[0][2]) * mult;
                         Result.y = (m[1][2] + m[2][1]) * mult;
                         Result.z = biggestVal;
                         break;
         default:                // Silence a -Wswitch-default warning in GCC. Should never actually get here. Assert is just for sanity.
             assert(false);
             break;
                 }
                 return Result;
         }
template<typename T > detail::tquat<T> glm::quat_cast (detail::tmat4x4< T > const & x)
Converts a 4 * 4 matrix to a quaternion.
See also
GLM_GTC_quaternion
Definition at line 724 of file quaternion.inl.
References glm::quat_cast().
         {
                 return quat_cast(detail::tmat3x3<T>(m4));
         }
template<typename valType > valType glm::roll (detail::tquat< valType > const & x)
Returns roll value of euler angles expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
See also
GLM_GTX_quaternion
Definition at line 588 of file quaternion.inl.
References glm::atan(), glm::atan2(), glm::degrees(), glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
Referenced by glm::eulerAngles().
         {
 #ifdef GLM_FORCE_RADIANS
                 return valType(atan2(valType(2) * (q.x * q.y + q.w * q.z), q.w * q.w + q.x * q.x - q.y * q.y - q.z * q.z));
 #else
                 return glm::degrees(atan(valType(2) * (q.x * q.y + q.w * q.z), q.w * q.w + q.x * q.x - q.y * q.y - q.z * q.z));
 #endif
         }
template<typename T > detail::tquat<T> glm::rotate (detail::tquat< T > const & q, typename detail::tquat< T >::value_type const & angle, detail::tvec3< T > const & axis)
Rotates a quaternion from an vector of 3 components axis and an angle.
Parameters
q Source orientation
angle Angle expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
axis Axis of the rotation, must be normalized.
See also
GLM_GTC_quaternion
Definition at line 548 of file quaternion.inl.
References glm::abs(), glm::cos(), glm::length(), glm::radians(), glm::sin(), glm::T, glm::detail::tvec3< T >::x, glm::detail::tvec3< T >::y, and glm::detail::tvec3< T >::z.
         {
                 detail::tvec3<T> Tmp = v;
                 // Axis of rotation must be normalised
                 typename detail::tquat<T>::value_type len = glm::length(Tmp);
                 if(abs(len - T(1)) > T(0.001))
                 {
                         T oneOverLen = T(1) / len;
                         Tmp.x *= oneOverLen;
                         Tmp.y *= oneOverLen;
                         Tmp.z *= oneOverLen;
                 }
 #ifdef GLM_FORCE_RADIANS
                 typename detail::tquat<T>::value_type const AngleRad(angle);
 #else
                 typename detail::tquat<T>::value_type const AngleRad = radians(angle);
 #endif
                 typename detail::tquat<T>::value_type const Sin = sin(AngleRad * T(0.5));
                 return q * detail::tquat<T>(cos(AngleRad * T(0.5)), Tmp.x * Sin, Tmp.y * Sin, Tmp.z * Sin);
                 //return gtc::quaternion::cross(q, detail::tquat<T>(cos(AngleRad * T(0.5)), Tmp.x * fSin, Tmp.y * fSin, Tmp.z * fSin));
         }
template<typename T > detail::tquat<T> glm::slerp (detail::tquat< T > const & x, detail::tquat< T > const & y, T const & a)
Returns the slurp interpolation between two quaternions.
Spherical linear interpolation of two quaternions. The interpolation always take the short path and the rotation is performed at constant speed.
Parameters
x A quaternion
y A quaternion
a Interpolation factor. The interpolation is defined beyond the range [0, 1].
Template Parameters
T Value type used to build the quaternion. Supported: half, float or double.
See also
GLM_GTC_quaternion
Definition at line 492 of file quaternion.inl.
References glm::acos(), glm::dot(), glm::mix(), glm::sin(), glm::T, glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
         {
                 detail::tquat<T> z = y;
                 T cosTheta = dot(x, y);
                 // If cosTheta < 0, the interpolation will take the long way around the sphere.
                 // To fix this, one quat must be negated.
                 if (cosTheta < T(0))
                 {
                         z        = -y;
                         cosTheta = -cosTheta;
                 }
                 // Perform a linear interpolation when cosTheta is close to 1 to avoid side effect of sin(angle) becoming a zero denominator
                 if(cosTheta > T(1) - epsilon<T>())
                 {
                         // Linear interpolation
                         return detail::tquat<T>(
                                 mix(x.w, z.w, a),
                                 mix(x.x, z.x, a),
                                 mix(x.y, z.y, a),
                                 mix(x.z, z.z, a));
                 }
                 else
                 {
                         // Essential Mathematics, page 467
                         T angle = acos(cosTheta);
                         return (sin((T(1) - a) * angle) * x + sin(a * angle) * z) / sin(angle);
                 }
         }
template<typename valType > valType glm::yaw (detail::tquat< valType > const & x)
Returns yaw value of euler angles expressed in radians if GLM_FORCE_RADIANS is define or degrees otherwise.
See also
GLM_GTX_quaternion
Definition at line 614 of file quaternion.inl.
References glm::asin(), glm::degrees(), glm::detail::tquat< T >::w, glm::detail::tquat< T >::x, glm::detail::tquat< T >::y, and glm::detail::tquat< T >::z.
Referenced by glm::eulerAngles().
         {
 #ifdef GLM_FORCE_RADIANS
                 return asin(valType(-2) * (q.x * q.z - q.w * q.y));
 #else
                 return glm::degrees(asin(valType(-2) * (q.x * q.z - q.w * q.y)));
 #endif
         }