SDL: GLM_GTX_wrap
GLM_GTX_wrap
GTX Extensions (Experimental)
Wrapping mode of texture coordinates.
Functions
template<typename genType >
genType glm::clamp (genType const &Texcoord)
template<typename genType >
genType glm::repeat (genType const &Texcoord)
template<typename genType >
genType glm::mirrorRepeat (genType const &Texcoord)
Detailed Description
Wrapping mode of texture coordinates.
<glm/gtx/wrap.hpp> need to be included to use these functionalities.
Function Documentation
template<typename genType > genType glm::clamp (genType const & Texcoord)
Simulate GL_CLAMP OpenGL wrap mode From GLM_GTX_wrap extension.
Definition at line 17 of file wrap.inl.
References glm::clamp().
         {
                 return glm::clamp(Texcoord, genType(0), genType(1));
         }
template<typename genType > genType glm::mirrorRepeat (genType const & Texcoord)
Simulate GL_MIRROR_REPEAT OpenGL wrap mode From GLM_GTX_wrap extension.
Definition at line 113 of file wrap.inl.
References glm::floor().
Referenced by glm::mirrorRepeat().
         {
                 genType const Clamp = genType(int(glm::floor(Texcoord)) % 2);
                 genType const Floor = glm::floor(Texcoord);
                 genType const Rest = Texcoord - Floor;
                 genType const Mirror = Clamp + Rest;
                 genType Out;
                 if(Mirror >= genType(1))
                         Out = genType(1) - Rest;
                 else
                         Out = Rest;
                 return Out;
         }
template<typename genType > genType glm::repeat (genType const & Texcoord)
Simulate GL_REPEAT OpenGL wrap mode From GLM_GTX_wrap extension.
Definition at line 65 of file wrap.inl.
References glm::fract().
Referenced by glm::repeat().
         {
                 return glm::fract(Texcoord);
         }